(() => {
  'use strict';
  const R=(key,label,min,max,step,initial,unit='',digits=0)=>({key,label,min,max,step,initial,unit,digits});
  const N=(label,value)=>({label,value:String(value)});
  const sims=[
    {id:'units',grade:11,group:'FOUNDATIONS',chapter:'Units and Measurements',title:'Vernier caliper',description:'Slide the jaw around an object and read a small length on the main and vernier scales.',formula:'Length = MSR + VSR',observe:'The vernier scale resolves lengths between main-scale markings.',try:'Move the jaw by just 0.01 cm and watch the reading change.',controls:[R('measure','Object length',.5,5,.01,3.24,'cm',2)],metrics:p=>[N('Measured length',`${p.measure.toFixed(2)} cm`),N('Least count','0.01 cm')],draw:'units'},
    {id:'kinematics',grade:11,group:'MECHANICS',chapter:'Motion in a Straight Line',title:'Motion in one dimension',description:'Follow a cart and watch its position graph curve as its velocity changes.',formula:'x = ut + ½at²',observe:'With constant acceleration, velocity changes steadily while the position graph bends.',try:'Set acceleration to zero. What happens to the graph?',controls:[R('velocity','Initial velocity',1,18,1,7,'m/s'),R('acceleration','Acceleration',0,5,.2,2,'m/s²',1)],metrics:(p,t)=>{let q=t%8;return[N('Position',`${(p.velocity*q+.5*p.acceleration*q*q).toFixed(1)} m`),N('Current speed',`${(p.velocity+p.acceleration*q).toFixed(1)} m/s`),N('Acceleration',`${p.acceleration.toFixed(1)} m/s²`)]},draw:'kinematics'},
    {id:'projectile',grade:11,group:'MECHANICS',chapter:'Motion in a Plane',title:'Projectile motion',description:'Launch an object and see how horizontal and vertical motion combine to form its path.',formula:'R = v² sin(2θ) / g',observe:'Horizontal velocity stays constant; gravity changes the vertical velocity every second.',try:'Try 30° and 60° with the same speed. Compare their ranges.',controls:[R('speed','Launch speed',10,35,1,24,'m/s'),R('angle','Launch angle',15,75,1,48,'°'),R('gravity','Gravity',3,15,.1,9.8,'m/s²',1)],metrics:p=>{let th=p.angle*Math.PI/180;return[N('Range',`${(p.speed**2*Math.sin(2*th)/p.gravity).toFixed(1)} m`),N('Maximum height',`${(p.speed**2*Math.sin(th)**2/(2*p.gravity)).toFixed(1)} m`),N('Time of flight',`${(2*p.speed*Math.sin(th)/p.gravity).toFixed(2)} s`)]},draw:'projectile'},
    {id:'forces',grade:11,group:'MECHANICS',chapter:'Laws of Motion',title:'Forces and friction',description:'Push a block and see when the applied force overcomes friction.',formula:'Fₙₑₜ = ma',observe:'The block stays still until the applied force exceeds the maximum friction shown.',try:'Increase the mass without changing the applied force. Does it still move?',controls:[R('mass','Block mass',2,15,1,6,'kg'),R('force','Applied force',0,100,1,55,'N'),R('friction','Friction coefficient',0,.8,.05,.35,'',2)],metrics:p=>{let limit=p.friction*p.mass*9.8,actual=Math.min(p.force,limit),net=Math.max(0,p.force-limit);return[N('Friction force',`${actual.toFixed(1)} N`),N('Net force',`${net.toFixed(1)} N`),N('Acceleration',`${(net/p.mass).toFixed(2)} m/s²`)]},draw:'forces'},
    {id:'energy',grade:11,group:'MECHANICS',chapter:'Work, Energy and Power',title:'Conservation of energy',description:'Watch gravitational potential energy turn into kinetic energy on a frictionless track.',formula:'E = mgh + ½mv²',observe:'As the ball goes lower, potential energy falls and kinetic energy rises.',try:'Double the starting height. How does the maximum speed change?',controls:[R('height','Starting height',3,8,.5,6,'m',1),R('mass','Ball mass',1,10,1,3,'kg')],metrics:p=>[N('Total energy',`${(p.mass*9.8*p.height).toFixed(0)} J`),N('Peak speed',`${Math.sqrt(2*9.8*p.height).toFixed(1)} m/s`)],draw:'energy'},
    {id:'rotation',grade:11,group:'MECHANICS',chapter:'System of Particles and Rotational Motion',title:'Torque and rotation',description:'Apply a tangential force at different distances from a pivot and spin the disc.',formula:'τ = rF = Iα',observe:'The same force produces more torque when you apply it farther from the axis.',try:'Keep the force fixed and double the lever arm.',controls:[R('force','Tangential force',2,20,1,8,'N'),R('radius','Lever arm',.3,1.5,.1,.8,'m',1),R('inertia','Moment of inertia',1,8,.5,3,'kg·m²',1)],metrics:p=>[N('Torque',`${(p.force*p.radius).toFixed(1)} N·m`),N('Angular acceleration',`${(p.force*p.radius/p.inertia).toFixed(2)} rad/s²`)],draw:'rotation'},
    {id:'gravity',grade:11,group:'MECHANICS',chapter:'Gravitation',title:'Satellite orbit',description:'Move a satellite to another altitude and compare its speed and orbital period.',formula:'v = √(GM / r)',observe:'A higher circular orbit has a lower orbital speed and a longer period.',try:'Raise the altitude and watch the satellite slow down.',controls:[R('altitude','Orbit altitude',200,2000,50,500,'km')],metrics:p=>{let r=6371+p.altitude,v=Math.sqrt(3.986e5/r);return[N('Orbital speed',`${v.toFixed(2)} km/s`),N('Orbital period',`${(2*Math.PI*r/v/60).toFixed(1)} min`)]},draw:'gravity'},
    {id:'hooke',grade:11,group:'MATERIALS & HEAT',chapter:'Mechanical Properties of Solids',title:'Stretching a spring',description:'Pull the block and see how spring stiffness sets its extension.',formula:'F = kx',observe:'Doubling the applied force doubles extension while the spring stays in its elastic range.',try:'Keep the force fixed and choose a stiffer spring.',controls:[R('force','Pulling force',5,50,1,22,'N'),R('stiffness','Spring constant',100,500,10,220,'N/m')],metrics:p=>[N('Extension',`${(p.force/p.stiffness*100).toFixed(1)} cm`),N('Elastic energy',`${(.5*p.force*p.force/p.stiffness).toFixed(2)} J`)],draw:'hooke'},
    {id:'buoyancy',grade:11,group:'MATERIALS & HEAT',chapter:'Mechanical Properties of Fluids',title:'Float or sink?',description:'Change the densities and watch a block find its level in a fluid.',formula:'Fᵦ = ρfluid Vsub g',observe:'A floating block displaces fluid with the same weight as the block.',try:'Make the object denser than the fluid. What changes?',controls:[R('objectDensity','Object density',300,1500,50,600,'kg/m³'),R('fluidDensity','Fluid density',700,1300,50,1000,'kg/m³'),R('volume','Object volume',5,30,1,15,'L')],metrics:p=>{let fraction=Math.min(1,p.objectDensity/p.fluidDensity),V=p.volume/1000;return[N('Submerged',`${(fraction*100).toFixed(0)}%`),N('Buoyant force',`${(p.fluidDensity*V*fraction*9.8).toFixed(1)} N`),N('Object weight',`${(p.objectDensity*V*9.8).toFixed(1)} N`)]},draw:'buoyancy'},
    {id:'expansion',grade:11,group:'MATERIALS & HEAT',chapter:'Thermal Properties of Matter',title:'Thermal expansion',description:'Heat a metal rod and measure the small increase in its length.',formula:'ΔL = αL₀ΔT',observe:'The diagram magnifies the change in length so that it is easy to see.',try:'Double the original length. What happens to the expansion?',controls:[R('temperature','Final temperature',20,220,5,140,'°C'),R('length','Original length',.5,3,.1,1.5,'m',1),R('alpha','Expansion coefficient',8,30,1,18,'µ/K')],metrics:p=>[N('Temperature change',`${p.temperature-20} °C`),N('Length increase',`${(p.alpha*1e-6*p.length*(p.temperature-20)*1000).toFixed(2)} mm`)],draw:'expansion'},
    {id:'thermo',grade:11,group:'MATERIALS & HEAT',chapter:'Thermodynamics',title:'Gas under a piston',description:'Compress or heat an ideal gas and watch its pressure respond.',formula:'PV = nRT',observe:'At fixed temperature, a smaller volume means a larger pressure.',try:'Halve the volume while holding temperature and gas amount fixed.',controls:[R('volume','Gas volume',4,30,.5,15,'L',1),R('temperature','Temperature',200,600,10,300,'K'),R('moles','Amount of gas',.5,3,.1,1.5,'mol',1)],metrics:p=>[N('Pressure',`${(p.moles*8.314*p.temperature/p.volume).toFixed(0)} kPa`),N('PV',`${(p.moles*8.314*p.temperature).toFixed(0)} J`)],draw:'thermo'},
    {id:'kinetic',grade:11,group:'MATERIALS & HEAT',chapter:'Kinetic Theory',title:'Molecules in motion',description:'Heat a gas and watch its particles move faster inside a container.',formula:'vᵣₘₛ = √(3kT / m)',observe:'Temperature measures average translational kinetic energy, not the speed of a single molecule.',try:'Keep temperature constant and choose heavier molecules.',controls:[R('temperature','Gas temperature',100,900,10,300,'K'),R('molecularMass','Molecular mass',2,44,2,28,'u')],metrics:p=>{let vrms=Math.sqrt(3*1.380649e-23*p.temperature/(p.molecularMass*1.660539e-27));return[N('RMS speed',`${vrms.toFixed(0)} m/s`),N('Mean kinetic energy',`${(1.5*1.380649e-23*p.temperature/1.602176634e-19).toFixed(3)} eV`)]},draw:'kinetic'},
    {id:'pendulum',grade:11,group:'OSCILLATIONS & WAVES',chapter:'Oscillations',title:'Simple pendulum',description:'Set the length and release angle to watch a pendulum swing.',formula:'T ≈ 2π√(L / g)',observe:'For small angles, the period depends mostly on length, not on the bob’s mass.',try:'Double the length and see whether the period doubles.',controls:[R('length','String length',.5,2.5,.1,1.5,'m',1),R('amplitude','Release angle',5,35,1,22,'°')],metrics:p=>[N('Period (small angle)',`${(2*Math.PI*Math.sqrt(p.length/9.8)).toFixed(2)} s`),N('Frequency',`${(1/(2*Math.PI*Math.sqrt(p.length/9.8))).toFixed(2)} Hz`)],draw:'pendulum'},
    {id:'wave',grade:11,group:'OSCILLATIONS & WAVES',chapter:'Waves',title:'Travelling wave',description:'Change amplitude, wavelength and frequency to see a wave move through a medium.',formula:'v = fλ',observe:'The pattern travels while each marked point oscillates about its own equilibrium position.',try:'Double frequency while keeping wavelength fixed. How does speed change?',controls:[R('amplitude','Amplitude',.5,2.5,.1,1.3,'units',1),R('frequency','Frequency',.2,2,.1,.7,'Hz',1),R('wavelength','Wavelength',1,4,.1,2.5,'m',1)],metrics:p=>[N('Wave speed',`${(p.frequency*p.wavelength).toFixed(2)} m/s`),N('Period',`${(1/p.frequency).toFixed(2)} s`)],draw:'wave'},
    {id:'electrostatic',grade:12,group:'ELECTRICITY',chapter:'Electric Charges and Fields',title:'Electric field of two charges',description:'Change the charges and separation to explore how the field and force respond.',formula:'F = k|q₁q₂| / r²',observe:'Field arrows point away from positive charges and toward negative charges.',try:'Reverse one charge. Watch the field between them.',controls:[R('charge1','Charge 1',-5,5,1,3,'µC'),R('charge2','Charge 2',-5,5,1,-3,'µC'),R('separation','Separation',2,8,.5,5,'dm',1)],metrics:p=>[N('Force magnitude',`${(8.988e9*Math.abs(p.charge1*p.charge2)*1e-12/(p.separation/10)**2).toFixed(2)} N`),N('Interaction',p.charge1*p.charge2<0?'Attraction':p.charge1*p.charge2>0?'Repulsion':'No force')],draw:'electrostatic'},
    {id:'capacitor',grade:12,group:'ELECTRICITY',chapter:'Electrostatic Potential and Capacitance',title:'Parallel plate capacitor',description:'Bring plates closer or insert a dielectric to change stored charge.',formula:'C = κε₀A / d',observe:'Closer plates and a larger dielectric constant both increase capacitance.',try:'Double the plate spacing and compare the capacitance.',controls:[R('voltage','Potential difference',2,24,1,12,'V'),R('distance','Plate separation',1,5,.2,3,'mm',1),R('dielectric','Dielectric constant',1,6,.5,1,'',1)],metrics:p=>{let C=p.dielectric*8.854e-12*.02/(p.distance*.001);return[N('Capacitance',`${(C*1e12).toFixed(1)} pF`),N('Stored charge',`${(C*p.voltage*1e9).toFixed(2)} nC`),N('Stored energy',`${(.5*C*p.voltage**2*1e9).toFixed(2)} nJ`)]},draw:'capacitor'},
    {id:'circuit',grade:12,group:'ELECTRICITY',chapter:'Current Electricity',title:'Ohm’s law circuit',description:'Change battery voltage and resistance to control the current in a closed circuit.',formula:'V = IR',observe:'At fixed resistance, twice the voltage gives twice the current.',try:'Double the resistance and notice how the charge flow slows.',controls:[R('voltage','Battery voltage',1,24,1,12,'V'),R('resistance','Resistance',2,40,1,10,'Ω')],metrics:p=>[N('Current',`${(p.voltage/p.resistance).toFixed(2)} A`),N('Power',`${(p.voltage**2/p.resistance).toFixed(1)} W`)],draw:'circuit'},
    {id:'lorentz',grade:12,group:'MAGNETISM',chapter:'Moving Charges and Magnetism',title:'Charged particle in a field',description:'Watch a charged particle curve through a uniform magnetic field.',formula:'r = mv / |q|B',observe:'The magnetic force bends the path without changing the particle’s speed.',try:'Switch between electron and proton. Compare their physical orbit radii.',controls:[R('speed','Particle speed',1,8,.5,3,'×10⁶ m/s',1),R('field','Field strength',2,20,1,8,'mT'),{key:'particle',label:'Particle',options:[['electron','Electron'],['proton','Proton']],initial:'electron'},{key:'direction',label:'Field direction',options:[['into','Into the page'],['out','Out of the page']],initial:'into'}],metrics:p=>{let m=p.particle==='electron'?9.109e-31:1.673e-27,r=m*p.speed*1e6/(1.602e-19*p.field/1000);return[N('Orbit radius',r<.01?`${(r*1000).toFixed(2)} mm`:`${r.toFixed(2)} m`),N('Magnetic work','0 J') ]},draw:'lorentz'},
    {id:'magnet',grade:12,group:'MAGNETISM',chapter:'Magnetism and Matter',title:'Bar magnet and compass',description:'Explore the field around a bar magnet and the direction a compass points.',formula:'B ∝ magnetic moment / r³',observe:'Outside the magnet, magnetic field lines leave the north pole and enter the south pole.',try:'Increase magnetic strength. Watch the arrows around the magnet.',controls:[R('strength','Relative field strength',.5,3,.1,1.4,'×',1)],metrics:p=>[N('Field strength',`${p.strength.toFixed(1)}× reference`),N('Outside field','N → S')],draw:'magnet'},
    {id:'induction',grade:12,group:'MAGNETISM',chapter:'Electromagnetic Induction',title:'Magnet through a coil',description:'Move a magnet past a coil and watch the induced current reverse.',formula:'ε = −N dΦ/dt',observe:'The lamp responds to changing magnetic flux; a stationary magnet would not induce current.',try:'Move the magnet faster or add more turns to the coil.',controls:[R('speed','Magnet speed',.3,2.5,.1,1.1,'×',1),R('turns','Coil turns',3,8,1,5),R('strength','Magnet strength',.5,3,.1,1.5,'×',1)],metrics:(p,t)=>[N('Magnet motion',p.speed<.6?'Slow':p.speed>1.7?'Fast':'Moderate'),N('Coil turns',p.turns),N('Flux trend',Math.cos(t*p.speed*.9)>0?'Changing ↗':'Changing ↘')],draw:'induction'},
    {id:'ac',grade:12,group:'MAGNETISM',chapter:'Alternating Current',title:'AC generator',description:'Rotate a coil and track the alternating voltage it produces.',formula:'V(t) = V₀ sin(2πft)',observe:'Voltage changes sign every half cycle; the effective RMS voltage is smaller than the peak.',try:'Double the frequency. How does the period change?',controls:[R('voltage','Peak voltage',10,120,5,60,'V'),R('frequency','Frequency',.2,2,.1,.5,'Hz',1)],metrics:(p,t)=>[N('Instantaneous voltage',`${(p.voltage*Math.sin(2*Math.PI*p.frequency*t)).toFixed(1)} V`),N('RMS voltage',`${(p.voltage/Math.sqrt(2)).toFixed(1)} V`),N('Period',`${(1/p.frequency).toFixed(2)} s`)],draw:'ac'},
    {id:'emwave',grade:12,group:'MAGNETISM',chapter:'Electromagnetic Waves',title:'Electromagnetic wave',description:'See perpendicular electric and magnetic fields oscillate as a wave travels.',formula:'c = fλ',observe:'The electric and magnetic fields are in phase and move together through space.',try:'Shorten the wavelength. What happens to the frequency in vacuum?',controls:[R('wavelength','Wavelength',.5,4,.1,1.8,'m',1),R('amplitude','Relative amplitude',.5,2,.1,1.3,'×',1)],metrics:p=>[N('Frequency',`${(300/p.wavelength).toFixed(1)} MHz`),N('Speed in vacuum','3.00 × 10⁸ m/s')],draw:'emwave'},
    {id:'lens',grade:12,group:'OPTICS',chapter:'Ray Optics and Optical Instruments',title:'Image through a convex lens',description:'Move an object toward or away from a lens and trace the rays to its image.',formula:'1/f = 1/v + 1/u',observe:'An object inside the focal length makes a virtual, upright image.',try:'Move the object just inside the focal point.',controls:[R('objectDistance','Object distance',15,80,1,45,'cm'),R('focalLength','Focal length',10,30,1,20,'cm')],metrics:p=>{let v=p.objectDistance===p.focalLength?Infinity:p.focalLength*p.objectDistance/(p.objectDistance-p.focalLength);return[N('Image distance',Number.isFinite(v)?`${v.toFixed(1)} cm`:'At infinity'),N('Magnification',Number.isFinite(v)?`${(-v/p.objectDistance).toFixed(2)}×`:'Unbounded'),N('Image type',v>0?'Real, inverted':'Virtual, upright')]},draw:'lens'},
    {id:'doubleslit',grade:12,group:'OPTICS',chapter:'Wave Optics',title:'Double slit interference',description:'Pass light through two slits and watch bright and dark fringes form.',formula:'β = λD / d',observe:'Bright fringes occur where waves from the two slits arrive in phase.',try:'Increase the slit spacing. How does fringe spacing respond?',controls:[R('wavelength','Light wavelength',400,700,10,550,'nm'),R('slit','Slit separation',.2,1,.05,.5,'mm',2),R('distance','Screen distance',1,3,.1,2,'m',1)],metrics:p=>[N('Fringe spacing',`${(p.wavelength*1e-9*p.distance/(p.slit*1e-3)*1000).toFixed(2)} mm`),N('Central fringe','Bright')],draw:'doubleslit'},
    {id:'photoelectric',grade:12,group:'MODERN PHYSICS',chapter:'Dual Nature of Radiation and Matter',title:'Photoelectric effect',description:'Shine light on a metal and see whether it releases electrons.',formula:'Kₘₐₓ = hf − φ',observe:'Below the threshold frequency, brighter light still cannot eject electrons.',try:'Use a long wavelength with maximum intensity, then shorten the wavelength.',controls:[R('wavelength','Light wavelength',250,700,10,480,'nm'),R('workFunction','Work function',1.5,4.5,.1,2.2,'eV',1),R('intensity','Light intensity',10,100,10,60,'%')],metrics:p=>{let e=1240/p.wavelength,ke=Math.max(0,e-p.workFunction);return[N('Photon energy',`${e.toFixed(2)} eV`),N('Maximum K.E.',`${ke.toFixed(2)} eV`),N('Emission',e>=p.workFunction?'Yes':'No')]},draw:'photoelectric'},
    {id:'bohr',grade:12,group:'MODERN PHYSICS',chapter:'Atoms',title:'Bohr’s atomic model',description:'Choose an orbit and calculate the photon released in a transition to the ground state.',formula:'Eₙ = −13.6 Z² / n² eV',observe:'Higher levels are farther apart in radius but closer together in energy.',try:'Raise n and compare the n → 1 photon energy.',controls:[R('level','Excited energy level',2,5,1,3),R('atomicNumber','Atomic number (H-like)',1,3,1,1)],metrics:p=>[N('Orbit energy',`${(-13.6*p.atomicNumber**2/p.level**2).toFixed(2)} eV`),N('n → 1 photon',`${(13.6*p.atomicNumber**2*(1-1/p.level**2)).toFixed(2)} eV`)],draw:'bohr'},
    {id:'nuclear',grade:12,group:'MODERN PHYSICS',chapter:'Nuclei',title:'Radioactive decay',description:'See individual nuclei disappear while the population follows a half-life curve.',formula:'N(t) = N₀(½)^(t/T½)',observe:'After each half-life, approximately half of the undecayed population remains.',try:'Double the half-life. Compare the steepness of the decay curve.',controls:[R('initial','Initial nuclei',48,120,12,96),R('halfLife','Half-life',3,12,1,6,'s')],metrics:(p,t)=>{let q=t%Math.max(25,p.halfLife*5);return[N('Expected remaining',`${(p.initial*2**(-q/p.halfLife)).toFixed(0)}`),N('Elapsed time',`${q.toFixed(1)} s`),N('Half-life',`${p.halfLife} s`)]},draw:'nuclear'},
    {id:'diode',grade:12,group:'MODERN PHYSICS',chapter:'Semiconductor Electronics',title:'P–N junction diode',description:'Apply a voltage and watch the depletion region change with forward or reverse bias.',formula:'Forward bias → narrow junction',observe:'Forward bias reduces the barrier; reverse bias widens the depletion region.',try:'Move the voltage through zero and compare carrier movement.',controls:[R('voltage','Applied voltage',-2,2,.1,.8,'V',1)],metrics:p=>[N('Bias',p.voltage>0?'Forward':p.voltage<0?'Reverse':'None'),N('Depletion region',p.voltage>0?'Narrower':p.voltage<0?'Wider':'Equilibrium')],draw:'diode'}
  ];
  // Rarely used or duplicate experiments retired from the library (kept out of menus, links and search).
  const DROP=new Set(["speed-uncertainty", "free-fall-drop", "trains-meeting", "range-vs-angle", "basketball-shot", "projectile-3d", "rotor-ride", "incline-pulley", "spring-pe", "hill-climb-power", "flywheel-energy", "yo-yo", "gyroscope", "hohmann-transfer", "binary-stars", "weight-planets", "hydrometer", "pv-work", "engine-efficiency", "sound-speed-gas", "graham-effusion", "torsion-oscillator", "lissajous", "mach-cone", "sound-intensity", "potential-landscape", "power-vs-resistance", "mass-spectrometer", "tangent-galvanometer", "faraday-rate", "rc-filter", "em-field-intensity", "radiation-pressure", "coherent-superposition", "photon-counting", "uncertainty-principle", "franck-hertz", "moseley-xray", "decay-chain", "ce-amplifier"]);for(let i=sims.length;i--;)if(DROP.has(sims[i].id))sims.splice(i,1);
  const chapters=sims.slice();
  for(const s of sims)s.subject='physics';window.PhysicaSims=sims;
  // Physics packs extend an existing chapter (base); biology packs bring their own NCERT chapters.
  for(const extra of window.ExtraSimulations||[]){if(DROP.has(extra.id))continue;const base=extra.base&&chapters.find(s=>s.id===extra.base);if(base){sims.push({...base,...extra,draw:extra.id});continue}
    const s={...extra,subject:extra.subject==='chemistry'?'chemistry':bioSubject(extra),draw:extra.id};sims.push(s);if(!chapters.some(c=>sameChapter(c,s)))chapters.push(s)}
  chapters.sort((a,b)=>a.subject===b.subject?(a.chapterNo||0)-(b.chapterNo||0):0);
  // Original 2D experiments that have a true-3D scene (phys3d-*.js) switch to it; the 2D diagram stays available.
  // Interactive instruments (hands-on drag) can replace a simulation's controls, readouts and drawing.
  for(const s of sims){const P=window.PhysicaSimPatch?.[s.id];if(P)Object.assign(s,P)}const INT=id=>window.PhysicaInteractive?.[id];
  const R3=window.Physica3DRenderers||{};for(const s of sims)if(R3[s.id]&&!s.view3d)s.r3=R3[s.id];
  // Detailed, realistic 3D apparatus (real3d-*.js) replace the earlier scenes wherever they exist.
  // Detailed 3D scenes arrive in a second, lazily loaded bundle; apply them now and again whenever more arrive.
  const applyReal3D=()=>{const RR=window.PhysicaReal3D||{};for(const s of sims)if(RR[s.id]&&s.r3!==RR[s.id]&&!window.PhysicaSimPatch?.[s.id]){s.r3=RR[s.id];s.view3d=false}};applyReal3D();
  // Every experiment has three views: 2D (clean flat diagram / hands-on), 3D (orbit camera) and Ultra-Realistic (photographic bench + camera finish).
  // Hands-on instruments keep their own parameters; map them onto the matching 3D scene.
  const ADAPT={units:p=>({...p,measure:p.jaw/10}),'screw-gauge':p=>{const r=p.gap/p.pitch,n=Math.floor(r);return{...p,turns:n,division:Math.round((r-n)*50)}}};
  for(const s of sims)if(window.PhysicaSimPatch?.[s.id]&&s.r3){const f=s.r3,ad=ADAPT[s.id];s.r3=ad?(c,p,t)=>f(c,ad(p),t):null}
  window.PhysicaApplyReal3D=()=>{applyReal3D();const RR=window.PhysicaReal3D||{};for(const s of sims)if(window.PhysicaSimPatch?.[s.id]&&RR[s.id]&&s.__rr!==RR[s.id]){const f=RR[s.id],ad=ADAPT[s.id];s.__rr=f;s.r3=ad?(c,p,t)=>f(c,ad(p),t):f}try{syncView3d();renderSimulationTabs();draw()}catch{}};
  let mode='3d';try{mode=localStorage.getItem('physica-mode')||(localStorage.getItem('physica-classic-2d')==='1'?'2d':'3d')}catch{}if(!['2d','3d','ultra'].includes(mode))mode='3d';
  const HAND=()=>(mode!=='3d'||!current.r3)&&INT(current.id);
  const is3D=s=>mode!=='2d'&&!(mode==='ultra'&&(INT(s.id)||window.PhysicaUltraScenes?.[s.id]))&&!!(s.view3d||s.r3);
  // NCERT biology is taught as Botany and Zoology (standard NEET / board split by chapter).
  function bioSubject(e){const Z={11:[4,7,9,14,15,16,17,18,19],12:[2,3,6,7,9,10]};return (Z[e.grade]||[]).includes(e.chapterNo)?'zoology':'botany'}
  function sameChapter(a,b){return a.chapter===b.chapter&&a.grade===b.grade&&a.subject===b.subject}
  const $=id=>document.getElementById(id),canvas=$('simulation'),ctx=canvas.getContext('2d');
  const saved=new Map(),defaultFor=sim=>Object.fromEntries(sim.controls.map(c=>[c.key,c.initial]));
  for(const s of sims)saved.set(s.id,defaultFor(s));
  // Links look like #simulation-id?key=value&key2=value2 so a setup can be shared exactly.
  function parseHash(){let raw=location.hash.slice(1);try{raw=decodeURIComponent(raw)}catch{}const [id,query='']=raw.split('?');return{id,params:new URLSearchParams(query)}}
  function applyParams(sim,params){const p=saved.get(sim.id);for(const c of sim.controls){if(!params.has(c.key))continue;const v=params.get(c.key);if(c.options){const o=c.options.find(([val])=>String(val)===v);if(o)p[c.key]=o[0]}else{const n=Number(v);if(Number.isFinite(n)){const k=Math.round((Math.min(c.max,Math.max(c.min,n))-c.min)/c.step);p[c.key]=Number(Math.min(c.max,c.min+k*c.step).toFixed(8))}}}}
  const firstLink=parseHash();
  let current=sims.find(s=>s.id===firstLink.id)||sims.find(s=>s.id==='projectile');
  let subject=current.subject;const inScope=s=>s.grade===grade&&s.subject===subject;
  if(current.id===firstLink.id)applyParams(current,firstLink.params);
  let playbackSpeed=1;
  const FAV_KEY='physica-favourites';
  let favourites=new Set();
  try{const value=JSON.parse(localStorage.getItem(FAV_KEY)||'[]');if(Array.isArray(value))favourites=new Set(value.filter(id=>sims.some(s=>s.id===id)));}catch{}
  function renderFavourites(){
    const host=$('favourites-list');host.replaceChildren();
    $('favourites-count').textContent=favourites.size;
    const starred=favourites.has(current.id),toggle=$('favourite-toggle');
    toggle.textContent=starred?'★ Starred':'☆ Favourite';toggle.setAttribute('aria-pressed',String(starred));
    toggle.setAttribute('aria-label',(starred?'Unstar ':'Star ')+current.title);
    if(!favourites.size){const p=document.createElement('p');p.className='favourites-empty';p.dataset.testid='favourites-empty';p.textContent='Star a simulation to keep it here. Both classes, one shortlist.';host.append(p);}
    for(const id of favourites){const sim=sims.find(s=>s.id===id),row=document.createElement('div');row.className='favourite-row';
      const open=document.createElement('button');open.type='button';open.textContent=sim.title;open.title=`Class ${sim.grade} · ${sim.chapter}`;open.dataset.testid='favourite-open-'+id;open.className=sim===current?'active':'';open.onclick=()=>{select(sim);closeSidebar();};
      const remove=document.createElement('button');remove.type='button';remove.textContent='★';remove.className='favourite-remove';remove.setAttribute('aria-label','Unstar '+sim.title);remove.dataset.testid='favourite-remove-'+id;remove.onclick=()=>toggleFavourite(id);row.append(open,remove);host.append(row);
    }
  }
  function toggleFavourite(id){favourites.has(id)?favourites.delete(id):favourites.add(id);try{localStorage.setItem(FAV_KEY,JSON.stringify([...favourites]));$('favourites-status').textContent='';}catch{$('favourites-status').textContent='Browser storage is full or unavailable. Stars will last for this visit only.';}renderFavourites();}
  $('favourite-toggle').onclick=()=>toggleFavourite(current.id);
  $('simulation-speed').onchange=e=>{playbackSpeed=Number(e.target.value);};
  $('simulation-step').onclick=()=>{playing=false;elapsed+=1/30;syncPlay();updateReadouts();draw();};
  let grade=current.grade,elapsed=0,playing=!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches,lastFrame=performance.now(),lastReadout=0;
  const fmt=c=>c.show?c.show(saved.get(current.id)[c.key]):`${typeof saved.get(current.id)[c.key]==='number'?saved.get(current.id)[c.key].toFixed(c.digits||0):saved.get(current.id)[c.key]}${c.unit?' '+c.unit:''}`;
  function renderSidebar(){
    const search=$('search').value.trim().toLowerCase();
    const entries=chapters.filter(s=>inScope(s)&&(!search||sims.some(x=>sameChapter(x,s)&&`${x.chapter} ${x.title} ${x.description}`.toLowerCase().includes(search))));
    const nav=$('chapter-list');nav.replaceChildren();let group='';
    if(!entries.length){const empty=document.createElement('p');empty.className='empty-search';empty.textContent='No chapters match. Try a different word.';nav.append(empty);return}
    for(const s of entries){
      if(s.group!==group){group=s.group;const heading=document.createElement('div');heading.className='chapter-group';heading.textContent=group;nav.append(heading)}
      const button=document.createElement('button');button.type='button';button.dataset.testid='chapter-'+s.id;button.className='chapter-link'+(sameChapter(s,current)?' active':'');button.setAttribute('aria-current',sameChapter(s,current)?'page':'false');
      const num=document.createElement('span');num.className='chapter-num';num.textContent=String(chapters.filter(inScope).indexOf(s)+1).padStart(2,'0');
      const label=document.createElement('span');label.textContent=s.chapter;
      const arrow=document.createElement('span');arrow.className='chapter-arrow';arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');
      button.append(num,label,arrow);button.addEventListener('click',()=>{select(s);closeSidebar()});nav.append(button)
    }
  }
  function renderSimulationTabs(){const holder=$('simulation-tabs');holder.replaceChildren();for(const sim of sims.filter(s=>sameChapter(s,current))){const button=document.createElement('button');button.type='button';button.dataset.testid='sim-tab-'+sim.id;button.textContent=sim.title;button.className=(sim===current?'selected':'')+(is3D(sim)?' is-3d':'');if(is3D(sim))button.title='Interactive 3D scene';button.setAttribute('aria-pressed',String(sim===current));button.addEventListener('click',()=>select(sim));holder.append(button)}$('library-count').textContent=`${sims.filter(s=>s.subject===subject).length} SIMULATIONS`;const inChapter=sims.filter(s=>sameChapter(s,current)),pos=inChapter.indexOf(current)+1;$('tab-count').textContent=`Simulation ${pos} of ${inChapter.length} in this chapter`;const sel=holder.querySelector('.selected');if(sel)holder.scrollLeft=Math.max(0,sel.offsetLeft-holder.clientWidth/2+sel.offsetWidth/2);}
  function renderLesson(){const holder=$('lesson-section'),lesson=window.SimulationLessons?.[current.id];holder.hidden=!lesson;holder.replaceChildren();if(!lesson)return;const top=document.createElement('div');top.className='lesson-top';const heading=document.createElement('h2');heading.textContent='Try a comparison';const presets=document.createElement('div');presets.className='preset-buttons';for(const preset of lesson.presets){const button=document.createElement('button');button.type='button';button.textContent=preset.label;button.addEventListener('click',()=>{Object.assign(saved.get(current.id),preset.values);elapsed=0;renderControls();updateReadouts(true);draw()});presets.append(button)}top.append(heading,presets);const grid=document.createElement('div');grid.className='lesson-grid';const worked=document.createElement('div');const wl=document.createElement('h3');wl.textContent='With your values';const equation=document.createElement('p');equation.id='worked-equation';worked.append(wl,equation);const assumptions=document.createElement('div');const al=document.createElement('h3');al.textContent='About this model';const ap=document.createElement('p');ap.textContent=lesson.assumption;assumptions.append(al,ap);if(current.reference){const link=document.createElement('a');link.className='model-reference';link.href=current.reference.url;link.textContent=current.reference.label;link.target='_blank';link.rel='noopener noreferrer';assumptions.append(link)}grid.append(worked,assumptions);holder.append(top,grid);}
  function renderControls(){
    const host=$('controls');host.replaceChildren();const p=saved.get(current.id);
    for(const c of current.controls){
      const row=document.createElement('div');row.className='control-row';
      const label=document.createElement('label');label.className='control-label';label.htmlFor=`control-${c.key}`;
      const name=document.createElement('span');name.textContent=c.label;
      const display=document.createElement('span');display.className='control-value';display.dataset.testid='control-value-'+c.key;display.textContent=typeof p[c.key]==='number'?fmt(c):'';label.append(name,display);row.append(label);
      if(c.options){const select=document.createElement('select');select.id=`control-${c.key}`;select.dataset.testid='control-'+c.key;for(const [value,title] of c.options){const option=document.createElement('option');option.value=value;option.textContent=title;select.append(option);}select.value=p[c.key];select.onchange=()=>{p[c.key]=c.options.find(([v])=>String(v)===select.value)[0];display.textContent=typeof p[c.key]==='number'?fmt(c):'';updateReadouts();draw();};row.append(select);}
      else{
        const input=document.createElement('input'),number=document.createElement('input');
        for(const [el,type] of [[input,'range'],[number,'number']]){el.type=type;el.min=c.min;el.max=c.max;el.step=c.step;el.value=p[c.key];el.id=`${type==='range'?'control':'exact'}-${c.key}`;el.dataset.testid=el.id;el.setAttribute('aria-label',c.label+(type==='number'?' exact value':''));}
        number.className='exact-value';
        const sync=()=>{input.value=p[c.key];number.value=p[c.key];display.textContent=fmt(c);input.setAttribute('aria-valuetext',fmt(c));input.style.setProperty('--fill',`${(p[c.key]-c.min)/(c.max-c.min)*100}%`);updateReadouts();draw();};
        input.oninput=()=>{p[c.key]=Number(input.value);sync();};
        number.onchange=()=>{if(number.value!==''&&Number.isFinite(number.valueAsNumber)){const v=Math.max(c.min,Math.min(c.max,number.valueAsNumber));p[c.key]=Number(Math.min(c.max,c.min+Math.round((v-c.min)/c.step)*c.step).toFixed(8));}sync();};
        const ends=document.createElement('div');ends.className='control-extents';ends.textContent=c.show?`${c.show(c.min)} — ${c.show(c.max)}`:`${c.min} — ${c.max}${c.unit?' '+c.unit:''}`;
        // − / + steppers: one step per tap, repeating while held.
        const nudge=d=>{const v=Math.min(c.max,Math.max(c.min,p[c.key]+d*c.step));p[c.key]=Number(Math.min(c.max,c.min+Math.round((v-c.min)/c.step)*c.step).toFixed(8));sync()};
        const stepper=(label,d)=>{const b=document.createElement('button');b.type='button';b.className='step-btn';b.textContent=d<0?'−':'+';b.setAttribute('aria-label',`${label} ${c.label}`);b.dataset.testid=`${d<0?'dec':'inc'}-${c.key}`;let timer=0;const stop=()=>{clearTimeout(timer);clearInterval(timer);timer=0};
          b.addEventListener('pointerdown',e=>{e.preventDefault();nudge(d);timer=setTimeout(()=>{timer=setInterval(()=>nudge(d),70)},380)});['pointerup','pointerleave','pointercancel'].forEach(ev=>b.addEventListener(ev,stop));b.addEventListener('click',e=>{if(e.detail===0)nudge(d)});return b};
        const slider=document.createElement('div');slider.className='range-wrap';slider.append(stepper('Decrease',-1),input,stepper('Increase',1));row.append(slider,ends,number);
        input.setAttribute('aria-valuetext',fmt(c));input.style.setProperty('--fill',`${(p[c.key]-c.min)/(c.max-c.min)*100}%`);
      }
      host.append(row);
    }
  }
  function updateReadouts(rebuild=false){const data=current.metrics(saved.get(current.id),elapsed);const holder=$('readouts');if(rebuild||holder.children.length!==data.length){holder.replaceChildren();for(const m of data){const box=document.createElement('div');box.className='readout';const key=document.createElement('span');key.className='readout-label';key.textContent=m.label;const val=document.createElement('strong');val.className='readout-value';val.dataset.testid='readout-'+holder.children.length;val.textContent=m.value;box.append(key,val);holder.append(box)}}else data.forEach((m,i)=>{holder.children[i].querySelector('.readout-value').textContent=m.value});$('elapsed').textContent=`${elapsed.toFixed(1)} s`;const equation=$('worked-equation');if(equation&&window.SimulationLessons?.[current.id])equation.textContent=window.SimulationLessons[current.id].worked(saved.get(current.id),elapsed);window.PhysicaExperience?.update()}
  function render(){grade=current.grade;subject=current.subject;const gradeSims=chapters.filter(inScope),ix=gradeSims.findIndex(s=>sameChapter(s,current));document.querySelectorAll('.subject-tab').forEach(b=>{const on=b.dataset.subject===subject;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on))});document.documentElement.dataset.subject=subject;document.title=`${current.title} | Physica`;document.querySelectorAll('.grade-tab').forEach(b=>{let active=Number(b.dataset.grade)===grade;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
    $('grade-crumb').textContent=`${subject.toUpperCase()} · CLASS ${grade}`;$('chapter-crumb').textContent=current.chapter.toUpperCase();$('position').textContent=`${String(ix+1).padStart(2,'0')} / ${gradeSims.length}`;$('sim-number').textContent=`№ ${String(ix+1).padStart(2,'0')}`;$('title').textContent=current.title;$('description').textContent=current.description;$('formula').textContent=current.formula;$('observation').textContent=current.observe;$('try-this').textContent=current.try;canvas.setAttribute('aria-label',`${current.title} animated physics simulation`);$('prev').disabled=ix===0;$('next').disabled=ix===gradeSims.length-1;
    $('search').value='';syncView3d();renderFavourites();renderSidebar();renderControls();renderSimulationTabs();renderLesson();updateReadouts(true);syncPlay();draw();
  }
  function select(s,scroll=true){if(!s)return;window.PhysicaExperience?.onSelect();current=s;elapsed=0;history.replaceState(null,'',`#${s.id}`);render();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
  function syncPlay(){$('play-icon').textContent=playing?'Ⅱ':'▶';$('play-label').textContent=playing?'Pause':'Play';$('play').setAttribute('aria-label',playing?'Pause simulation':'Play simulation');$('live-status').textContent=playing?'LIVE SIMULATION':'SIMULATION PAUSED';document.querySelector('.stage').classList.toggle('paused',!playing);window.PhysicaExperience?.update()}
  // Big classroom boards (4K panels with phone-class chips) and Teacher mode run "lite": no live blur, and frames are
  // paced at 30 per second so motion stays even. Resolution adapts to how long drawing really takes (not to the
  // screen's refresh rate), between the screen's own pixels and full sharpness (devicePixelRatio, max 2).
  const BIG=Math.max(screen.width||0,screen.height||0)*(devicePixelRatio||1)>=3000;
  const lite=()=>BIG||document.body.classList.contains('mode-teacher');let lastDraw=0;
  let renderScale=1,cost=6,lastAdapt=0;window.PhysicaPerf={get cost(){return+cost.toFixed(1)},get scale(){return+renderScale.toFixed(2)}};function adapt(ms,now){if(window.PhysicaRecordWidth)return;cost+=(ms-cost)*.08;window.PhysicaLite=lite();document.documentElement.classList.toggle('lite',window.PhysicaLite);if(now-lastAdapt<900)return;
    const budget=lite()?22:14;if(cost>budget&&renderScale>.5){renderScale=Math.max(.5,renderScale*.85);lastAdapt=now;resize()}else if(cost<budget*.45&&renderScale<1){renderScale=Math.min(1,renderScale*1.1);lastAdapt=now+2000;resize()}}
  function resize(){const box=canvas.getBoundingClientRect(),dpr=Math.max(1,Math.min(devicePixelRatio||1,2)*renderScale),RW=window.PhysicaRecordWidth;if(RW){canvas.width=RW;canvas.height=Math.round(RW*505/960/2)*2;ctx.setTransform(canvas.width/960,0,0,canvas.height/505,0,0);draw();return}if(box.width<1)return;window.PhysicaTextScale=Math.max(1,Math.min(1.55,820/box.width));canvas.width=Math.round(box.width*dpr);canvas.height=Math.round(box.height*dpr);ctx.setTransform(canvas.width/960,0,0,canvas.height/505,0,0);draw()}
  function draw(){if(!ctx)return;ctx.clearRect(0,0,960,505);window.PhysicaSceneBoost=current.subject==='physics'?1.08:1.2;if(window.__chartSim!==current.id){window.PhysicaChartRects=[];window.__chartSim=current.id}else window.PhysicaChartRects=window.__chartRects||[];window.__chartRects=[];try{const g=window.PhysicaTheme.wrapContext(ctx);const P3=window.Physica3D;if(P3){P3.flat=mode==='2d';P3.ultra=mode==='ultra'&&!window.PhysicaUltraScenes?.[current.id]}const US=mode==='ultra'&&window.PhysicaUltraScenes?.[current.id];if(US)window.PhysicaRenderExperiment(g,current,saved.get(current.id),elapsed,US);else if(HAND())window.PhysicaRenderExperiment(g,current,saved.get(current.id),elapsed,INT(current.id).draw);else if(current.r3&&mode!=='2d')window.PhysicaRenderExperiment(g,current,saved.get(current.id),elapsed,current.r3);else window.PhysicsDraw.draw(g,current.draw,saved.get(current.id),elapsed)}catch(err){console.error('Simulation drawing error',current.id,err);ctx.fillStyle='#0b2030';ctx.fillRect(0,0,960,505);ctx.fillStyle='#eff8ff';ctx.font='22px system-ui';ctx.fillText('This simulation could not be drawn. Try another chapter.',65,235)}if(mode==='ultra'&&!window.PhysicaUltraScenes?.[current.id])try{window.Physica3D?.finish(ctx)}catch{}}
  window.addEventListener('physica-theme-change',draw);
  function frame(now){if(lite()&&now-lastDraw<31){requestAnimationFrame(frame);return}lastDraw=now;let dt=Math.min((now-lastFrame)/1000,.06);lastFrame=now;if(playing)elapsed=(elapsed+dt*playbackSpeed)%3600;if(is3D(current))window.Physica3D?.tick(dt);const t0=performance.now();draw();adapt(performance.now()-t0,now);window.PhysicaExperience?.draw();if(now-lastReadout>110){updateReadouts();lastReadout=now}requestAnimationFrame(frame)}
  function closeSidebar(){$('sidebar').classList.remove('open');$('mobile-topics').setAttribute('aria-expanded','false')}
  $('mobile-topics').addEventListener('click',()=>{let open=$('sidebar').classList.toggle('open');$('mobile-topics').setAttribute('aria-expanded',String(open));if(open)$('search').focus()});
  $('search').addEventListener('input',renderSidebar);
  document.querySelectorAll('.grade-tab').forEach(b=>b.addEventListener('click',()=>{const g=Number(b.dataset.grade);if(g!==grade)select(sims.find(s=>s.grade===g&&s.subject===subject));else renderSidebar()}));
  document.querySelectorAll('.subject-tab').forEach(b=>b.addEventListener('click',()=>{const sub=b.dataset.subject;if(sub!==subject)select(sims.find(s=>s.subject===sub&&s.grade===grade)||sims.find(s=>s.subject===sub));else renderSidebar()}));
  $('prev').addEventListener('click',()=>{let l=chapters.filter(inScope);select(l[l.findIndex(s=>sameChapter(s,current))-1])});$('next').addEventListener('click',()=>{let l=chapters.filter(inScope);select(l[l.findIndex(s=>sameChapter(s,current))+1])});
  $('play').addEventListener('click',()=>{playing=!playing;syncPlay()});$('restart').addEventListener('click',()=>{elapsed=0;updateReadouts();draw()});$('defaults').addEventListener('click',()=>{saved.set(current.id,defaultFor(current));elapsed=0;renderControls();updateReadouts(true);draw()});
  document.addEventListener('keydown',e=>{if($('help-dialog').open)return;shortcut(e);if(e.key==='Escape'){closeSidebar();document.activeElement?.blur()}if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();if(innerWidth<=760){$('sidebar').classList.add('open');$('mobile-topics').setAttribute('aria-expanded','true')}$('search').focus()}if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement?.tagName)){e.preventDefault();playing=!playing;syncPlay()}});
  window.addEventListener('hashchange',()=>{const link=parseHash(),target=sims.find(s=>s.id===link.id);if(!target)return;applyParams(target,link.params);if(target!==current)select(target);else{renderControls();updateReadouts(true);draw()}});
  // ---- Extra controls: 3D view bar, randomise, share, snapshot, full screen, help, shortcuts ----
  let dragMode='rotate',toastTimer=0;
  function toast(msg){const el=$('toast');el.textContent=msg;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true},2600)}
  function syncView3d(){const is3d=is3D(current),P3=window.Physica3D;$('view3d-bar').hidden=false;for(const m of['2d','3d','ultra'])$('mode-'+m).setAttribute('aria-pressed',String(mode===m));for(const id of['drag-mode','auto-spin','zoom-in','zoom-out','view-reset'])$(id).hidden=!is3d;$('drag-mode').textContent=dragMode==='rotate'?'⟲ Drag: rotate view':'⇆ Drag: adjust values';$('drag-mode').setAttribute('aria-pressed',String(dragMode==='rotate'));
    $('auto-spin').setAttribute('aria-pressed',String(!!P3?.cam.auto));$('stage-hint').textContent=is3d?(dragMode==='rotate'?'3D · DRAG TO ROTATE · PINCH TO ZOOM':'3D · DRAG TO ADJUST VALUES'):'DRAG THE SLIDERS · OR DRAG ON THE STAGE';
    const on=P3?P3.enabled:true;$('realism-toggle').textContent=`◆ 3D look: ${on?'On':'Off'}`;$('realism-toggle').setAttribute('aria-pressed',String(on))}
  for(const m of['2d','3d','ultra'])$('mode-'+m).onclick=()=>{mode=m;try{localStorage.setItem('physica-mode',m)}catch{}syncView3d();renderSimulationTabs();renderControls();updateReadouts();draw();toast(m==='2d'?'2D view':m==='3d'?'3D · drag to rotate':'Ultra-Realistic')};
  $('drag-mode').onclick=()=>{dragMode=dragMode==='rotate'?'values':'rotate';syncView3d()};
  $('auto-spin').onclick=()=>{window.Physica3D?.setAuto(!window.Physica3D.cam.auto);syncView3d()};
  $('zoom-in').onclick=()=>window.Physica3D?.zoomBy(1.15);$('zoom-out').onclick=()=>window.Physica3D?.zoomBy(1/1.15);
  $('view-reset').onclick=()=>{window.Physica3D?.resetView();window.Physica3D?.setAuto(false);syncView3d()};
  $('realism-toggle').onclick=()=>{const P3=window.Physica3D;if(!P3)return;P3.setEnabled(!P3.enabled);syncView3d();draw();toast(P3.enabled?'Realistic 3D lighting on':'Flat classic look')};
  function randomise(){const p=saved.get(current.id);for(const c of current.controls){if(c.options)p[c.key]=c.options[Math.floor(Math.random()*c.options.length)][0];else{const n=Math.round((c.max-c.min)/c.step);p[c.key]=Number(Math.min(c.max,c.min+Math.floor(Math.random()*(n+1))*c.step).toFixed(8))}}elapsed=0;renderControls();updateReadouts(true);draw();toast('Random values — what do you predict will happen?')}
  $('randomise-btn').onclick=randomise;
  function shareURL(){const p=saved.get(current.id),q=new URLSearchParams();for(const c of current.controls)q.set(c.key,String(p[c.key]));return`${location.origin}${location.pathname}#${current.id}?${q}`}
  $('share-link').onclick=async()=>{const url=shareURL();history.replaceState(null,'',url.slice(url.indexOf('#')));try{await navigator.clipboard.writeText(url);toast('Link copied — it opens this experiment with your values')}catch{toast('Link is in the address bar — copy it from there')}};
  $('snapshot-btn').onclick=()=>{canvas.toBlob(blob=>{if(!blob){toast('Snapshot is not available in this browser');return}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`physica-${current.id}.png`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),4000);toast('Snapshot saved')},'image/png')};
  function toggleFullscreen(){const stage=document.querySelector('.stage');if(document.fullscreenElement){document.exitFullscreen?.();return}if(stage.classList.contains('pseudo-full')){stage.classList.remove('pseudo-full');document.body.classList.remove('no-scroll');resize();return}
    if(stage.requestFullscreen)stage.requestFullscreen().catch(()=>{stage.classList.add('pseudo-full');document.body.classList.add('no-scroll');resize()});else{stage.classList.add('pseudo-full');document.body.classList.add('no-scroll');resize()}}
  $('tab-prev').onclick=()=>stepSimulation(-1);$('tab-next').onclick=()=>stepSimulation(1);
  $('fullscreen-btn').onclick=toggleFullscreen;document.addEventListener('fullscreenchange',()=>setTimeout(resize,50));
  $('help-open').onclick=()=>$('help-dialog').showModal();$('help-close').onclick=()=>$('help-dialog').close();$('help-dialog').addEventListener('click',e=>{if(e.target===$('help-dialog'))$('help-dialog').close()});
  function stepSimulation(d){const order=chapters.filter(inScope).flatMap(ch=>sims.filter(s=>sameChapter(s,ch))),i=order.indexOf(current),next=order[i+d];if(next)select(next,false)}
  function setSpeed(d){const sel=$('simulation-speed'),opts=[...sel.options].map(o=>o.value),i=Math.max(0,Math.min(opts.length-1,opts.indexOf(sel.value)+d));sel.value=opts[i];playbackSpeed=Number(opts[i]);toast(`Playback ${opts[i]}×`)}
  function shortcut(e){const tag=document.activeElement?.tagName;if(e.ctrlKey||e.metaKey||e.altKey||['INPUT','SELECT','TEXTAREA'].includes(tag))return;const k=e.key;
    if(k==='r'||k==='R'){elapsed=0;updateReadouts();draw()}else if(k==='f'||k==='F')toggleFullscreen();else if(k==='x'||k==='X')randomise();else if(k==='3')$('realism-toggle').click();else if(k==='?'){e.preventDefault();$('help-dialog').showModal()}
    else if(k==='ArrowRight'||k==='ArrowLeft'){if(tag==='BUTTON'&&document.activeElement.closest('.simulation-tabs'))return;e.preventDefault();stepSimulation(k==='ArrowRight'?1:-1)}else if(k===']')setSpeed(1);else if(k==='[')setSpeed(-1);
    else if(is3D(current)&&(k==='+'||k==='='))window.Physica3D?.zoomBy(1.15);else if(is3D(current)&&(k==='-'||k==='_'))window.Physica3D?.zoomBy(1/1.15);else if(is3D(current)&&k==='0')window.Physica3D?.resetView()}
  
  // Optional browser agent controls share the exact same state and rendering path as the UI.
  if(document.modelContext?.registerTool){
    const lifecycle=new AbortController();
    const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(console.warn)}catch(err){console.warn(err)}};
    const ids=sims.map(s=>s.id);
    register({name:'open_physics_simulation',title:'Open physics simulation',description:'Open a Class 11 or 12 chapter simulation by its ID.',inputSchema:{type:'object',properties:{simulationId:{type:'string',enum:ids}},required:['simulationId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const target=sims.find(s=>s.id===input?.simulationId);if(!target)throw Error('Unknown simulation ID');select(target);return{simulationId:current.id,title:current.title,parameters:saved.get(current.id)}}});
    register({name:'configure_physics_simulation',title:'Configure physics simulation',description:'Change one or more parameters and update the visible animation and calculated values.',inputSchema:{type:'object',properties:{simulationId:{type:'string',enum:ids},values:{type:'object',minProperties:1,additionalProperties:{anyOf:[{type:'number'},{type:'string'}]}}},required:['simulationId','values'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const target=sims.find(s=>s.id===input?.simulationId);if(!target||!input.values||Array.isArray(input.values)||typeof input.values!=='object')throw Error('Provide a simulation and its parameters');const changes=Object.entries(input.values);if(!changes.length)throw Error('At least one parameter is required');for(const [key,value] of changes){const c=target.controls.find(control=>control.key===key);if(!c)throw Error(`Unknown parameter: ${key}`);if(c.options){if(!c.options.some(([v])=>v===value))throw Error(`Invalid value for ${key}`)}else if(typeof value!=='number'||!Number.isFinite(value)||value<c.min||value>c.max||Math.abs((value-c.min)/c.step-Math.round((value-c.min)/c.step))>1e-4)throw Error(`Out of range or off step: ${key}`)}const p=saved.get(target.id);for(const [key,value] of changes)p[key]=value;if(target!==current)select(target);else{renderControls();updateReadouts();draw()}return{simulationId:target.id,parameters:p,results:target.metrics(p,elapsed)}}});
    addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
  if(ctx){render();new ResizeObserver(resize).observe(canvas);resize();window.PhysicaResize=resize;window.PhysicaExperience?.init({state:()=>({current,params:saved.get(current.id),time:elapsed,playing}),open(id,values){const target=sims.find(s=>s.id===id);if(!target)return;saved.set(id,{...defaultFor(target),...values});select(target,false)}});
    // Direct manipulation: drag anywhere on the stage to steer the first two sliders with touch or mouse.
    let steering=false;
    function stageDrag(e){const rng=current.controls.filter(c=>!c.options);if(!rng.length)return;const box=canvas.getBoundingClientRect();if(box.width<1)return;const px=(e.clientX-box.left)/box.width,py=(e.clientY-box.top)/box.height,p=saved.get(current.id);const setC=(c,frac)=>{let v=c.min+(c.max-c.min)*Math.min(1,Math.max(0,frac));v=Math.round((v-c.min)/c.step)*c.step+c.min;p[c.key]=Number(Math.min(c.max,Math.max(c.min,v)).toFixed(8))};setC(rng[0],px);if(rng[1])setC(rng[1],1-py);renderControls();updateReadouts();draw()}
    // In 3D experiments dragging orbits the camera (two fingers pinch-zoom) unless the user chooses value steering.
    const pointers=new Map();let pinch=0;
    const orbiting=()=>is3D(current)&&dragMode==='rotate'&&window.Physica3D;
    const spread=()=>{const [a,b]=[...pointers.values()];return Math.hypot(a.x-b.x,a.y-b.y)};
    canvas.style.cursor='grab';
    const logical=e=>{const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*960,y=(e.clientY-b.top)/b.height*505,V=window.PhysicaClean&&window.PhysicaView;return V?{x:(x-V.ox)/V.s,y:(y-V.oy)/V.s}:{x,y}},handOn=(fn,e)=>{const I=HAND();if(!I)return false;I[fn]?.(logical(e),saved.get(current.id));renderControls();updateReadouts();draw();return true};
  canvas.addEventListener('pointerdown',e=>{if(HAND()){steering=true;try{canvas.setPointerCapture(e.pointerId)}catch{}handOn('down',e);return}steering=true;canvas.style.cursor='grabbing';pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});try{canvas.setPointerCapture(e.pointerId)}catch{}if(orbiting()){if(pointers.size===2)pinch=spread()}else stageDrag(e)});
    canvas.addEventListener('pointermove',e=>{if(!steering)return;if(handOn('move',e))return;if(!orbiting()){stageDrag(e);return}const last=pointers.get(e.pointerId);if(!last)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});
      if(pointers.size>=2){const d=spread();if(pinch)window.Physica3D.zoomBy(d/pinch);pinch=d}else window.Physica3D.rotate((e.clientX-last.x)*.009,(e.clientY-last.y)*.007)});
    const stopSteer=e=>{if(steering&&HAND())handOn('up',e);pointers.delete(e.pointerId);if(pointers.size<2)pinch=0;if(!pointers.size){steering=false;canvas.style.cursor='grab'}};
    canvas.addEventListener('pointerup',stopSteer);canvas.addEventListener('pointercancel',stopSteer);
    canvas.addEventListener('wheel',e=>{if(!orbiting()||!(e.ctrlKey||e.metaKey||document.fullscreenElement))return;e.preventDefault();window.Physica3D.zoomBy(Math.exp(-e.deltaY*.0025))},{passive:false});
    canvas.addEventListener('dblclick',()=>{if(is3D(current))window.Physica3D?.resetView()});
    requestAnimationFrame(frame)}
  else{document.querySelector('.stage').insertAdjacentText('beforeend','Canvas animations are unavailable in this browser.')}
})();
