(() => {
  'use strict';
  const R=(key,label,min,max,step,initial,unit='',digits=0)=>({key,label,min,max,step,initial,unit,digits});
  const N=(label,value)=>({label,value:String(value)});
  const sims=[
    {id:'units',grade:11,group:'FOUNDATIONS',chapter:'Units and Measurements',title:'Vernier caliper',description:'Slide the jaw around an object and read a small length on the main and vernier scales.',formula:'Length = MSR + VSR',observe:'The vernier scale resolves lengths between main-scale markings.',try:'Move the jaw by just 0.01 cm and watch the reading change.',controls:[R('measure','Object length',.5,5,.01,3.24,'cm',2)],metrics:p=>[N('Measured length',`${p.measure.toFixed(2)} cm`),N('Least count','0.01 cm')],draw:'units'},
    {id:'kinematics',grade:11,group:'MECHANICS',chapter:'Motion in a Straight Line',title:'Motion in one dimension',description:'Follow a cart and watch its position graph curve as its velocity changes.',formula:'x = ut + ½at²',observe:'With constant acceleration, velocity changes steadily while the position graph bends.',try:'Set acceleration to zero. What happens to the graph?',controls:[R('velocity','Initial velocity',1,18,1,7,'m/s'),R('acceleration','Acceleration',0,5,.2,2,'m/s²',1)],metrics:(p,t)=>{let q=t%8;return[N('Position',`${(p.velocity*q+.5*p.acceleration*q*q).toFixed(1)} m`),N('Current speed',`${(p.velocity+p.acceleration*q).toFixed(1)} m/s`),N('Acceleration',`${p.acceleration.toFixed(1)} m/s²`)]},draw:'kinematics'},
    {id:'projectile',grade:11,group:'MECHANICS',chapter:'Motion in a Plane',title:'Projectile motion',description:'Launch an object and see how horizontal and vertical motion combine to form its path.',formula:'R = v² sin(2θ) / g',observe:'Horizontal velocity stays constant; gravity changes the vertical velocity every second.',try:'Try 30° and 60° with the same speed. Compare their ranges.',controls:[R('speed','Launch speed',10,35,1,24,'m/s'),R('angle','Launch angle',15,75,1,48,'°'),R('gravity','Gravity',3,15,.1,9.8,'m/s²',1)],metrics:p=>{let th=p.angle*Math.PI/180;return[N('Range',`${(p.speed**2*Math.sin(2*th)/p.gravity).toFixed(1)} m`),N('Maximum height',`${(p.speed**2*Math.sin(th)**2/(2*p.gravity)).toFixed(1)} m`),N('Time of flight',`${(2*p.speed*Math.sin(th)/p.gravity).toFixed(2)} s`)]},draw:'projectile'},
    {id:'forces',grade:11,group:'MECHANICS',chapter:'Laws of Motion',title:'Forces and friction',description:'Push a block and see when the applied force overcomes friction.',formula:'Fₙₑₜ = ma',observe:'The block stays still until the applied force exceeds the maximum friction shown.',try:'Increase the mass without changing the applied force. Does it still move?',controls:[R('mass','Block mass',2,15,1,6,'kg'),R('force','Applied force',0,100,1,55,'N'),R('friction','Friction coefficient',0,.8,.05,.35,'',2)],metrics:p=>{let limit=p.friction*p.mass*9.8,actual=Math.min(p.force,limit),net=Math.max(0,p.force-limit);return[N('Friction force',`${actual.toFixed(1)} N`),N('Net force',`${net.toFixed(1)} N`),N('Acceleration',`${(net/p.mass).toFixed(2)} m/s²`)]},draw:'forces'},
    {id:'energy',grade:11,group:'MECHANICS',chapter:'Work, Energy and Power',title:'Conservation of energy',description:'Watch gravitational potential energy turn into kinetic energy on a frictionless track.',formula:'E = mgh + ½mv²',observe:'As the ball goes lower, potential energy falls and kinetic energy rises.',try:'Double the starting height. How does the maximum speed change?',controls:[R('height','Starting height',3,8,.5,6,'m',1),R('mass','Ball mass',1,10,1,3,'kg')],metrics:p=>[N('Total energy',`${(p.mass*9.8*p.height).toFixed(0)} J`),N('Peak speed',`${Math.sqrt(2*9.8*p.height).toFixed(1)} m/s`)],draw:'energy'},
    {id:'rotation',grade:11,group:'MECHANICS',chapter:'System of Particles and Rotational Motion',title:'Torque and rotation',description:'Apply a tangential force at different distances from a pivot and spin the disc.',formula:'τ = rF = Iα',observe:'The same force produces more torque when you apply it farther from the axis.',try:'Keep the force fixed and double the lever arm.',controls:[R('force','Tangential force',2,20,1,8,'N'),R('radius','Lever arm',.3,1.5,.1,.8,'m',1),R('inertia','Moment of inertia',1,8,.5,3,'kg·m²',1)],metrics:p=>[N('Torque',`${(p.force*p.radius).toFixed(1)} N·m`),N('Angular acceleration',`${(p.force*p.radius/p.inertia).toFixed(2)} rad/s²`)],draw:'rotation'},
    {id:'gravity',grade:11,group:'MECHANICS',chapter:'Gravitation',title:'Satellite orbit',description:'Move a satellite to another altitude and compare its speed and orbital period.',formula:'v = √(GM / r)',observe:'A higher circular orbit has a lower orbital speed and a longer period.',try:'Raise the altitude and watch the satellite slow down.',controls:[R('altitude','Orbit altitude',200,2000,50,500,'km')],metrics:p=>{let r=6371+p.altitude,v=Math.sqrt(3.986e5/r);return[N('Orbital speed',`${v.toFixed(2)} km/s`),N('Orbital period',`${(2*Math.PI*r/v/60).toFixed(1)} min`)]},draw:'gravity'},
    {id:'hooke',grade:11,group:'MATERIALS & HEAT',chapter:'Mechanical Properties of Solids',title:'Stretching a spring',description:'Pull the block and see how spring stiffness sets its extension.',formula:'F = kx',observe:'Doubling the applied force doubles extension while the spring stays in its elastic range.',try:'Keep the force fixed and choose a stiffer spring.',controls:[R('force','Pulling force',5,50,1,22,'N'),R('stiffness','Spring constant',100,500,10,220,'N/m')],metrics:p=>[N('Extension',`${(p.force/p.stiffness*100).toFixed(1)} cm`),N('Elastic energy',`${(.5*p.force*p.force/p.stiffness).toFixed(2)} J`)],draw:'hooke'},
    {id:'buoyancy',grade:11,group:'MATERIALS & HEAT',chapter:'Mechanical Properties of Fluids',title:'Float or sink?',description:'Change the densities and watch a block find its level in a fluid.',formula:'Fᵦ = ρfluid Vsub g',observe:'A floating block displaces fluid with the same weight as the block.',try:'Make the object denser than the fluid. What changes?',controls:[R('objectDensity','Object density',300,1500,50,600,'kg/m³'),R('fluidDensity','Fluid density',700,1300,50,1000,'kg/m³'),R('volume','Object volume',5,30,1,15,'L')],metrics:p=>{let fraction=Math.min(1,p.objectDensity/p.fluidDensity),V=p.volume/1000;return[N('Submerged',`${(fraction*100).toFixed(0)}%`),N('Buoyant force',`${(p.fluidDensity*V*fraction*9.8).toFixed(1)} N`),N('Object weight',`${(p.objectDensity*V*9.8).toFixed(1)} N`)]},draw:'buoyancy'},
    {id:'expansion',grade:11,group:'MATERIALS & HEAT',chapter:'Thermal Properties of Matter',title:'Thermal expansion',description:'Heat a metal rod and measure the small increase in its length.',formula:'ΔL = αL₀ΔT',observe:'The diagram magnifies the change in length so that it is easy to see.',try:'Double the original length. What happens to the expansion?',controls:[R('temperature','Final temperature',20,220,5,140,'°C'),R('length','Original length',.5,3,.1,1.5,'m',1),R('alpha','Expansion coefficient',8,30,1,18,'µ/K')],metrics:p=>[N('Temperature change',`${p.temperature-20} °C`),N('Length increase',`${(p.alpha*1e-6*p.length*(p.temperature-20)*1000).toFixed(2)} mm`)],draw:'expansion'},
    {id:'thermo',grade:11,group:'MATERIALS & HEAT',chapter:'Thermodynamics',title:'Gas under a piston',description:'Compress or heat an ideal gas and watch its pressure respond.',formula:'PV = nRT',observe:'At fixed temperature, a smaller volume means a larger pressure.',try:'Halve the volume while holding temperature and gas amount fixed.',controls:[R('volume','Gas volume',4,30,.5,15,'L',1),R('temperature','Temperature',200,600,10,300,'K'),R('moles','Amount of gas',.5,3,.1,1.5,'mol',1)],metrics:p=>[N('Pressure',`${(p.moles*8.314*p.temperature/p.volume).toFixed(0)} kPa`),N('PV',`${(p.moles*8.314*p.temperature).toFixed(0)} J`)],draw:'thermo'},
    {id:'kinetic',grade:11,group:'MATERIALS & HEAT',chapter:'Kinetic Theory',title:'Molecules in motion',description:'Heat a gas and watch its particles move faster inside a container.',formula:'vᵣₘₛ = √(3kT / m)',observe:'Temperature measures average translational kinetic energy, not the speed of a single molecule.',try:'Keep temperature constant and choose heavier molecules.',controls:[R('temperature','Gas temperature',100,900,10,300,'K'),R('molecularMass','Molecular mass',2,44,2,28,'u')],metrics:p=>{let vrms=Math.sqrt(3*1.380649e-23*p.temperature/(p.molecularMass*1.660539e-27));return[N('RMS speed',`${vrms.toFixed(0)} m/s`),N('Mean kinetic energy',`${(1.5*1.380649e-23*p.temperature/1.602176634e-19).toFixed(3)} eV`)]},draw:'kinetic'},
    {id:'pendulum',grade:11,group:'OSCILLATIONS & WAVES',chapter:'Oscillations',title:'Simple pendulum',description:'Set the length and release angle to watch a pendulum swing.',formula:'T ≈ 2π√(L / g)',observe:'For small angles, the period depends mostly on length, not on the bob’s mass.',try:'Double the length and see whether the period doubles.',controls:[R('length','String length',.5,2.5,.1,1.5,'m',1),R('amplitude','Release angle',5,35,1,22,'°')],metrics:p=>[N('Period (small angle)',`${(2*Math.PI*Math.sqrt(p.length/9.8)).toFixed(2)} s`),N('Frequency',`${(1/(2*Math.PI*Math.sqrt(p.length/9.8))).toFixed(2)} Hz`)],draw:'pendulum'},
    {id:'wave',grade:11,group:'OSCILLATIONS & WAVES',chapter:'Waves',title:'Travelling wave',description:'Change amplitude, wavelength and frequency to see a wave move through a medium.',formula:'v = fλ',observe:'The pattern travels while each marked point oscillates about its own equilibrium position.',try:'Double frequency while keeping wavelength fixed. How does speed change?',controls:[R('amplitude','Amplitude',.5,2.5,.1,1.3,'units',1),R('frequency','Frequency',.2,2,.1,.7,'Hz',1),R('wavelength','Wavelength',1,4,.1,2.5,'m',1)],metrics:p=>[N('Wave speed',`${(p.frequency*p.wavelength).toFixed(2)} m/s`),N('Period',`${(1/p.frequency).toFixed(2)} s`)],draw:'wave'},
    {id:'electrostatic',grade:12,group:'ELECTRICITY',chapter:'Electric Charges and Fields',title:'Electric field of two charges',description:'Change the charges and separation to explore how the field and force respond.',formula:'F = k|q₁q₂| / r²',observe:'Field arrows point away from positive charges and toward negative charges.',try:'Reverse one charge. Watch the field between them.',controls:[R('charge1','Charge 1',-5,5,1,3,'µC'),R('charge2','Charge 2',-5,5,1,-3,'µC'),R('separation','Separation',2,8,.5,5,'dm',1)],metrics:p=>[N('Force magnitude',`${(8.988e9*Math.abs(p.charge1*p.charge2)*1e-12/(p.separation/10)**2).toFixed(2)} N`),N('Interaction',p.charge1*p.charge2<0?'Attraction':p.charge1*p.charge2>0?'Repulsion':'No force')],draw:'electrostatic'},
    {id:'capacitor',grade:12,group:'ELECTRICITY',chapter:'Electrostatic Potential and Capacitance',title:'Parallel plate capacitor',description:'Bring plates closer or insert a dielectric to change stored charge.',formula:'C = κε₀A / d',observe:'Closer plates and a larger dielectric constant both increase capacitance.',try:'Double the plate spacing and compare the capacitance.',controls:[R('voltage','Potential difference',2,24,1,12,'V'),R('distance','Plate separation',1,5,.2,3,'mm',1),R('dielectric','Dielectric constant',1,6,.5,1,'',1)],metrics:p=>{let C=p.dielectric*8.854e-12*.02/(p.distance*.001);return[N('Capacitance',`${(C*1e12).toFixed(1)} pF`),N('Stored charge',`${(C*p.voltage*1e9).toFixed(2)} nC`),N('Stored energy',`${(.5*C*p.voltage**2*1e9).toFixed(2)} nJ`)]},draw:'capacitor'},
    {id:'circuit',grade:12,group:'ELECTRICITY',chapter:'Current Electricity',title:'Ohm’s law circuit',description:'Change battery voltage and resistance to control the current in a closed circuit.',formula:'V = IR',observe:'At fixed resistance, twice the voltage gives twice the current.',try:'Double the resistance and notice how the charge flow slows.',controls:[R('voltage','Battery voltage',1,24,1,12,'V'),R('resistance','Resistance',2,40,1,10,'Ω')],metrics:p=>[N('Current',`${(p.voltage/p.resistance).toFixed(2)} A`),N('Power',`${(p.voltage**2/p.resistance).toFixed(1)} W`)],draw:'circuit'},
    {id:'lorentz',grade:12,group:'MAGNETISM',chapter:'Moving Charges and Magnetism',title:'Charged particle in a field',description:'Watch a charged particle curve through a uniform magnetic field.',formula:'r = mv / |q|B',observe:'The magnetic force bends the path without changing the particle’s speed.',try:'Switch between electron and proton. Compare their physical orbit radii.',controls:[R('speed','Particle speed',1,8,.5,3,'×10⁶ m/s',1),R('field','Field strength',2,20,1,8,'mT'),{key:'particle',label:'Particle',options:[['electron','Electron'],['proton','Proton']],initial:'electron'},{key:'direction',label:'Field direction',options:[['into','Into the page'],['out','Out of the page']],initial:'into'}],metrics:p=>{let m=p.particle==='electron'?9.109e-31:1.673e-27,r=m*p.speed*1e6/(1.602e-19*p.field/1000);return[N('Orbit radius',r<.01?`${(r*1000).toFixed(2)} mm`:`${r.toFixed(2)} m`),N('Magnetic work','0 J') ]},draw:'lorentz'},
    {id:'magnet',grade:12,group:'MAGNETISM',chapter:'Magnetism and Matter',title:'Bar magnet and compass',description:'Explore the field around a bar magnet and the direction a compass points.',formula:'B ∝ magnetic moment / r³',observe:'Outside the magnet, magnetic field lines leave the north pole and enter the south pole.',try:'Increase magnetic strength. Watch the arrows around the magnet.',controls:[R('strength','Relative field strength',.5,3,.1,1.4,'×',1)],metrics:p=>[N('Field strength',`${p.strength.toFixed(1)}× reference`),N('Outside field','N → S')],draw:'magnet'},
    {id:'induction',grade:12,group:'MAGNETISM',chapter:'Electromagnetic Induction',title:'Magnet through a coil',description:'Move a magnet past a coil and watch the induced current reverse.',formula:'ε = −N dΦ/dt',observe:'The lamp responds to changing magnetic flux; a stationary magnet would not induce current.',try:'Move the magnet faster or add more turns to the coil.',controls:[R('speed','Magnet speed',.3,2.5,.1,1.1,'×',1),R('turns','Coil turns',3,8,1,5),R('strength','Magnet strength',.5,3,.1,1.5,'×',1)],metrics:(p,t)=>[N('Magnet motion',p.speed<.6?'Slow':p.speed>1.7?'Fast':'Moderate'),N('Coil turns',p.turns),N('Flux trend',Math.cos(t*p.speed*.9)>0?'Changing ↗':'Changing ↘')],draw:'induction'},
    {id:'ac',grade:12,group:'MAGNETISM',chapter:'Alternating Current',title:'AC generator',description:'Rotate a coil and track the alternating voltage it produces.',formula:'V(t) = V₀ sin(2πft)',observe:'Voltage changes sign every half cycle; the effective RMS voltage is smaller than the peak.',try:'Double the frequency. How does the period change?',controls:[R('voltage','Peak voltage',10,120,5,60,'V'),R('frequency','Frequency',.2,2,.1,.5,'Hz',1)],metrics:(p,t)=>[N('Instantaneous voltage',`${(p.voltage*Math.sin(2*Math.PI*p.frequency*t)).toFixed(1)} V`),N('RMS voltage',`${(p.voltage/Math.sqrt(2)).toFixed(1)} V`),N('Period',`${(1/p.frequency).toFixed(2)} s`)],draw:'ac'},
    {id:'emwave',grade:12,group:'MAGNETISM',chapter:'Electromagnetic Waves',title:'Electromagnetic wave',description:'See perpendicular electric and magnetic fields oscillate as a wave travels.',formula:'c = fλ',observe:'The electric and magnetic fields are in phase and move together through space.',try:'Shorten the wavelength. What happens to the frequency in vacuum?',controls:[R('wavelength','Wavelength',.5,4,.1,1.8,'m',1),R('amplitude','Relative amplitude',.5,2,.1,1.3,'×',1)],metrics:p=>[N('Frequency',`${(300/p.wavelength).toFixed(1)} MHz`),N('Speed in vacuum','3.00 × 10⁸ m/s')],draw:'emwave'},
    {id:'lens',grade:12,group:'OPTICS',chapter:'Ray Optics and Optical Instruments',title:'Image through a convex lens',description:'Move an object toward or away from a lens and trace the rays to its image.',formula:'1/f = 1/v + 1/u',observe:'An object inside the focal length makes a virtual, upright image.',try:'Move the object just inside the focal point.',controls:[R('objectDistance','Object distance',15,80,1,45,'cm'),R('focalLength','Focal length',10,30,1,20,'cm')],metrics:p=>{let v=p.objectDistance===p.focalLength?Infinity:p.focalLength*p.objectDistance/(p.objectDistance-p.focalLength);return[N('Image distance',Number.isFinite(v)?`${v.toFixed(1)} cm`:'At infinity'),N('Magnification',Number.isFinite(v)?`${(-v/p.objectDistance).toFixed(2)}×`:'Unbounded'),N('Image type',v>0?'Real, inverted':'Virtual, upright')]},draw:'lens'},
    {id:'doubleslit',grade:12,group:'OPTICS',chapter:'Wave Optics',title:'Double slit interference',description:'Pass light through two slits and watch bright and dark fringes form.',formula:'β = λD / d',observe:'Bright fringes occur where waves from the two slits arrive in phase.',try:'Increase the slit spacing. How does fringe spacing respond?',controls:[R('wavelength','Light wavelength',400,700,10,550,'nm'),R('slit','Slit separation',.2,1,.05,.5,'mm',2),R('distance','Screen distance',1,3,.1,2,'m',1)],metrics:p=>[N('Fringe spacing',`${(p.wavelength*1e-9*p.distance/(p.slit*1e-3)*1000).toFixed(2)} mm`),N('Central fringe','Bright')],draw:'doubleslit'},
    {id:'photoelectric',grade:12,group:'MODERN PHYSICS',chapter:'Dual Nature of Radiation and Matter',title:'Photoelectric effect',description:'Shine light on a metal and see whether it releases electrons.',formula:'Kₘₐₓ = hf − φ',observe:'Below the threshold frequency, brighter light still cannot eject electrons.',try:'Use a long wavelength with maximum intensity, then shorten the wavelength.',controls:[R('wavelength','Light wavelength',250,700,10,480,'nm'),R('workFunction','Work function',1.5,4.5,.1,2.2,'eV',1),R('intensity','Light intensity',10,100,10,60,'%')],metrics:p=>{let e=1240/p.wavelength,ke=Math.max(0,e-p.workFunction);return[N('Photon energy',`${e.toFixed(2)} eV`),N('Maximum K.E.',`${ke.toFixed(2)} eV`),N('Emission',e>=p.workFunction?'Yes':'No')]},draw:'photoelectric'},
    {id:'bohr',grade:12,group:'MODERN PHYSICS',chapter:'Atoms',title:'Bohr’s atomic model',description:'Choose an orbit and calculate the photon released in a transition to the ground state.',formula:'Eₙ = −13.6 Z² / n² eV',observe:'Higher levels are farther apart in radius but closer together in energy.',try:'Raise n and compare the n → 1 photon energy.',controls:[R('level','Excited energy level',2,5,1,3),R('atomicNumber','Atomic number (H-like)',1,3,1,1)],metrics:p=>[N('Orbit energy',`${(-13.6*p.atomicNumber**2/p.level**2).toFixed(2)} eV`),N('n → 1 photon',`${(13.6*p.atomicNumber**2*(1-1/p.level**2)).toFixed(2)} eV`)],draw:'bohr'},
    {id:'nuclear',grade:12,group:'MODERN PHYSICS',chapter:'Nuclei',title:'Radioactive decay',description:'See individual nuclei disappear while the population follows a half-life curve.',formula:'N(t) = N₀(½)^(t/T½)',observe:'After each half-life, approximately half of the undecayed population remains.',try:'Double the half-life. Compare the steepness of the decay curve.',controls:[R('initial','Initial nuclei',48,120,12,96),R('halfLife','Half-life',3,12,1,6,'s')],metrics:(p,t)=>{let q=t%Math.max(25,p.halfLife*5);return[N('Expected remaining',`${(p.initial*2**(-q/p.halfLife)).toFixed(0)}`),N('Elapsed time',`${q.toFixed(1)} s`),N('Half-life',`${p.halfLife} s`)]},draw:'nuclear'},
    {id:'diode',grade:12,group:'MODERN PHYSICS',chapter:'Semiconductor Electronics',title:'P–N junction diode',description:'Apply a voltage and watch the depletion region change with forward or reverse bias.',formula:'Forward bias → narrow junction',observe:'Forward bias reduces the barrier; reverse bias widens the depletion region.',try:'Move the voltage through zero and compare carrier movement.',controls:[R('voltage','Applied voltage',-2,2,.1,.8,'V',1)],metrics:p=>[N('Bias',p.voltage>0?'Forward':p.voltage<0?'Reverse':'None'),N('Depletion region',p.voltage>0?'Narrower':p.voltage<0?'Wider':'Equilibrium')],draw:'diode'}
  ];
  const chapters=sims.slice();
  for(const extra of window.ExtraSimulations||[]){const base=chapters.find(s=>s.id===extra.base);sims.push({...base,...extra,draw:extra.id});}
  const $=id=>document.getElementById(id),canvas=$('simulation'),ctx=canvas.getContext('2d');
  const saved=new Map(),defaultFor=sim=>Object.fromEntries(sim.controls.map(c=>[c.key,c.initial]));
  for(const s of sims)saved.set(s.id,defaultFor(s));
  let current=sims.find(s=>s.id===location.hash.slice(1))||sims.find(s=>s.id==='projectile');
  let playbackSpeed=1;
  const FAV_KEY='physica-favourites';
  let favourites=new Set();
  try{const value=JSON.parse(localStorage.getItem(FAV_KEY)||'[]');if(Array.isArray(value))favourites=new Set(value.filter(id=>sims.some(s=>s.id===id)));}catch{}
  function renderFavourites(){
    const host=$('favourites-list');host.replaceChildren();
    $('favourites-count').textContent=favourites.size;
    const starred=favourites.has(current.id),toggle=$('favourite-toggle');
    toggle.textContent=starred?'★ Starred':'☆ Favourite';toggle.setAttribute('aria-pressed',String(starred));
    toggle.setAttribute('aria-label',(starred?'Unstar ':'Star ')+current.title);
    if(!favourites.size){const p=document.createElement('p');p.className='favourites-empty';p.dataset.testid='favourites-empty';p.textContent='Star a simulation to keep it here. Both classes, one shortlist.';host.append(p);}
    for(const id of favourites){const sim=sims.find(s=>s.id===id),row=document.createElement('div');row.className='favourite-row';
      const open=document.createElement('button');open.type='button';open.textContent=sim.title;open.title=`Class ${sim.grade} · ${sim.chapter}`;open.dataset.testid='favourite-open-'+id;open.className=sim===current?'active':'';open.onclick=()=>{select(sim);closeSidebar();};
      const remove=document.createElement('button');remove.type='button';remove.textContent='★';remove.className='favourite-remove';remove.setAttribute('aria-label','Unstar '+sim.title);remove.dataset.testid='favourite-remove-'+id;remove.onclick=()=>toggleFavourite(id);row.append(open,remove);host.append(row);
    }
  }
  function toggleFavourite(id){favourites.has(id)?favourites.delete(id):favourites.add(id);try{localStorage.setItem(FAV_KEY,JSON.stringify([...favourites]));$('favourites-status').textContent='';}catch{$('favourites-status').textContent='Browser storage is full or unavailable. Stars will last for this visit only.';}renderFavourites();}
  $('favourite-toggle').onclick=()=>toggleFavourite(current.id);
  $('simulation-speed').onchange=e=>{playbackSpeed=Number(e.target.value);};
  $('simulation-step').onclick=()=>{playing=false;elapsed+=1/30;syncPlay();updateReadouts();draw();};
  let grade=current.grade,elapsed=0,playing=!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches,lastFrame=performance.now(),lastReadout=0;
  const fmt=c=>`${typeof saved.get(current.id)[c.key]==='number'?saved.get(current.id)[c.key].toFixed(c.digits||0):saved.get(current.id)[c.key]}${c.unit?' '+c.unit:''}`;
  function renderSidebar(){
    const search=$('search').value.trim().toLowerCase();
    const entries=chapters.filter(s=>s.grade===grade&&(!search||sims.some(x=>x.chapter===s.chapter&&`${x.chapter} ${x.title} ${x.description}`.toLowerCase().includes(search))));
    const nav=$('chapter-list');nav.replaceChildren();let group='';
    if(!entries.length){const empty=document.createElement('p');empty.className='empty-search';empty.textContent='No chapters match. Try a different word.';nav.append(empty);return}
    for(const s of entries){
      if(s.group!==group){group=s.group;const heading=document.createElement('div');heading.className='chapter-group';heading.textContent=group;nav.append(heading)}
      const button=document.createElement('button');button.type='button';button.dataset.testid='chapter-'+s.id;button.className='chapter-link'+(s.chapter===current.chapter?' active':'');button.setAttribute('aria-current',s.chapter===current.chapter?'page':'false');
      const num=document.createElement('span');num.className='chapter-num';num.textContent=String(chapters.filter(x=>x.grade===grade).indexOf(s)+1).padStart(2,'0');
      const label=document.createElement('span');label.textContent=s.chapter;
      const arrow=document.createElement('span');arrow.className='chapter-arrow';arrow.textContent='↗';arrow.setAttribute('aria-hidden','true');
      button.append(num,label,arrow);button.addEventListener('click',()=>{select(s);closeSidebar()});nav.append(button)
    }
  }
  function renderSimulationTabs(){const holder=$('simulation-tabs');holder.replaceChildren();for(const sim of sims.filter(s=>s.chapter===current.chapter&&s.grade===current.grade)){const button=document.createElement('button');button.type='button';button.dataset.testid='sim-tab-'+sim.id;button.textContent=sim.title;button.className=sim===current?'selected':'';button.setAttribute('aria-pressed',String(sim===current));button.addEventListener('click',()=>select(sim));holder.append(button)}$('library-count').textContent=`${sims.length} SIMULATIONS`;}
  function renderLesson(){const holder=$('lesson-section'),lesson=window.SimulationLessons?.[current.id];holder.hidden=!lesson;holder.replaceChildren();if(!lesson)return;const top=document.createElement('div');top.className='lesson-top';const heading=document.createElement('h2');heading.textContent='Try a comparison';const presets=document.createElement('div');presets.className='preset-buttons';for(const preset of lesson.presets){const button=document.createElement('button');button.type='button';button.textContent=preset.label;button.addEventListener('click',()=>{Object.assign(saved.get(current.id),preset.values);elapsed=0;renderControls();updateReadouts(true);draw()});presets.append(button)}top.append(heading,presets);const grid=document.createElement('div');grid.className='lesson-grid';const worked=document.createElement('div');const wl=document.createElement('h3');wl.textContent='With your values';const equation=document.createElement('p');equation.id='worked-equation';worked.append(wl,equation);const assumptions=document.createElement('div');const al=document.createElement('h3');al.textContent='About this model';const ap=document.createElement('p');ap.textContent=lesson.assumption;assumptions.append(al,ap);if(current.reference){const link=document.createElement('a');link.className='model-reference';link.href=current.reference.url;link.textContent=current.reference.label;link.target='_blank';link.rel='noopener noreferrer';assumptions.append(link)}grid.append(worked,assumptions);holder.append(top,grid);}
  function renderControls(){
    const host=$('controls');host.replaceChildren();const p=saved.get(current.id);
    for(const c of current.controls){
      const row=document.createElement('div');row.className='control-row';
      const label=document.createElement('label');label.className='control-label';label.htmlFor=`control-${c.key}`;
      const name=document.createElement('span');name.textContent=c.label;
      const display=document.createElement('span');display.className='control-value';display.dataset.testid='control-value-'+c.key;display.textContent=typeof p[c.key]==='number'?fmt(c):'';label.append(name,display);row.append(label);
      if(c.options){const select=document.createElement('select');select.id=`control-${c.key}`;select.dataset.testid='control-'+c.key;for(const [value,title] of c.options){const option=document.createElement('option');option.value=value;option.textContent=title;select.append(option);}select.value=p[c.key];select.onchange=()=>{p[c.key]=c.options.find(([v])=>String(v)===select.value)[0];display.textContent=typeof p[c.key]==='number'?fmt(c):'';updateReadouts();draw();};row.append(select);}
      else{
        const input=document.createElement('input'),number=document.createElement('input');
        for(const [el,type] of [[input,'range'],[number,'number']]){el.type=type;el.min=c.min;el.max=c.max;el.step=c.step;el.value=p[c.key];el.id=`${type==='range'?'control':'exact'}-${c.key}`;el.dataset.testid=el.id;el.setAttribute('aria-label',c.label+(type==='number'?' exact value':''));}
        number.className='exact-value';
        const sync=()=>{input.value=p[c.key];number.value=p[c.key];display.textContent=fmt(c);input.setAttribute('aria-valuetext',fmt(c));input.style.setProperty('--fill',`${(p[c.key]-c.min)/(c.max-c.min)*100}%`);updateReadouts();draw();};
        input.oninput=()=>{p[c.key]=Number(input.value);sync();};
        number.onchange=()=>{if(number.value!==''&&Number.isFinite(number.valueAsNumber)){const v=Math.max(c.min,Math.min(c.max,number.valueAsNumber));p[c.key]=Number(Math.min(c.max,c.min+Math.round((v-c.min)/c.step)*c.step).toFixed(8));}sync();};
        const ends=document.createElement('div');ends.className='control-extents';ends.textContent=`${c.min} — ${c.max}${c.unit?' '+c.unit:''}`;row.append(input,ends,number);
        input.setAttribute('aria-valuetext',fmt(c));input.style.setProperty('--fill',`${(p[c.key]-c.min)/(c.max-c.min)*100}%`);
      }
      host.append(row);
    }
  }
  function updateReadouts(rebuild=false){const data=current.metrics(saved.get(current.id),elapsed);const holder=$('readouts');if(rebuild||holder.children.length!==data.length){holder.replaceChildren();for(const m of data){const box=document.createElement('div');box.className='readout';const key=document.createElement('span');key.className='readout-label';key.textContent=m.label;const val=document.createElement('strong');val.className='readout-value';val.dataset.testid='readout-'+holder.children.length;val.textContent=m.value;box.append(key,val);holder.append(box)}}else data.forEach((m,i)=>{holder.children[i].querySelector('.readout-value').textContent=m.value});$('elapsed').textContent=`${elapsed.toFixed(1)} s`;const equation=$('worked-equation');if(equation&&window.SimulationLessons?.[current.id])equation.textContent=window.SimulationLessons[current.id].worked(saved.get(current.id),elapsed);window.PhysicaExperience?.update()}
  function render(){const gradeSims=chapters.filter(s=>s.grade===current.grade),ix=gradeSims.findIndex(s=>s.chapter===current.chapter);grade=current.grade;document.title=`${current.title} | Physica`;document.querySelectorAll('.grade-tab').forEach(b=>{let active=Number(b.dataset.grade)===grade;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
    $('grade-crumb').textContent=`CLASS ${grade}`;$('chapter-crumb').textContent=current.chapter.toUpperCase();$('position').textContent=`${String(ix+1).padStart(2,'0')} / ${gradeSims.length}`;$('sim-number').textContent=`№ ${String(ix+1).padStart(2,'0')}`;$('title').textContent=current.title;$('description').textContent=current.description;$('formula').textContent=current.formula;$('observation').textContent=current.observe;$('try-this').textContent=current.try;canvas.setAttribute('aria-label',`${current.title} animated physics simulation`);$('prev').disabled=ix===0;$('next').disabled=ix===gradeSims.length-1;
    $('search').value='';renderFavourites();renderSidebar();renderControls();renderSimulationTabs();renderLesson();updateReadouts(true);syncPlay();draw();
  }
  function select(s,scroll=true){if(!s)return;window.PhysicaExperience?.onSelect();current=s;elapsed=0;history.replaceState(null,'',`#${s.id}`);render();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
  function syncPlay(){$('play-icon').textContent=playing?'Ⅱ':'▶';$('play-label').textContent=playing?'Pause':'Play';$('play').setAttribute('aria-label',playing?'Pause simulation':'Play simulation');$('live-status').textContent=playing?'LIVE SIMULATION':'SIMULATION PAUSED';document.querySelector('.stage').classList.toggle('paused',!playing);window.PhysicaExperience?.update()}
  function resize(){const box=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(box.width<1)return;canvas.width=Math.round(box.width*dpr);canvas.height=Math.round(box.height*dpr);ctx.setTransform(canvas.width/960,0,0,canvas.height/505,0,0);draw()}
  function draw(){if(!ctx)return;ctx.clearRect(0,0,960,505);try{window.PhysicsDraw.draw(window.PhysicaTheme.wrapContext(ctx),current.draw,saved.get(current.id),elapsed)}catch(err){console.error('Simulation drawing error',current.id,err);ctx.fillStyle='#0b2030';ctx.fillRect(0,0,960,505);ctx.fillStyle='#eff8ff';ctx.font='22px system-ui';ctx.fillText('This simulation could not be drawn. Try another chapter.',65,235)}}
  window.addEventListener('physica-theme-change',draw);
  function frame(now){let dt=Math.min((now-lastFrame)/1000,.06);lastFrame=now;if(!$('sandbox-view').hidden){requestAnimationFrame(frame);return;}if(playing)elapsed=(elapsed+dt*playbackSpeed)%3600;draw();window.PhysicaExperience?.draw();if(now-lastReadout>110){updateReadouts();lastReadout=now}requestAnimationFrame(frame)}
  function closeSidebar(){$('sidebar').classList.remove('open');$('mobile-topics').setAttribute('aria-expanded','false')}
  $('mobile-topics').addEventListener('click',()=>{let open=$('sidebar').classList.toggle('open');$('mobile-topics').setAttribute('aria-expanded',String(open));if(open)$('search').focus()});
  $('search').addEventListener('input',renderSidebar);
  document.querySelectorAll('.grade-tab').forEach(b=>b.addEventListener('click',()=>{const g=Number(b.dataset.grade);if(g!==grade)select(sims.find(s=>s.grade===g));else renderSidebar()}));
  $('prev').addEventListener('click',()=>{let l=chapters.filter(s=>s.grade===grade);select(l[l.findIndex(s=>s.chapter===current.chapter)-1])});$('next').addEventListener('click',()=>{let l=chapters.filter(s=>s.grade===grade);select(l[l.findIndex(s=>s.chapter===current.chapter)+1])});
  $('play').addEventListener('click',()=>{playing=!playing;syncPlay()});$('restart').addEventListener('click',()=>{elapsed=0;updateReadouts();draw()});$('defaults').addEventListener('click',()=>{saved.set(current.id,defaultFor(current));elapsed=0;renderControls();updateReadouts(true);draw()});
  document.addEventListener('keydown',e=>{if(!$('sandbox-view').hidden)return;if(e.key==='Escape'){closeSidebar();document.activeElement?.blur()}if(e.key==='/'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();if(innerWidth<=760){$('sidebar').classList.add('open');$('mobile-topics').setAttribute('aria-expanded','true')}$('search').focus()}if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement?.tagName)){e.preventDefault();playing=!playing;syncPlay()}});
  window.addEventListener('hashchange',()=>{let target=sims.find(s=>s.id===location.hash.slice(1));if(target&&target!==current)select(target)});
  // Optional browser agent controls share the exact same state and rendering path as the UI.
  if(document.modelContext?.registerTool){
    const lifecycle=new AbortController();
    const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(console.warn)}catch(err){console.warn(err)}};
    const ids=sims.map(s=>s.id);
    register({name:'open_physics_simulation',title:'Open physics simulation',description:'Open a Class 11 or 12 chapter simulation by its ID.',inputSchema:{type:'object',properties:{simulationId:{type:'string',enum:ids}},required:['simulationId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const target=sims.find(s=>s.id===input?.simulationId);if(!target)throw Error('Unknown simulation ID');select(target);return{simulationId:current.id,title:current.title,parameters:saved.get(current.id)}}});
    register({name:'configure_physics_simulation',title:'Configure physics simulation',description:'Change one or more parameters and update the visible animation and calculated values.',inputSchema:{type:'object',properties:{simulationId:{type:'string',enum:ids},values:{type:'object',minProperties:1,additionalProperties:{anyOf:[{type:'number'},{type:'string'}]}}},required:['simulationId','values'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const target=sims.find(s=>s.id===input?.simulationId);if(!target||!input.values||Array.isArray(input.values)||typeof input.values!=='object')throw Error('Provide a simulation and its parameters');const changes=Object.entries(input.values);if(!changes.length)throw Error('At least one parameter is required');for(const [key,value] of changes){const c=target.controls.find(control=>control.key===key);if(!c)throw Error(`Unknown parameter: ${key}`);if(c.options){if(!c.options.some(([v])=>v===value))throw Error(`Invalid value for ${key}`)}else if(typeof value!=='number'||!Number.isFinite(value)||value<c.min||value>c.max||Math.abs((value-c.min)/c.step-Math.round((value-c.min)/c.step))>1e-4)throw Error(`Out of range or off step: ${key}`)}const p=saved.get(target.id);for(const [key,value] of changes)p[key]=value;if(target!==current)select(target);else{renderControls();updateReadouts();draw()}return{simulationId:target.id,parameters:p,results:target.metrics(p,elapsed)}}});
    addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
  if(ctx){render();new ResizeObserver(resize).observe(canvas);resize();window.PhysicaExperience?.init({state:()=>({current,params:saved.get(current.id),time:elapsed,playing}),open(id,values){const target=sims.find(s=>s.id===id);if(!target)return;saved.set(id,{...defaultFor(target),...values});select(target,false)}});
    // Direct manipulation: drag anywhere on the stage to steer the first two sliders with touch or mouse.
    let steering=false;
    function stageDrag(e){const rng=current.controls.filter(c=>!c.options);if(!rng.length)return;const box=canvas.getBoundingClientRect();if(box.width<1)return;const px=(e.clientX-box.left)/box.width,py=(e.clientY-box.top)/box.height,p=saved.get(current.id);const setC=(c,frac)=>{let v=c.min+(c.max-c.min)*Math.min(1,Math.max(0,frac));v=Math.round((v-c.min)/c.step)*c.step+c.min;p[c.key]=Number(Math.min(c.max,Math.max(c.min,v)).toFixed(8))};setC(rng[0],px);if(rng[1])setC(rng[1],1-py);renderControls();updateReadouts();draw()}
    canvas.style.cursor='grab';
    canvas.addEventListener('pointerdown',e=>{steering=true;canvas.style.cursor='grabbing';try{canvas.setPointerCapture(e.pointerId)}catch{}stageDrag(e)});
    canvas.addEventListener('pointermove',e=>{if(steering)stageDrag(e)});
    const stopSteer=()=>{steering=false;canvas.style.cursor='grab'};
    canvas.addEventListener('pointerup',stopSteer);canvas.addEventListener('pointercancel',stopSteer);
    requestAnimationFrame(frame)}
  else{document.querySelector('.stage').insertAdjacentText('beforeend','Canvas animations are unavailable in this browser.')}
})();
