/* Teaching lens, opt-in Web Audio, and guided surprise experiments. */
(() => {
'use strict';
const {C,text,line,rr,dot,arrow,arc,wrap}=window.PhysicaDrawing;
const F=(x,d=2)=>Number(x).toFixed(d),g=9.8,TAU=Math.PI*2,mod=(x,n)=>((x%n)+n)%n;
const V=(label,x,y,unit='N',value)=>({label,x,y,unit,value});
const force=(title,body,vectors,note)=>({kind:'vectors',title,body,vectors,note,scale:'Force arrows share one scale. Only forces acting on the body are included.'});
function profile(s,p,t){
 const M=window.FourthModels,T=window.PhysicaModels,id=s.id;
 if(id==='forces'){let weight=p.mass*g,f=Math.min(p.force,p.friction*weight);return force('Free-body diagram: block on the floor','BLOCK',[V('N',0,weight),V('mg',0,-weight),V('Push',p.force,0),V('Friction',-f,0)],`ΣFx = ${F(p.force-f)} N, so ax = ${F((p.force-f)/p.mass)} m/s². Vertical forces balance.`)}
 if(id==='elevator-weight'){let z=M.elevator(p);return force('Free-body diagram: elevator passenger','PASSENGER',[V('N',0,z.N),V('mg',0,-z.weight)],`Up is positive. N − mg = ${F(z.N-z.weight,1)} N = ma. The acceleration is ${p.acceleration.toFixed(1)} m/s².`)}
 if(id==='atwood'){let z=T.atwood(p);return{kind:'pair',title:'Free-body diagrams: both hanging masses',bodies:[{name:'LEFT MASS m₁',vectors:[V('T',0,z.tension),V('m₁g',0,-p.m1*g)]},{name:'RIGHT MASS m₂',vectors:[V('T',0,z.tension),V('m₂g',0,-p.m2*g)]}],note:`T = ${F(z.tension)} N on both sides. Right-side downward acceleration = ${F(z.a)} m/s²; the left side has the opposite acceleration.`,scale:'Arrows use one common force scale for both masses.'}}
 if(id==='inclined-plane'){let a=p.angle*Math.PI/180,N=g*Math.cos(a),f=Math.min(g*Math.sin(a),p.mu*N);return{...force('Free-body diagram: block on an incline','BLOCK',[V('N/m',N*Math.sin(a),N*Math.cos(a),'N/kg'),V('g',0,-g,'N/kg'),V('f/m',-f*Math.cos(a),f*Math.sin(a),'N/kg')],`Forces per unit mass are shown because mass is not an input. Down-slope acceleration = ${F(g*Math.sin(a)-f)} m/s². Weight components are not extra forces.`),scale:'All arrows show force divided by mass, in N/kg.'}}
 if(id==='projectile'||id==='vertical-throw'){let gravity=id==='projectile'?p.gravity:g,th=(p.angle||90)*Math.PI/180,Tflight=id==='projectile'?2*p.speed*Math.sin(th)/gravity:M.throw(p).T,q=Math.min(mod(t,Tflight+1),Tflight),vx=id==='projectile'?p.speed*Math.cos(th):0,vy=p.speed*Math.sin(th)-gravity*q;return{kind:'flight',title:'In-flight forces and velocity components',body:'BALL',vectors:[V('Gravity',0,-1,'','mg')],velocity:[vx,vy],note:`vx = ${F(vx)} m/s; vy = ${F(vy)} m/s. During flight, gravity is the only force and ay = −${gravity.toFixed(1)} m/s², including at the highest point.`,scale:'The mg arrow is symbolic; velocity arrows use a separate scale. Diagram describes flight before ground contact.'}}
 if(id==='spring-launcher'){let z=M.launch(p,t),Fs=z.time<z.release?-p.k*z.x:0;return force('Free-body diagram: spring-launched cart','CART',[V('N',0,p.mass*g),V('mg',0,-p.mass*g),V('Spring',Fs,0)],z.time<z.release?`The compressed spring pushes right with ${F(Fs)} N. As compression falls, its force and acceleration decrease.`:'After contact is lost, spring force is zero. Vertical forces balance, so the cart continues at constant velocity.')}
 if(id==='spring-shm'||id==='damped-oscillation'||id==='driven-resonance'){let m=p.mass||1,k=p.k||TAU**2,x,v,b=0,drive=0;if(id==='spring-shm'){let w=Math.sqrt(k/m);x=p.amplitude*Math.cos(w*t);v=-p.amplitude*w*Math.sin(w*t)}else if(id==='damped-oscillation'){let z=T.damping(p,t);x=z.x;v=-.5*Math.exp(-z.beta*z.time)*(z.beta*Math.cos(z.wd*z.time)+z.wd*Math.sin(z.wd*z.time));b=p.damping}else{let z=M.resonance(p);x=z.A*Math.cos(z.w*t-z.phase);v=-z.A*z.w*Math.sin(z.w*t-z.phase);b=p.damping;drive=p.force*Math.cos(z.w*t)}let vs=[V('N',0,m*g),V('mg',0,-m*g),V('Spring',-k*x,0)];if(b)vs.push(V('Damping',-b*v,0));if(id==='driven-resonance')vs.push(V('Drive',drive,0));return force('Free-body diagram: spring–mass system','MASS',vs,`x = ${F(x,3)} m and v = ${F(v,3)} m/s. Spring force = −kx; damping opposes velocity. Net horizontal force = ${F(-k*x-b*v+drive)} N.`)}
 if(id==='terminal-speed'){let z=M.stokes(p,t);return force('Free-body diagram: sphere in viscous liquid','SPHERE',[V('Weight',0,-z.weight*1000,'mN'),V('Buoyancy',0,z.buoyancy*1000,'mN'),V('Drag',0,z.drag*1000,'mN')],`Downward resultant = ${F((z.weight-z.buoyancy-z.drag)*1000,4)} mN. At terminal speed, weight = buoyancy + drag.`)}
 if(id==='buoyancy'){let m=p.objectDensity*p.volume/1000,w=m*g,B=Math.min(w,p.fluidDensity*p.volume/1000*g),vs=[V('Weight',0,-w),V('Buoyancy',0,B)];if(w>B)vs.push(V('Floor N',0,w-B));return force('Equilibrium forces: floating or resting on the bottom','BLOCK',vs,p.objectDensity<=p.fluidDensity?'At its floating level, buoyancy equals weight. No floor support is needed.':'After the block settles on the bottom, the floor supplies the part of its weight not balanced by buoyancy.')}
 if(id==='lifting-power')return force('Free-body diagram: load at constant speed','LOAD',[V('Tension',0,p.mass*g),V('Weight',0,-p.mass*g)],`The forces balance because the selected lifting speed is constant. Power = mgv = ${F(p.mass*g*p.speed,1)} W.`);
 if(id==='circular-motion'){let a=p.speed/p.radius*t;return{kind:'vectors',title:'Velocity is tangential; acceleration is radial',body:'PARTICLE',vectors:[V('v',-p.speed*Math.sin(a),-p.speed*Math.cos(a),'m/s'),V('a',-p.speed*p.speed/p.radius*Math.cos(a),p.speed*p.speed/p.radius*Math.sin(a),'m/s²')],separate:true,note:`Speed stays ${p.speed} m/s, while the direction changes. The required inward resultant force is mv²/r; centripetal force names this resultant, not an extra force.`,scale:'Velocity and acceleration use separate scales; y is upward.'}}
 if(id==='rolling')return{kind:'vectors',title:'Velocities during rolling without slipping',body:'WHEEL',vectors:[V('Centre v',p.speed,0,'m/s'),V('Top 2v',2*p.speed,0,'m/s')],note:`ω = v/R = ${F(p.speed/p.radius)} rad/s, clockwise for rolling to the right. The instantaneous contact-point velocity is zero.`,scale:'These are velocity comparisons at different points, not a free-body diagram.'};
 if(id==='pendulum'){let w=Math.sqrt(g/p.length),a=p.amplitude*Math.PI/180,theta=a*Math.cos(w*t),v=-p.length*a*w*Math.sin(w*t),Tper=g*Math.cos(theta)+v*v/p.length;return{...force('Forces on the pendulum bob','BOB',[V('T/m',-Tper*Math.sin(theta),Tper*Math.cos(theta),'N/kg'),V('g',0,-g,'N/kg')],`T/m = g cos θ + v²/L = ${F(Tper)} N/kg. Tension is radial; gravity also has a tangential restoring component.`),scale:'Forces divided by bob mass, in N/kg. Values use the small-angle trajectory of the main model.'}}
 if(id==='velocity-selector'){let z=M.selector(p);return force('Entrance forces on the proton','PROTON',[V('qE',0,z.Fe*1e18,'aN'),V('qvB',0,-z.Fb*1e18,'aN')],`The proton enters toward the right; B is out of the page. Electric force points up and magnetic force down. Entry resultant = ${F((z.Fe-z.Fb)*1e18)} aN upward.`)}
 if(id==='lorentz'){let charge=p.particle==='electron'?-1:1,B=p.direction==='out'?1:-1,m=p.particle==='electron'?9.109e-31:1.673e-27;return force('Magnetic force for an initial rightward velocity',p.particle.toUpperCase(),[V('q(v × B)',0,-charge*B*1.602e-19*p.speed*1e6*p.field/1000*1e15,'fN')],`B points ${p.direction==='out'?'out of':'into'} the page. A negative charge reverses the right-hand-rule direction. Magnetic force is perpendicular to velocity and does no work; radius = ${F(m*p.speed*1e6/(1.602e-19*p.field/1000),4)} m.`)}
 if(id==='dipole-torque'){let z=M.dipole(p);return{kind:'dipole',title:'Equal opposite forces, nonzero torque',angle:p.angle,v:z.force*1e9,note:`Each charge feels ${F(z.force*1e9)} nN. Their resultant is zero; torque magnitude = ${F(z.torque*1e9)} nN·m. The torque tends to align the dipole with E.`,scale:'Charge spacing follows the selected orientation. E points right.'}}
 if(id==='tangent-galvanometer'){let z=M.tangent(p);return{kind:'vectors',title:'The compass follows the resultant magnetic field',body:'COMPASS',vectors:[V('Earth BH',0,25,'µT'),V('Coil B',z.coil*1e6,0,'µT'),V('Resultant',z.coil*1e6,25,'µT')],note:`tan θ = Bcoil/BH; θ = ${F(z.theta*180/Math.PI,1)}°. North is upward and east is rightward. These field arrows are vectors, not forces.`,scale:'Magnetic field arrows share one scale.'}}
 if(id==='electrostatic'){let Fq=8.988e9*Math.abs(p.charge1*p.charge2)*1e-12/(p.separation/10)**2,sign=Math.sign(p.charge1*p.charge2);return{kind:'pair',title:'Equal and opposite Coulomb forces',bodies:[{name:'LEFT CHARGE',vectors:[V('F₁',-sign*Fq,0)]},{name:'RIGHT CHARGE',vectors:[V('F₂',sign*Fq,0)]}],note:`Force magnitude = ${F(Fq)} N on each charge. ${sign<0?'Opposite charges attract.':sign>0?'Like charges repel.':'If either charge is zero, their mutual electric force is zero.'}`,scale:'The force on each body is drawn separately, using one common scale.'}}
 if(id==='equipotential-map'||id==='gauss'){let a=(p.angle||0)*Math.PI/180,field=8.988*p.charge/p.radius**2;return{kind:'vectors',title:'Electric field direction at the probe',body:'PROBE',vectors:[V('E',field*Math.cos(a),field*Math.sin(a),'N/C')],note:field===0?'Zero source charge gives zero electric field.':`The field points ${field>0?'away from':'toward'} the source. Equipotential surfaces are perpendicular to E.`,scale:'Electric-field arrow; this is not a force on the probe.'}}
 if(id==='vector-addition'){let z=M.vectors(p),a=p.angle*Math.PI/180;return{kind:'vectors',title:'Resolve, add, then reconstruct the resultant',body:'ORIGIN',vectors:[V('A',p.a,0,'units'),V('B',p.b*Math.cos(a),p.b*Math.sin(a),'units'),V('R',z.x,z.y,'units')],note:`Rx = ${F(z.x)} and Ry = ${F(z.y)}. ${z.r<1e-8?'The zero resultant has no defined direction.':'Direction = '+F(Math.atan2(z.y,z.x)*180/Math.PI,1)+'° from +x.'}`,scale:'All vector arrows share one scale.'}}
 if(id==='gravity-depth'){let z=M.depth(p);return{kind:'vectors',title:'Field points toward Earth’s centre',body:'PROBE',vectors:[V('g',-z.field,0,'m/s²')],note:`At r = ${z.r} km, g = ${F(z.field)} m/s². The probe is drawn to the right of the centre, so gravity points left.`,scale:'Field acceleration, not a force on a specified probe mass.'}}
 if(id==='maxwell-speeds'){let z=M.maxwell(p);return{kind:'bars',title:'Three averages of one speed distribution',bars:[['Most probable',z.mp,'m/s'],['Mean',z.mean,'m/s'],['RMS',z.rms,'m/s']],note:'These are statistical speed measures. RMS gives the correct average kinetic energy because it averages v² before taking the square root.',scale:'All speed bars share one scale.'}}
 if(id==='beats'){let a=p.amplitude*Math.sin(TAU*p.f1*t),b=p.amplitude*Math.sin(TAU*p.f2*t);return{kind:'bars',title:'Instantaneous superposition at one point',bars:[['Wave 1',a,'units'],['Wave 2',b,'units'],['Sum',a+b,'units']],note:`The signed displacements add. Beat rate = |f₁−f₂| = ${F(Math.abs(p.f1-p.f2),1)} Hz. The gold envelope is an amplitude envelope, not a third wave.`,scale:'Bars show signed displacement, using one scale.'}}
 if(id==='alpha-recoil'){let z=M.alpha(p);return{kind:'pair',title:'Momentum conservation in two-body decay',bodies:[{name:'DAUGHTER',vectors:[V('pd',-1,0,'','−p')]},{name:'ALPHA',vectors:[V('pα',1,0,'','+p')]}],note:`The momentum magnitudes match, although kinetic energies differ: alpha ${F(z.alpha,3)} MeV; daughter ${F(z.daughter,3)} MeV. Total momentum remains zero.`,scale:'Symbolic equal momentum arrows; positions are schematic.'}}
 if(id==='internal-resistance'){let z=M.cell(p);return{kind:'bars',title:'Where the cell’s emf is used',bars:[['Terminal voltage',z.V,'V'],['Internal voltage loss',z.I*p.internal,'V'],['Cell emf',p.emf,'V']],note:'Potential rises inside the ideal emf source and falls across both resistances. Conventional current leaves the positive terminal; electrons in metal move oppositely.',scale:'Voltage bars share one scale.'}}
 if(id==='zener-regulator'){let z=M.zener(p);return{kind:'bars',title:'Current splits at the output node',bars:[['Series current',z.I*1000,'mA'],['Load current',z.load*1000,'mA'],['Zener current',z.Iz*1000,'mA']],note:`Kirchhoff’s junction rule: Is = IL + IZ. ${z.regulated?'The Zener conducts in reverse breakdown and clamps output.':'Below breakdown, IZ = 0 and the output follows the resistor divider.'}`,scale:'Current bars share one scale.'}}
 const notes={
  'parallax':'The dashed normal is the error-free viewing direction. The green line of sight projects the raised pointer onto the ruler.',
  'rod-pendulum':'Weight acts downward at the centre of mass, L/2 from the pivot. Its perpendicular moment arm is (L/2) sin θ; torque restores the rod toward vertical.',
  'spring-network':p.mode==='series'?'Series: each spring carries the full applied force; extensions add.':'Parallel: both springs have the same extension; their restoring forces add.',
  'heat-conduction':'Heat flows from the hotter face to the colder face. The temperature gradient and heat-flow direction are opposite in Fourier’s signed law.',
  'adiabatic':p.ratio<1?'Compression: work enters the gas, internal energy rises, and Q = 0.':'Expansion: work leaves the gas, internal energy falls, and Q = 0.',
  'eddy-brake':'Braking torque is opposite angular velocity. It reduces rotational kinetic energy; the corresponding energy appears as heat.',
  'ac-power':'Current lags voltage by φ. Instantaneous p = vi can be negative when the inductor returns stored energy; cycle-average power is positive.',
  'displacement-current':'At maximum electric field, dE/dt = 0, so instantaneous current is zero. The changing-field term and wire current have equal signed values.',
  'optical-fibre':'Angles at the wall are measured from its normal. The reflected ray keeps the same incidence angle; total internal reflection requires i ≥ ic.',
  'thin-film':'The first air-to-film reflection gains π phase. The second film-to-air reflection does not. Optical path and reflection phase both determine interference.',
  'compton':'Incident photon momentum equals the vector sum of scattered-photon and recoil-electron momenta. Energy and momentum are both conserved.',
  'franck-hertz':'Electrons gain energy from the accelerating field. In this ideal threshold model, each inelastic mercury excitation removes about 4.9 eV.',
  'lens':'Light refracts at the lens. The central ray continues straight; a ray parallel to the axis passes through the far focus. Back extensions locate a virtual image.',
  'refraction':'Angles are measured from the normal. Entering higher refractive index bends toward the normal; total internal reflection can occur only from higher to lower index.',
  'doubleslit':'Path difference determines phase difference. In the far-field approximation, bright fringes occur at d sin θ = mλ and dark fringes at (m+½)λ.',
  'diffraction':'For a single slit, minima satisfy a sin θ = mλ with nonzero integer m. Increasing screen distance spreads the pattern on the screen.',
  'polarization':'The analyser transmits the electric-field component along its axis. Field amplitude projects as cos θ; intensity projects as cos² θ.',
  'prism-dispersion':'A ray bends toward the normal at the first glass surface and away from it at the second. Normal dispersion makes violet deviate more than red.',
  'rutherford':'Repulsive Coulomb force acts along the nucleus–alpha separation. The trajectory bends away from the nucleus; closer approaches produce larger deflections.',
  'rectifier':'Conventional current can flow through the diode during forward conduction. Negative input half-cycles are blocked in this ideal model.',
  'logic-gates':'Inputs are binary values, not forces. The truth table lists every input pair; an output bubble means logical inversion.',
  'circuit':'Conventional current leaves the battery’s positive terminal and returns to its negative terminal. The resistance produces a voltage drop and dissipates power.',
  'rc-charge':'Charging current decreases as capacitor voltage rises. The capacitor’s electric field stores energy; no charge crosses its ideal insulating gap.',
  'motional-emf':'Magnetic forces separate charges along the moving rod. The induced current produces a force opposing the imposed motion, consistent with Lenz’s law.',
  'induction':'The induced emf opposes a change of magnetic flux. Reversing the magnet’s motion reverses the induced current at the same position.',
  'magnet':'Outside the magnet, B goes from north to south; inside it returns from south to north. Magnetic field lines form closed loops.',
  'solenoid':'The right-hand grip rule links current circulation to the axial magnetic field: curled fingers follow current, and the thumb gives the field inside.',
  'emwave':'Electric and magnetic fields are perpendicular to each other and to propagation. The direction of energy flow follows E × B.',
  'radiation-pressure':'Light transfers momentum to a surface. Perfect reflection reverses the normal photon momentum and doubles the force relative to absorption.'
 };
 return{kind:'relationship',title:'Live values and the physics behind them',note:notes[id]||s.observe,formula:s.formula,scale:'Values follow the same parameters and time as the main experiment.'};
}
function vectorPlot(c,profile,cx,cy,vectors,max,compact=false){
 const colours=[C.blue,C.gold,C.mint,C.red,C.purple,C.white];
 line(c,cx-98,cy,cx+98,cy,C.line,1,[3,5]);line(c,cx,cy-100,cx,cy+100,C.line,1,[3,5]);
 for(let i=0;i<vectors.length;i++){let v=vectors[i],mag=Math.hypot(v.x,v.y),den=profile.separate?Math.max(mag,1e-12):max,scale=(compact?72:90)/Math.max(den,1e-12),x=cx+v.x*scale,y=cy-v.y*scale,col=colours[i%colours.length];if(mag>1e-10)arrow(c,cx,cy,x,y,col,3);}
 dot(c,cx,cy,13,C.white);
 if(!compact)text(c,profile.body||'BODY',cx,cy+125,C.muted,13,'center');
}
function drawProfile(c,data,s,p,t){
 c.clearRect(0,0,640,330);let bg=c.createLinearGradient(0,0,640,330);bg.addColorStop(0,'#0a1d2d');bg.addColorStop(1,'#081624');c.fillStyle=bg;c.fillRect(0,0,640,330);for(let x=20;x<640;x+=30)line(c,x,0,x,330,'#1d354755',1);for(let y=20;y<330;y+=30)line(c,0,y,640,y,'#1d354755',1);
 if(data.kind==='vectors'||data.kind==='flight'){
  let vs=data.vectors,max=Math.max(...vs.map(v=>Math.hypot(v.x,v.y)),1e-9);vectorPlot(c,data,170,151,vs,max);
  let y=46;vs.forEach((v,i)=>{let colour=[C.blue,C.gold,C.mint,C.red,C.purple,C.white][i%6],m=Math.hypot(v.x,v.y);text(c,`${v.label}: ${v.value||F(m,m<.01?4:2)}${v.unit?' '+v.unit:''}`,324,y,colour,17);y+=32});
  if(data.velocity){let [vx,vy]=data.velocity;arrow(c,452,246,452+vx*2.6,246,C.mint,2);arrow(c,452,246,452,246-vy*2.6,C.gold,2);text(c,'velocity components',350,297,C.muted,13)}
  text(c,'+y ↑    +x →',35,305,C.muted,13);
 }else if(data.kind==='pair'){
  let max=Math.max(...data.bodies.flatMap(b=>b.vectors.map(v=>Math.hypot(v.x,v.y))),1e-9);data.bodies.forEach((b,i)=>{let x=170+300*i;vectorPlot(c,data,x,150,b.vectors,max,true);text(c,b.name,x, 30,C.white,15,'center');b.vectors.forEach((v,j)=>text(c,`${v.label} = ${v.value||F(Math.hypot(v.x,v.y))} ${v.unit}`,x,268+j*25,j?C.gold:C.blue,15,'center'))});
 }else if(data.kind==='dipole'){
  let a=data.angle*Math.PI/180,dx=82*Math.cos(a),dy=-82*Math.sin(a);line(c,310-dx,168-dy,310+dx,168+dy,C.white,3);dot(c,310-dx,168-dy,15,C.blue);dot(c,310+dx,168+dy,15,C.gold);arrow(c,310-dx-18,168-dy,310-dx-88,168-dy,C.blue,3);arrow(c,310+dx+18,168+dy,310+dx+88,168+dy,C.gold,3);text(c,'−q',310-dx,202-dy,C.blue,16,'center');text(c,'+q',310+dx,202+dy,C.gold,16,'center');text(c,`Each force: ${F(data.v)} nN`,32, 30,C.mint,18);text(c,'Uniform E →',425,35,C.muted,15);
 }else if(data.kind==='bars'){
  let max=Math.max(...data.bars.map(b=>Math.abs(b[1])),1e-9),signed=data.bars.some(b=>b[1]<0),origin=signed?345:212,W=signed?170:360;data.bars.forEach((b,i)=>{let y=66+i*84,col=[C.mint,C.gold,C.blue][i%3],width=b[1]/max*W;text(c,b[0],28,y-18,C.muted,15);rr(c,origin,y-7,Math.max(1,Math.abs(width)),22,'#102638',C.line,2);rr(c,width<0?origin+width:origin,y-7,Math.abs(width),22,col,null,2);text(c,`${F(b[1],2)} ${b[2]}`,607,y+37,col,17,'right');if(signed)line(c,origin,y-13,origin,y+20,C.white,1)});
 }else{
  text(c,'KEY RELATION', 30,35,C.mint,13);wrap(c,s.formula,30,76,575,23,C.gold);line(c,30,123,610,123,C.line,1);let controls=s.controls.slice(0,3);controls.forEach((control,i)=>{let value=p[control.key],display=control.options?control.options.find(([v])=>v===value)?.[1]:`${Number(value).toFixed(control.digits||0)} ${control.unit||''}`;text(c,control.label,30,159+i*47,C.muted,14);text(c,display,606,159+i*47,C.white,17,'right')});
 }
}
const wonders=[
 {id:'elevator-weight',values:{mass:60,acceleration:-9.8},title:'A scale that reads zero',question:'The passenger still has mass and gravity still acts. Why does the scale read zero?',answer:'In free fall, the passenger and elevator accelerate together at g. The floor no longer needs to push on the passenger, so N = 0. The scale measures N, not gravity.'},
 {id:'beats',values:{f1:4,f2:4.2,amplitude:1},title:'Hear the invisible difference',question:'Two steady waves produce a slow pulse. What sets the time between loudness maxima?',answer:'The waves drift in and out of phase. At the starting values, their frequency difference is 0.2 Hz, so beats repeat every 5 seconds. Turn on Sound to hear the same beat rate on an audible carrier.'},
 {id:'vector-addition',values:{a:5,b:5,angle:180},title:'Two large vectors, zero resultant',question:'Both arrows have length 5. How can their sum have no magnitude or direction?',answer:'Equal opposite vectors cancel component by component. A zero vector has zero magnitude, and its direction is undefined.'},
 {id:'velocity-selector',values:{electric:300,field:1,speed:3},title:'Two forces make a straight line',question:'The proton feels two forces. Why does it travel straight through the plates?',answer:'At v = E/B, the upward electric force and downward magnetic force have equal magnitudes. Their vector sum is zero. Change the speed to break the balance.'},
 {id:'adiabatic',values:{ratio:.5,temperature:300,gamma:'1.4'},title:'Hotter without adding heat',question:'The gas gets hotter during compression, but Q = 0. Where did its extra energy come from?',answer:'The piston does work on the gas. That increases internal energy and temperature. Heat and work are different ways to transfer energy.'},
 {id:'thin-film',values:{thickness:180,index:1.5,wavelength:540},title:'A film that cancels its reflection',question:'Light reflects at each surface. How can the total reflected intensity be zero?',answer:'At this thickness, the reflected contributions cancel. Reflection phase matters as well as optical path. Change thickness to 90 nm and compare.'},
 {id:'dipole-torque',values:{charge:3,separation:6,field:500,angle:90},title:'Zero net force, maximum torque',question:'The electric forces cancel. What still makes this dipole want to rotate?',answer:'The forces act at different points and form a couple. Net force is zero, but at 90° the turning effect pE is maximal.'},
 {id:'kepler',values:{axis:1.4,eccentricity:.7},title:'Fast near the Sun, slow far away',question:'The planet changes its speed continuously. What remains constant about its motion?',answer:'The line joining planet and Sun sweeps equal areas in equal times. The shaded region shows a fixed time interval; its changing shape reveals Kepler’s second law.'},
 {id:'wheatstone',values:{p:20,q:40,r:30,s:60},title:'A wire with no current',question:'This bridge contains a conducting detector path. Why is its current zero?',answer:'Both midpoints have equal potential because P/Q = R/S. With no potential difference across the galvanometer, no current flows through it.'},
 {id:'alpha-recoil',values:{mass:220,energy:6},title:'Same momentum, very different energy',question:'The two products have equal momentum magnitudes. Why does the alpha particle take almost all the energy?',answer:'At equal momentum, non-relativistic kinetic energy is p²/(2m). The alpha particle is much lighter, so at these starting values it carries about 98.2% of the released energy.'},
 {id:'zener-regulator',values:{input:6,series:1000,load:500,zener:5.1},title:'When a regulator stops regulating',question:'The diode is labelled 5.1 V. Why is the output lower than 5.1 V?',answer:'The circuit cannot supply enough current to reach Zener breakdown. The diode is off, and the output follows the resistor divider. Reduce the series resistance to recover regulation.'},
 {id:'compton',values:{wavelength:12,angle:180},title:'A photon gives an electron a kick',question:'After back-scattering, what happened to the photon’s missing energy?',answer:'The recoil electron carries it as kinetic energy. Energy and momentum are conserved; the scattered photon has a lower energy and a longer wavelength.'}
];
const audio={enabled:false,ctx:null,voices:[],volume:.25,lastChime:0,
 async enable(){const A=window.AudioContext||window.webkitAudioContext;if(!A)throw Error('Audio unavailable');if(!this.ctx){this.ctx=new A();this.master=this.ctx.createGain();this.master.gain.value=0;this.master.connect(this.ctx.destination);for(let i=0;i<2;i++){let o=this.ctx.createOscillator(),gain=this.ctx.createGain();o.type='sine';gain.gain.value=0;o.connect(gain);gain.connect(this.master);o.start();this.voices.push({o,gain})}}await this.ctx.resume();this.enabled=true;},
 update(s,p,t,playing){if(!this.ctx)return;let active=this.enabled&&playing&&!document.hidden,levels=[0,0],freq=[220,220],caption='Gentle control sounds';if(s.id==='beats'){freq=[216+p.f1,216+p.f2];levels=[p.amplitude/1.5*.36,p.amplitude/1.5*.36];caption='Audible carrier shifted; beat rate unchanged'}else if(s.id==='driven-resonance'){freq=[196+55*p.frequency,220];levels=[Math.min(.3,window.FourthModels.resonance(p).A*.6)*(Math.abs(Math.sin(TAU*p.frequency*t))*.7+.3),0];caption='Gentle guide tone follows the oscillation'}else if(s.id==='pendulum'){let w=Math.sqrt(g/p.length);freq=[392,220];levels=[Math.abs(Math.sin(w*t))**10*.24,0];caption='A soft tone marks centre crossings'}this.master.gain.setTargetAtTime(this.enabled&&!document.hidden?this.volume*.14:0,this.ctx.currentTime,.045);this.voices.forEach((v,i)=>{v.o.frequency.setTargetAtTime(freq[i],this.ctx.currentTime,.07);v.gain.gain.setTargetAtTime(active?levels[i]:0,this.ctx.currentTime,.06)});return caption;},
 chime(special=false){if(!this.enabled||!this.ctx||document.hidden)return;let now=this.ctx.currentTime;if(now-this.lastChime<.12)return;this.lastChime=now;for(let [i,f] of (special?[392,493.88,587.33]:[440]).entries()){let o=this.ctx.createOscillator(),v=this.ctx.createGain(),start=now+i*.09;o.type='sine';o.frequency.value=f;v.gain.setValueAtTime(0,start);v.gain.linearRampToValueAtTime(.22,start+.018);v.gain.exponentialRampToValueAtTime(.001,start+.25);o.connect(v);v.connect(this.master);o.start(start);o.stop(start+.28);o.onended=()=>{o.disconnect();v.disconnect()}}}
};
let api,lens=false,context,lastWonder=-1,activeWonder=null;
const $=id=>document.getElementById(id);
function setLens(on){lens=on;$('physics-toggle').setAttribute('aria-pressed',String(on));$('physics-toggle').textContent=on?'Hide physics':'Show physics';$('physics-panel').hidden=!on;try{localStorage.setItem('physica-lens',String(on))}catch{}if(api)update();}
function update(){if(!api)return;const {current:s,params:p,time:t,playing}=api.state();const caption=audio.update(s,p,t,playing);if(caption)$('sound-caption').textContent=caption;if(!lens)return;let data=profile(s,p,t);$('physics-title').textContent=data.title;$('physics-canvas').setAttribute('aria-label',data.title+'. '+data.note);$('physics-note').textContent=data.note;$('physics-scale').textContent=data.scale;const holder=$('physics-values'),metrics=s.metrics(p,t);while(holder.children.length>metrics.length)holder.lastElementChild.remove();metrics.forEach((m,i)=>{let row=holder.children[i];if(!row){row=document.createElement('div');row.className='lens-value';let key=document.createElement('span'),value=document.createElement('strong');row.append(key,value);holder.append(row)}row.children[0].textContent=m.label;row.children[1].textContent=m.value});draw();}
function draw(){if(!api||!lens)return;const {current:s,params:p,time:t}=api.state(),data=profile(s,p,t),c=$('physics-canvas');if(!context){context=c.getContext('2d');if(!context)return;c.width=1280;c.height=660;context.setTransform(2,0,0,2,0,0)}drawProfile(window.PhysicaTheme.wrapContext(context),data,s,p,t);}

function clearWonder(){activeWonder=null;$('wonder-card').hidden=true;}
function surprise(){let choices=wonders.map((_,i)=>i).filter(i=>i!==lastWonder),index=choices[Math.floor(Math.random()*choices.length)],w=wonders[index];lastWonder=index;api.open(w.id,w.values);activeWonder=w;$('wonder-title').textContent=w.title;$('wonder-question').textContent=w.question;$('wonder-answer').textContent=w.answer;$('wonder-answer').hidden=true;$('wonder-reveal').hidden=false;$('wonder-reveal').setAttribute('aria-expanded','false');$('wonder-card').hidden=false;audio.chime(true);$('wonder-title').focus({preventScroll:true});$('wonder-card').scrollIntoView({behavior:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}
window.PhysicaExperience={profile,drawProfile,wonders,update,draw,onSelect:clearWonder,
 init(app){api=app;try{lens=localStorage.getItem('physica-lens')==='true';let v=Number(localStorage.getItem('physica-volume'));if(localStorage.getItem('physica-volume')!==null&&v>=0&&v<=50)audio.volume=v/100}catch{}$('volume').value=audio.volume*100;setLens(lens);$('physics-toggle').addEventListener('click',()=>{setLens(!lens);if(lens)$('physics-panel').scrollIntoView({behavior:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'})});$('sound-toggle').addEventListener('click',async()=>{const b=$('sound-toggle');b.disabled=true;try{if(audio.enabled)audio.enabled=false;else await audio.enable();b.setAttribute('aria-pressed',String(audio.enabled));b.textContent=audio.enabled?'Sound on':'Sound off';$('volume-wrap').hidden=!audio.enabled;$('sound-caption').hidden=!audio.enabled;update();audio.chime()}catch{$('sound-caption').hidden=false;$('sound-caption').textContent='Sound is unavailable in this browser.'}finally{b.disabled=false}});$('volume').addEventListener('input',()=>{audio.volume=Number($('volume').value)/100;try{localStorage.setItem('physica-volume',$('volume').value)}catch{}update()});$('wonder-reveal').addEventListener('click',()=>{$('wonder-answer').hidden=false;$('wonder-reveal').hidden=true;$('wonder-reveal').setAttribute('aria-expanded','true');setLens(true);audio.chime()});$('wonder-close').addEventListener('click',clearWonder);$('controls').addEventListener('change',()=>audio.chime());document.addEventListener('visibilitychange',update);window.addEventListener('physica-theme-change',update);window.addEventListener('pagehide',()=>{audio.enabled=false;audio.ctx?.suspend()});update();}
};
})();
