/* Rank mode · NEET Physics: Samjho lessons (original content). One concise lesson per topic:
   idea → formula with its conditions → one explained example → one partly completed example → three checks
   (predict / first step / changed condition). Pilot chapter: Motion in a Straight Line. Every number was computed and asserted.
   Lesson shape: {title, idea:[..], fig?, trap, rules:[[label, text]], valid:[..], invalid:[..],
   example:{q, fig?, steps:[[label, text]], ans}, partial:{q, fig?, steps:[[label, text]], ask:{p, o, c, why}, ans},
   checks:[{k:'predict'|'first'|'change', q, o:[4], c, s}]} */
(() => {
'use strict';
const L={};
L['Motion in a Straight Line']={
kin:{title:'Displacement, speed and velocity',
 idea:['Distance is the length of the path travelled; it is a scalar and never decreases. Displacement is the change in position, from start to finish in a straight line; it has a direction.',
  'Average speed = total distance ÷ total time. Average velocity = displacement ÷ total time. They are equal only when the body moves in a straight line without turning back.'],
 trap:'A runner who finishes a full lap has covered a large distance but her displacement, and so her average velocity, is zero.',
 rules:[['Average speed','total distance ÷ total time (always)'],['Equal TIMES at v₁ and v₂','average speed = (v₁ + v₂) ÷ 2'],['Equal DISTANCES at v₁ and v₂','average speed = 2v₁v₂ ÷ (v₁ + v₂)']],
 valid:['Equal distances at 30 and 60 km/h → 2×30×60 ÷ 90 = 40 km/h.','Equal times at 30 and 60 km/h → (30 + 60) ÷ 2 = 45 km/h.'],
 invalid:['Writing (30 + 60) ÷ 2 for equal distances: that is the equal-time result, so 45 km/h is wrong there.'],
 example:{q:'A person walks 3 m east and then 4 m north in 5 s. Find the distance, displacement, average speed and the magnitude of average velocity.',
  steps:[['Target','Four quantities: distance, displacement, average speed, average velocity.'],['Given','Two perpendicular legs of 3 m and 4 m; total time 5 s.'],['Choose','Distance is the sum of the legs. Displacement is the straight line from start to end, so use Pythagoras.'],['Compute','Distance = 3 + 4 = 7 m. Displacement = √(3² + 4²) = 5 m. Speed = 7 ÷ 5 = 1.4 m/s. Velocity = 5 ÷ 5 = 1 m/s.'],['Check','Average speed (1.4) is larger than the magnitude of average velocity (1) because the path turned.']],ans:'7 m, 5 m, 1.4 m/s, 1 m/s'},
 partial:{q:'A car covers the first half of a distance at 40 km/h and the second half at 60 km/h. Find the average speed.',
  steps:[['Target','Average speed over the whole journey.'],['Given','Equal distances, so let each half be d. Total distance = 2d.'],['Choose','Start from total distance ÷ total time. Do not average the two speeds.']],
  ask:{p:'The total time for the two halves is',o:['d/50','d/24','d/100','d/20'],c:1,why:'t = d/40 + d/60 = 3d/120 + 2d/120 = 5d/120 = d/24.'},ans:'Average speed = 2d ÷ (d/24) = 48 km/h.'},
 checks:[{k:'predict',q:'A runner completes one full lap of a circular track in 40 s. Her average velocity over the lap is',o:['zero','equal to her average speed','circumference ÷ 40','radius ÷ 40'],c:0,s:'The start and end points are the same, so the displacement is zero.'},
  {k:'first',q:'A bus travels equal distances at 20 km/h and 30 km/h. The first thing to write to find the average speed is',o:['(20 + 30) ÷ 2','total distance and total time','20 × 30','30 − 20'],c:1,s:'Average speed always starts from total distance ÷ total time.'},
  {k:'change',q:'Now the bus travels for equal TIMES at 20 km/h and 30 km/h. The average speed is',o:['24 km/h','25 km/h','50 km/h','10 km/h'],c:1,s:'For equal times the average speed is the simple mean: (20 + 30) ÷ 2 = 25 km/h. (For equal distances it would be 24 km/h.)'}]},
eq:{title:'Equations of motion',
 idea:['For motion in a straight line with constant acceleration, five quantities are linked: u (initial velocity), v (final velocity), a, t and s.',
  'Pick the relation by asking which quantity is neither given nor wanted. That quantity decides the equation.'],
 trap:'These equations are valid only while the acceleration is constant. If a changes with time, they cannot be used.',
 rules:[['No s involved','v = u + at'],['No v involved','s = ut + ½at²'],['No t involved','v² = u² + 2as'],['Sign rule','choose a positive direction first; a is negative if it opposes it']],
 valid:['A car brakes uniformly: a is constant, so v² = u² + 2as is valid.'],
 invalid:['A body with acceleration a = 2t (growing with time): constant-acceleration equations do not apply.'],
 example:{q:'A car moving at 20 m/s brakes with a constant deceleration of 5 m/s² and stops. Find the stopping distance.',
  steps:[['Target','Distance s.'],['Given','u = 20 m/s, v = 0, a = −5 m/s² (forward taken as positive). Time is not given and not asked.'],['Choose','The missing quantity is t, so use v² = u² + 2as.'],['Compute','0 = 20² + 2(−5)s, so 10s = 400 and s = 40 m.'],['Check','Time = 20 ÷ 5 = 4 s. Then s = 20(4) − ½(5)(16) = 40 m, the same.']],ans:'40 m'},
 partial:{q:'A train starts from rest and accelerates uniformly at 0.5 m/s² for 20 s. Find the distance covered.',
  steps:[['Target','Distance s.'],['Given','u = 0, a = 0.5 m/s², t = 20 s. The final speed is not given.']],
  ask:{p:'Which relation avoids the unknown final speed?',o:['v = u + at','s = ut + ½at²','v² = u² + 2as','s = (u + v)t ÷ 2'],c:1,why:'Only s = ut + ½at² contains s, u, a and t without v.'},ans:'s = 0 + ½(0.5)(20²) = 100 m.'},
 checks:[{k:'predict',q:'A car braking with a constant deceleration stops in 20 m from speed v. From speed 2v, with the same deceleration, it stops in',o:['40 m','80 m','60 m','20 m'],c:1,s:'From v² = 2as, the distance is proportional to v². Doubling v gives four times the distance: 80 m.'},
  {k:'first',q:'A bike speeds up from 10 m/s to 20 m/s over 150 m. To find its acceleration, the best first relation is',o:['v = u + at','v² = u² + 2as','s = ut + ½at²','s = vt'],c:1,s:'t is neither given nor asked, so use v² = u² + 2as: a = (400 − 100) ÷ 300 = 1 m/s².'},
  {k:'change',q:'A body starts from rest with acceleration a = 2t (it increases with time). Can v² = u² + 2as be used?',o:['Yes, always','No, the acceleration is not constant','Yes, if t is small','Only to find s'],c:1,s:'The equation assumes constant acceleration, which is not the case here.'}]},
grav:{title:'Free fall and vertical motion',
 idea:['Ignoring air, every body moving freely near the Earth has the same downward acceleration g, whether it is going up, at the top or coming down. Use g = 10 m/s² unless the question gives 9.8 m/s².',
  'At the highest point the velocity is zero for an instant, but the acceleration is still g downward.'],
 trap:'“Velocity zero at the top, so acceleration zero” is wrong. If the acceleration were zero, the ball would stay there.',
 rules:[['Upward positive','a = −g during the whole flight'],['Time to the top','t = u ÷ g'],['Maximum height','H = u² ÷ 2g'],['Back at the starting level','speed = u (directed downward)']],
 valid:['Ball thrown up at 20 m/s: H = 400 ÷ 20 = 20 m, time up = 2 s, total flight = 4 s.'],
 invalid:['A feather or a parachutist: air drag is not negligible, so a ≠ g.'],
 example:{q:'A ball is thrown vertically upward at 20 m/s (g = 10 m/s²). Find the maximum height, the time to reach it and the total time of flight.',
  steps:[['Target','H, time up, total time.'],['Given','u = 20 m/s upward, a = −10 m/s², v = 0 at the top.'],['Choose','At the top v = 0. For height, time is not needed: v² = u² + 2as. For time, v = u + at.'],['Compute','0 = 400 − 20H, so H = 20 m. 0 = 20 − 10t, so t = 2 s. The way down takes the same time, so the total is 4 s.'],['Check','Total time by s = 0: 0 = 20t − 5t², so t = 4 s. ✓']],ans:'20 m, 2 s, 4 s'},
 partial:{q:'A stone is dropped from rest from a height of 45 m (g = 10 m/s²). Find the time to reach the ground and its speed on landing.',
  steps:[['Target','Time t and landing speed v.'],['Given','u = 0, s = 45 m, a = g = 10 m/s². Take downward as positive.']],
  ask:{p:'Which equation gives the time?',o:['45 = ½ × 10 × t²','45 = 10t','45 = −½ × 10 × t²','45 = 20t'],c:0,why:'s = ut + ½at² with u = 0 gives 45 = 5t². The sign is positive because downward is positive.'},ans:'t = 3 s, and v = gt = 30 m/s.'},
 checks:[{k:'predict',q:'At the highest point of a ball thrown upward, its velocity and acceleration are',o:['zero and g downward','zero and zero','g and zero','zero and g upward'],c:0,s:'Velocity is momentarily zero; the acceleration is g downward all the time.'},
  {k:'first',q:'A ball is thrown up at 25 m/s (g = 10 m/s²). To find the time to reach the top, which condition do you use?',o:['v = 0 at the top','s = 0 at the top','a = 0 at the top','u = 0 at the top'],c:0,s:'At the top v = 0, so 0 = 25 − 10t and t = 2.5 s.'},
  {k:'change',q:'Stone A is dropped and stone B is thrown downward with speed 10 m/s, both from the same height (no air). Which reaches the ground first?',o:['A','B','Both together','It depends on the mass'],c:1,s:'B starts with a downward speed and the same acceleration, so it covers the height sooner.'}]},
graph:{title:'Motion graphs',
 idea:['Read the axes first. On an x–t graph the slope is velocity. On a v–t graph the slope is acceleration and the area between the graph and the time axis is displacement.',
  'Area below the time axis counts as negative displacement.'],
 trap:'The height of a graph is not its slope. A high x–t graph can have zero velocity (a flat line); a steep one has large velocity.',
 rules:[['x–t graph','slope = velocity; straight line = constant velocity'],['v–t graph','slope = acceleration; area = displacement'],['a–t graph','area = change in velocity'],['Sign','area below the axis is negative, so total area gives displacement, not distance']],
 valid:['A v–t graph that is a straight sloping line: constant acceleration, and the area is a triangle or trapezoid.'],
 invalid:['Using the area under a v–t graph as distance when the velocity changes sign: you must add the magnitudes of the areas.'],
 example:{q:'The v–t graph shown rises from 0 to 10 m/s in 4 s, stays at 10 m/s for 6 s and falls to 0 in 2 s. Find the displacement and the acceleration in the first 4 s.',
  fig:{w:240,h:150,alt:'Velocity-time graph: rises to 10 metres per second at 4 seconds, flat until 10 seconds, falls to zero at 12 seconds',d:[['l',30,125,30,12,'a'],['l',30,125,228,125,'a'],['p','M30 125 L86 45 L170 45 L198 125','B'],['l',86,45,86,125,'d'],['l',170,45,170,125,'d'],['t',34,16,'v (m/s)','s'],['t',222,138,'t (s)','es'],['t',12,49,'10','s'],['t',86,138,'4','ms'],['t',170,138,'10','ms'],['t',198,138,'12','ms'],['t',30,138,'0','ms']]},
  steps:[['Target','Displacement = area under the graph; acceleration = slope of the first part.'],['Given','Three parts: a rising triangle (4 s), a rectangle (6 s) and a falling triangle (2 s).'],['Choose','Split into simple shapes and add their areas.'],['Compute','Area = ½(4)(10) + (6)(10) + ½(2)(10) = 20 + 60 + 10 = 90 m. Slope = 10 ÷ 4 = 2.5 m/s².'],['Check','All the velocities are positive, so displacement equals distance: 90 m.']],ans:'90 m, 2.5 m/s²'},
 partial:{q:'A v–t graph is a straight line from 4 m/s at t = 0 to 16 m/s at t = 6 s. Find the displacement in 6 s and the acceleration.',
  steps:[['Target','Displacement (area) and acceleration (slope).'],['Given','v₁ = 4 m/s, v₂ = 16 m/s, duration 6 s.']],
  ask:{p:'What shape is the area under this graph?',o:['a triangle','a trapezoid','a rectangle','a semicircle'],c:1,why:'The graph does not start at zero, so the area is a trapezoid with parallel sides 4 and 16.'},ans:'Area = ½(4 + 16)(6) = 60 m; slope = (16 − 4) ÷ 6 = 2 m/s².'},
 checks:[{k:'predict',q:'On a position–time graph, a straight line sloping upward means',o:['constant positive velocity','constant acceleration','zero velocity','increasing velocity'],c:0,s:'A constant slope on an x–t graph is a constant velocity.'},
  {k:'first',q:'You are given a v–t graph and asked for the displacement. The first thing to compute is',o:['the slope','the signed area under the graph','the final velocity only','the maximum velocity'],c:1,s:'Displacement is the area between the graph and the time axis, with sign.'},
  {k:'change',q:'A body moves at +10 m/s for 4 s and then at −10 m/s for 4 s. Its displacement is',o:['0','80 m','40 m','−40 m'],c:0,s:'The areas are +40 m and −40 m, so the displacement is zero. (The distance is 80 m.)'}]},
rel:{title:'Relative velocity',
 idea:['The velocity of A relative to B is what an observer sitting on B sees: v(A rel B) = v(A) − v(B), with signs along the line.',
  'Bodies moving the same way have a small relative speed; bodies moving towards each other have a large one.'],
 trap:'Do not add speeds blindly. Same direction: subtract. Opposite directions: add the magnitudes.',
 rules:[['Same direction','relative speed = difference of speeds'],['Opposite directions (towards or away)','relative speed = sum of speeds'],['Time to meet or catch up','time = initial gap ÷ relative speed'],['Frame','both velocities must be measured from the same frame (usually the ground)']],
 valid:['Cars at 60 and 80 km/h in the same direction: the passenger in the slower car sees the faster car at 20 km/h.'],
 invalid:['Using the gap ÷ relative speed formula when one body accelerates: the relative speed is no longer constant.'],
 example:{q:'Train B moves at 30 m/s and train A at 20 m/s in the same direction on parallel tracks. B is 250 m behind A. When does B catch up with A?',
  steps:[['Target','Time for the gap to close.'],['Given','Same direction, gap 250 m, speeds 30 and 20 m/s.'],['Choose','Sit on A: B approaches at 30 − 20 = 10 m/s.'],['Compute','t = 250 ÷ 10 = 25 s.'],['Check','In 25 s, B travels 750 m and A travels 500 m; the difference is 250 m. ✓']],ans:'25 s'},
 partial:{q:'Two cars approach each other on a straight road at 15 m/s and 25 m/s. They are 400 m apart. When do they meet?',
  steps:[['Target','Time to meet.'],['Given','Opposite directions, gap 400 m.']],
  ask:{p:'The relative speed of approach is',o:['10 m/s','40 m/s','20 m/s','375 m/s'],c:1,why:'They move towards each other, so the speeds add: 15 + 25 = 40 m/s.'},ans:'t = 400 ÷ 40 = 10 s.'},
 checks:[{k:'predict',q:'Two cars move the same way at 60 km/h and 80 km/h. A passenger in the slower car sees the faster car move at',o:['20 km/h','140 km/h','80 km/h','60 km/h'],c:0,s:'Same direction: 80 − 60 = 20 km/h.'},
  {k:'first',q:'To find when two bodies on a line meet, the first step is',o:['to find their relative velocity and the initial separation','to always add their speeds','to use the larger speed','to average the speeds'],c:0,s:'Time = separation ÷ relative speed; the relative speed depends on the directions.'},
  {k:'change',q:'A is 300 m behind B. A moves at 10 m/s and B moves away at 20 m/s in the same direction. Will A ever catch B?',o:['Yes, after 10 s','No; the gap keeps growing','Yes, after 30 s','Yes, after 15 s'],c:1,s:'B is faster, so the gap grows at 10 m/s. A never catches up.'}]}
};
window.PhysicaRankLessons=L;
})();
