/* Rank mode · NEET Physics · Units and Measurements: formulas with how to apply them, short notes, most asked question types.
   Original notes. Every number in an example was computed before writing. */
(() => {
'use strict';
window.PhysicaRankUnits={
chapter:'Units and Measurements',
table:[['Velocity','LT⁻¹'],['Acceleration','LT⁻²'],['Momentum, impulse','MLT⁻¹'],['Force, weight','MLT⁻²'],['Work, energy, torque','ML²T⁻²'],['Power','ML²T⁻³'],['Pressure, stress, Young’s modulus','ML⁻¹T⁻²'],['Density','ML⁻³'],['Frequency, angular velocity','T⁻¹'],['Angular momentum, Planck’s constant h','ML²T⁻¹'],['Surface tension','MT⁻²'],['Viscosity (coefficient η)','ML⁻¹T⁻¹'],['Gravitational constant G','M⁻¹L³T⁻²'],['Specific heat','L²T⁻²K⁻¹'],['Gas constant R (per mole)','ML²T⁻²K⁻¹mol⁻¹'],['Boltzmann constant k','ML²T⁻²K⁻¹'],['Charge','AT'],['Potential difference','ML²T⁻³A⁻¹'],['Resistance','ML²T⁻³A⁻²'],['Capacitance','M⁻¹L⁻²T⁴A²'],['Inductance','ML²T⁻²A⁻²'],['Magnetic field B','MT⁻²A⁻¹'],['Permittivity ε₀','M⁻¹L⁻³T⁴A²']],
formulas:[
 {n:'Principle of homogeneity',f:'Every term in an equation must have the same dimensions',how:'Write the dimensions of each term. If one term is different, the equation is wrong. You can add or subtract only quantities of the same dimension.',ex:'v = u + at → [LT⁻¹] = [LT⁻¹] + [LT⁻²][T]. Every term is LT⁻¹, so it is correct.'},
 {n:'Dimensions of a quantity',f:'[X] = dimensions of the right-hand side of a formula for X',how:'Pick any formula that contains X. Put M, L, T for each symbol and cancel.',ex:'η = F ÷ (6πrv) → [MLT⁻²] ÷ ([L][LT⁻¹]) = [ML⁻¹T⁻¹].'},
 {n:'Deriving a relation',f:'Q = k · aˣ bʸ cᶻ, then match the powers of M, L, T',how:'Assume Q is a product of powers of the quantities it depends on. Equate the powers of M, L and T on both sides and solve for x, y, z. The constant k stays unknown.',ex:'T = k lˣ gʸ → T¹ = Lˣ(LT⁻²)ʸ. So x + y = 0 and −2y = 1. Then y = −½, x = ½, so T = k√(l/g).'},
 {n:'Limits of dimensional analysis',f:'Cannot give pure numbers such as ½, 2π or k',how:'It also fails for sin, log and eˣ (their argument must be dimensionless), cannot tell apart quantities with the same dimensions (work and torque), and gives only a product of powers.',ex:'From dimensions alone you cannot decide whether K.E. is mv² or ½mv².'},
 {n:'Unit conversion',f:'n₂ = n₁ [M₁/M₂]ᵃ [L₁/L₂]ᵇ [T₁/T₂]ᶜ',how:'The quantity has dimensions [MᵃLᵇTᶜ]. The bigger the new unit, the smaller the number. Put the old unit on top of the new one.',ex:'Force [MLT⁻²]: 1 N = 1 × (1000 g ÷ 1 g)(100 cm ÷ 1 cm)(1 s ÷ 1 s)⁻² = 10⁵ dyne.'},
 {n:'Counting significant figures',f:'Non-zero digits count · zeros between digits count · trailing zeros after a decimal point count · leading zeros never count',how:'Write the number in scientific notation. The digits in front of ×10ⁿ are the significant figures.',ex:'0.00230 → 3 · 4.500 → 4 · 2005 → 4 · 1.20 × 10³ → 3.'},
 {n:'Adding and subtracting',f:'The answer keeps the decimal places of the least precise number',how:'Add normally, then round to the fewest decimal places among the numbers.',ex:'12.11 + 0.3 + 1.457 = 13.867 → 13.9 (one decimal place, because of 0.3).'},
 {n:'Multiplying and dividing',f:'The answer keeps the significant figures of the least precise number',how:'Multiply or divide normally, then round to the smallest number of significant figures.',ex:'4.0 × 2.50 = 10.00 → 10 (2 significant figures, because of 4.0).'},
 {n:'Rounding off',f:'Dropped digit above 5: round up · below 5: keep · exactly 5: make the kept digit even',how:'Look only at the digit to be dropped. If it is exactly 5, the kept digit goes up when it is odd and stays when it is even.',ex:'2.735 → 2.74 (3 is odd, goes up) · 2.745 → 2.74 (4 is even, stays).'},
 {n:'Errors in repeated readings',f:'Mean ā = (a₁ + … + aₙ)/n · Δaᵢ = |ā − aᵢ| · Mean absolute error = Σ|Δaᵢ|/n · Relative error = Δā/ā · Percentage error = Relative × 100',how:'Find the mean, then each reading’s difference from the mean (always positive), then the mean of those differences.',ex:'Readings 2.63, 2.56, 2.42, 2.71, 2.80 s: mean = 2.62 s, mean absolute error = 0.11 s, percentage error ≈ 4%.'},
 {n:'Error in a sum or difference',f:'Z = A ± B  →  ΔZ = ΔA + ΔB',how:'Absolute errors always add, even for a difference.',ex:'(10.5 ± 0.1) + (26.8 ± 0.1) = 37.3 ± 0.2, and 26.8 − 10.5 = 16.3 ± 0.2.'},
 {n:'Error in a product, quotient or power',f:'Z = Aᵖ Bᵠ ÷ Cʳ  →  ΔZ/Z = p·ΔA/A + q·ΔB/B + r·ΔC/C',how:'Add the percentage errors, each multiplied by its power. Use the powers as positive numbers.',ex:'g = 4π²L/T²: %Δg = %ΔL + 2·%ΔT = 1 + 2 × 2 = 5% (L has 1% error, T has 2%).'},
 {n:'Vernier callipers',f:'LC = 1 MSD − 1 VSD = (1 MSD) ÷ N · Reading = MSR + (coinciding VSD) × LC',how:'Read the main scale just before the vernier zero (MSR). Find the vernier division that lines up with a main-scale mark. Then correct for zero error.',ex:'1 MSD = 1 mm, N = 10 → LC = 0.1 mm. MSR 24 mm, 6th division coincides → 24 + 6 × 0.1 = 24.6 mm.'},
 {n:'Screw gauge',f:'LC = pitch ÷ number of circular divisions · Reading = PSR + CSR × LC · Corrected = Reading − zero error',how:'PSR is the pitch-scale reading, CSR is the circular-scale division on the line. Subtract the zero error with its sign.',ex:'Pitch 1 mm, 100 divisions → LC = 0.01 mm. PSR 3 mm, CSR 35 → 3.35 mm. Zero error +0.02 mm → 3.33 mm.'},
 {n:'Spherometer',f:'R = l² ÷ 6h + h ÷ 2',how:'l is the distance between the outer legs and h is the height of the middle leg, found from the screw readings.',ex:'l = 4 cm, h = 0.1 cm → R = 16 ÷ 0.6 + 0.05 ≈ 26.7 cm.'},
 {n:'Same dimensions (very useful)',f:'Work = Energy = Torque · Pressure = Stress = Young’s modulus = Energy density · Impulse = Momentum · Frequency = Angular velocity = 1/time · Latent heat = Gravitational potential · RC = L/R = √(LC) = time · E/B = 1/√(μ₀ε₀) = velocity · h = Angular momentum',how:'If a question asks which pairs have the same dimensions, check these first.',ex:'Impulse = F·t = MLT⁻² · T = MLT⁻¹, the same as momentum.'},
 {n:'Handy values',f:'1 light-year = 9.46 × 10¹⁵ m · 1 parsec = 3.08 × 10¹⁶ m · 1 AU = 1.5 × 10¹¹ m · 1 Å = 10⁻¹⁰ m · 1 fermi = 10⁻¹⁵ m · 1 u = 1.66 × 10⁻²⁷ kg · 1 eV = 1.6 × 10⁻¹⁹ J · 1 atm = 1.013 × 10⁵ Pa · 1 cal = 4.186 J · 1 hp = 746 W · 1 litre = 10⁻³ m³ · 1 N = 10⁵ dyne · 1 J = 10⁷ erg',how:'Prefixes: tera 10¹², giga 10⁹, mega 10⁶, kilo 10³, milli 10⁻³, micro 10⁻⁶, nano 10⁻⁹, pico 10⁻¹², femto 10⁻¹⁵.',ex:''}
],
notes:[
 {h:'SI units',items:['Seven base units: metre (length), kilogram (mass), second (time), ampere (current), kelvin (temperature), mole (amount of substance), candela (luminous intensity).','Radian (plane angle) and steradian (solid angle) are dimensionless.','Derived units are built from base units: N = kg m s⁻², J = N m, W = J/s, Pa = N/m².','Prefixes change the size only: kilo 10³, milli 10⁻³, micro 10⁻⁶, nano 10⁻⁹.']},
 {h:'Dimensions',items:['Dimensionless: angle, strain, refractive index, relative density, Poisson’s ratio, any ratio of like quantities, and π.','The argument of sin, cos, log and exp must be dimensionless.','Only quantities with the same dimensions can be added, subtracted or equated.','Use dimensions to check a formula, to find a relation, and to convert units. Not to find numbers like ½ or 2π.']},
 {h:'Measurement and errors',items:['Least count is the smallest value an instrument can measure. A smaller least count means a more precise instrument.','Accuracy is closeness to the true value. Precision is how close repeated readings are to each other.','Systematic errors (zero error, faulty instrument, personal bias) push every reading the same way. Random errors scatter the readings both ways. Gross errors are blunders.','Taking many readings reduces random error. Zero error must be corrected for.','Absolute error is in the unit of the quantity. Relative and percentage errors have no unit.']},
 {h:'Significant figures',items:['More significant figures means a more precise measurement.','Changing the unit does not change the number of significant figures. Write 2.5 m as 2.5 × 10² cm, not 250 cm.','Exact numbers (the 2 in 2πr, or a count of objects) have unlimited significant figures.','In a multi-step calculation, round only at the end.']}
],
asked:[
 {t:'Find the dimensions of a quantity',what:'“What are the dimensions of …?” asked for η, G, h, R, ε₀, B, surface tension and similar.',steps:['Write a formula that contains the quantity.','Put the dimensions of every other symbol.','Cancel and write the powers of M, L, T.'],ex:'Dimensions of pressure ÷ density: ML⁻¹T⁻² ÷ ML⁻³ = L²T⁻².',tp:'dims'},
 {t:'Is the equation dimensionally correct?',what:'A formula is given, and you must say whether it can be correct, or find the missing power.',steps:['Find the dimensions of each term.','Terms added or equated must match.','Fix the powers until both sides agree.'],ex:'Wave speed on a string v = √(T/μ): T/μ = MLT⁻² ÷ ML⁻¹ = L²T⁻², so √(T/μ) = LT⁻¹, the dimensions of speed. Correct.',tp:'dims'},
 {t:'Which quantities have the same dimensions?',what:'“Which pair has the same dimensions?” or “which one is not a time?”',steps:['Convert each quantity to M, L, T.','Compare.','Remember the standard pairs (work and torque, impulse and momentum, RC and L/R).'],ex:'Impulse = F·t = MLT⁻² · T = MLT⁻¹. Momentum = MLT⁻¹. Same dimensions.',tp:'dims'},
 {t:'Percentage error',what:'A quantity depends on measured values and you are given their errors. Find the error in the result.',steps:['Write the formula with its powers.','Percentage error = sum of (power × percentage error of each quantity).','For a sum or difference, add the absolute errors instead.'],ex:'Z = A³B² ÷ C with errors 1%, 2% and 3%: 3(1) + 2(2) + 3 = 10%.',tp:'err'},
 {t:'Least count and instrument reading',what:'Find the least count, the reading, or the corrected reading of a vernier callipers or screw gauge.',steps:['Least count = smallest scale division ÷ number of divisions on the moving scale.','Reading = main-scale reading + coinciding division × least count.','Corrected reading = reading − zero error.'],ex:'Vernier: 1 MSD = 1 mm, 10 VSD. LC = 0.1 mm. MSR 24 mm, 6th division coincides → 24.6 mm.',tp:'inst'},
 {t:'Significant figures',what:'Count the significant figures, round off, or give the result of an addition or multiplication.',steps:['Count from the first non-zero digit.','Addition: keep the least number of decimal places.','Multiplication: keep the least number of significant figures.'],ex:'0.0450 has 3 significant figures: the leading zeros do not count and the last zero does. And 12.11 + 0.3 = 12.41 → 12.4.',tp:'sig'},
 {t:'A new system of units',what:'The units of some quantities are changed and you must find the new unit of another quantity.',steps:['Write the dimensions of the asked quantity in terms of the given ones.','Substitute the new units.'],ex:'Unit of force 100 N, length 10 m, time 1 s. From F = ma, M = F T² ÷ L = 100 × 1 ÷ 10 = 10 kg, so the unit of mass is 10 kg.',tp:'units'}
]};
})();
