/* Physica Tutor - answers learned from real student questions.
   Questions the tutor could not answer reach the Physica team (Google Form responses sheet);
   their answers are added here, chapter by chapter: [question, [keywords], answer]. */
(() => {
'use strict';
const T=(en,hl,hi)=>({en,hl,hi});
const L={
'Units and Measurements':[
  ['Why do we need standard units?',['standard unit','why units','need units','unit kyu','units kyun'],'Without a common standard, "5 hand-spans" means different lengths for different people. SI units (metre, kilogram, second...) are defined using constants of nature, so a measurement means exactly the same thing everywhere in the world.'],
  ['What is the difference between accuracy and precision?',['accuracy','precision','accurate','precise'],'Accuracy is how close a measurement is to the true value; precision is how close repeated measurements are to each other (and how fine the instrument reads). A badly zeroed vernier can be very precise (readings agree) but not accurate (all shifted by the zero error).'],
  ['What is zero error?',['zero error','negative zero','positive zero'],'Zero error is the reading an instrument shows when it should read zero (jaws closed). If the vernier zero is to the right of the main-scale zero, the error is positive and you subtract it; if it is to the left, the error is negative and you add its magnitude. Corrected reading = observed reading − zero error.'],
  ['What is the SI unit of force?',['unit of force','force ki unit','newton unit','si unit force'],T('The newton (N): 1 N is the force that gives 1 kg an acceleration of 1 m/s², so 1 N = 1 kg m s⁻².','Newton (N): 1 N woh force hai jo 1 kg ko 1 m/s² ka acceleration de, yaani 1 N = 1 kg m s⁻².','न्यूटन (N): 1 N वह बल है जो 1 kg को 1 m/s² का त्वरण दे, यानी 1 N = 1 kg m s⁻²।')],
  ['What is a parsec and an astronomical unit?',['parsec','astronomical unit','au unit','light year distance'],T('1 AU ≈ 1.5 × 10¹¹ m (Earth–Sun distance). 1 parsec ≈ 3.08 × 10¹⁶ m ≈ 3.26 light-years - the distance at which 1 AU subtends 1 arc-second.','1 AU ≈ 1.5 × 10¹¹ m (Dharti–Sooraj doori). 1 parsec ≈ 3.08 × 10¹⁶ m ≈ 3.26 light-year - woh doori jahan se 1 AU ek arc-second ka kon banata hai.','1 AU ≈ 1.5 × 10¹¹ m (पृथ्वी–सूर्य दूरी)। 1 पारसेक ≈ 3.08 × 10¹⁶ m ≈ 3.26 प्रकाश-वर्ष - वह दूरी जहाँ से 1 AU एक आर्क-सेकंड का कोण बनाता है।')],
  ['Why is an angle dimensionless?',['radian','angle dimension','dimensionless angle','angle ki dimension'],T('An angle in radians is arc length ÷ radius - a length divided by a length - so it has no dimensions, even though we write the unit rad.','Radian mein angle = arc length ÷ radius - length ko length se bhaag - isliye iski koi dimension nahi, bhale hi unit rad likhte hain.','रेडियन में कोण = चाप की लंबाई ÷ त्रिज्या - लंबाई को लंबाई से भाग - इसलिए इसकी कोई विमा नहीं, भले ही मात्रक rad लिखते हैं।')],
  ['What is order of magnitude?',['order of magnitude','order','power of ten'],T('It is the power of ten nearest to a quantity. Write it as a × 10ᵇ: if a ≤ 3.16 the order is b, otherwise b + 1. E.g. Earth’s radius 6.4 × 10⁶ m has order 7.','Ye kisi quantity ke sabse paas ki 10 ki power hai. a × 10ᵇ likho: a ≤ 3.16 ho toh order b, warna b + 1. Jaise Dharti ki radius 6.4 × 10⁶ m ka order 7.','यह किसी राशि के सबसे पास की 10 की घात है। a × 10ᵇ लिखो: a ≤ 3.16 हो तो कोटि b, वरना b + 1। जैसे पृथ्वी की त्रिज्या 6.4 × 10⁶ m की कोटि 7।')],
  ['Which errors are systematic and which are random?',['systematic error','random error','types of error','error ke prakar'],T('Systematic errors push every reading the same way (zero error, wrong calibration, parallax) - fix them by correction. Random errors scatter readings both ways (small fluctuations) - reduce them by taking many readings and averaging.','Systematic errors har reading ko ek hi taraf dhakelte hain (zero error, galat calibration, parallax) - correction se theek karo. Random errors readings ko dono taraf bikherte hain - zyada readings lekar average se kam karo.','क्रमबद्ध त्रुटियाँ हर पाठ्यांक को एक ही ओर धकेलती हैं (शून्य त्रुटि, ग़लत अंशांकन, लंबन) - संशोधन से ठीक करो। यादृच्छिक त्रुटियाँ पाठ्यांकों को दोनों ओर बिखेरती हैं - अधिक पाठ्यांक लेकर औसत से कम करो।')]],
'Motion in a Straight Line':[
  ['What is a frame of reference?',['frame of reference','reference frame','frame'],T('It is the viewpoint (an origin, axes and a clock) from which we describe motion. A passenger sitting in a train is at rest in the train’s frame but moving in the ground’s frame.','Ye woh nazariya (origin, axes aur ghadi) hai jahan se hum motion dekhte hain. Train mein baitha yaatri train ke frame mein ruka hai par zameen ke frame mein chal raha hai.','यह वह दृष्टिकोण (मूल बिंदु, अक्ष और घड़ी) है जहाँ से हम गति देखते हैं। ट्रेन में बैठा यात्री ट्रेन के फ़्रेम में रुका है पर ज़मीन के फ़्रेम में चल रहा है।')],
  ['What is the difference between uniform and non-uniform motion?',['uniform motion','non uniform','non-uniform','ek samaan gati'],T('Uniform motion: equal distances in equal time intervals (constant velocity, straight x-t graph). Non-uniform: unequal distances in equal intervals - the velocity changes and the x-t graph curves.','Uniform motion: barabar time mein barabar doori (constant velocity, seedha x-t graph). Non-uniform: barabar time mein alag doori - velocity badalti hai aur x-t graph mudta hai.','एकसमान गति: बराबर समय में बराबर दूरी (नियत वेग, सीधा x-t ग्राफ़)। असमान गति: बराबर समय में अलग दूरी - वेग बदलता है और x-t ग्राफ़ मुड़ता है।')],
  ['Can speed be negative?',['speed negative','negative speed','speed kabhi negative'],T('No. Speed is a magnitude, so it is always zero or positive. Velocity can be negative - the sign only shows direction along your chosen axis.','Nahi. Speed magnitude hai, isliye hamesha zero ya positive. Velocity negative ho sakti hai - sign sirf direction batata hai.','नहीं। चाल परिमाण है, इसलिए हमेशा शून्य या धनात्मक। वेग ऋणात्मक हो सकता है - चिह्न केवल दिशा बताता है।')],
  ['How do I convert km/h to m/s?',['km/h','kmph','convert','5/18','km per hour'],T('Multiply by 5/18 (because 1 km/h = 1000 m / 3600 s). So 72 km/h = 72 × 5/18 = 20 m/s. For m/s → km/h multiply by 18/5.','5/18 se guna karo (kyunki 1 km/h = 1000 m / 3600 s). Jaise 72 km/h = 72 × 5/18 = 20 m/s. m/s → km/h ke liye 18/5 se guna karo.','5/18 से गुणा करो (क्योंकि 1 km/h = 1000 m / 3600 s)। जैसे 72 km/h = 72 × 5/18 = 20 m/s। m/s → km/h के लिए 18/5 से गुणा करो।')],
  ['What do an odometer and a speedometer measure?',['odometer','speedometer','meter in car'],T('The odometer adds up the distance travelled; the speedometer shows the instantaneous speed at that moment.','Odometer chali hui kul doori jodta hai; speedometer us pal ki instantaneous speed dikhata hai.','ओडोमीटर तय की गई कुल दूरी जोड़ता है; स्पीडोमीटर उस क्षण की तात्क्षणिक चाल दिखाता है।')],
  ['What does a straight line v-t graph tell us?',['straight v-t','straight line graph velocity','uniformly accelerated'],T('A straight, sloping v-t line means uniform acceleration; its slope is a. A horizontal line means constant velocity (a = 0).','Seedhi tirchhi v-t line matlab uniform acceleration; slope = a. Horizontal line matlab constant velocity (a = 0).','सीधी तिरछी v-t रेखा मतलब एकसमान त्वरण; ढाल = a। क्षैतिज रेखा मतलब नियत वेग (a = 0)।')]],
'Motion in a Plane':[
  ['What is the difference between scalar and vector quantities?',['scalar','vector quantity','scalar vector','adish','sadish'],T('A scalar has only magnitude (mass, speed, time, energy). A vector has magnitude and direction and adds by the triangle/parallelogram law (displacement, velocity, force).','Scalar mein sirf magnitude hota hai (mass, speed, time, energy). Vector mein magnitude aur direction dono, aur ye triangle/parallelogram law se judte hain (displacement, velocity, force).','अदिश में केवल परिमाण होता है (द्रव्यमान, चाल, समय, ऊर्जा)। सदिश में परिमाण और दिशा दोनों, और ये त्रिभुज/समांतर चतुर्भुज नियम से जुड़ते हैं (विस्थापन, वेग, बल)।')],
  ['What is a unit vector?',['unit vector','i cap','j cap','î'],T('A vector of magnitude 1 that only shows direction: Â = A/|A|. î, ĵ, k̂ point along x, y and z.','Magnitude 1 wala vector jo sirf direction dikhata hai: Â = A/|A|. î, ĵ, k̂ x, y aur z ki taraf.','परिमाण 1 वाला सदिश जो केवल दिशा दिखाता है: Â = A/|A|। î, ĵ, k̂ x, y और z की ओर।')],
  ['Why is the path of a projectile a parabola?',['parabola','why parabola','path shape','parabolic'],T('x grows uniformly (x = u cos θ · t) while y has a t² term (y = u sin θ · t − ½gt²). Eliminating t gives y = x tan θ − gx²/(2u² cos²θ) - a quadratic in x, i.e. a parabola.','x barabar badhta hai (x = u cos θ · t) aur y mein t² term hai. t hatao toh y = x tan θ − gx²/(2u² cos²θ) - x ka quadratic, yaani parabola.','x बराबर बढ़ता है (x = u cos θ · t) और y में t² पद है। t हटाओ तो y = x tan θ − gx²/(2u² cos²θ) - x का द्विघात, यानी परवलय।')],
  ['How are linear and angular velocity related?',['angular velocity','omega','v = omega r','ω'],T('v = ωr: a point at radius r on something spinning at ω rad/s moves at speed ωr. ω = 2π/T = 2πf.','v = ωr: ω rad/s se ghoomti cheez par r doori ka point ωr speed se chalta hai. ω = 2π/T = 2πf.','v = ωr: ω rad/s से घूमती वस्तु पर r दूरी का बिंदु ωr चाल से चलता है। ω = 2π/T = 2πf।')],
  ['What is a null (zero) vector?',['null vector','zero vector','shunya sadish'],T('A vector of zero magnitude with no definite direction, e.g. A + (−A) or the displacement of a round trip.','Zero magnitude wala vector jiski koi tay direction nahi, jaise A + (−A) ya aane-jaane ka displacement.','शून्य परिमाण वाला सदिश जिसकी कोई निश्चित दिशा नहीं, जैसे A + (−A) या आने-जाने का विस्थापन।')],
  ['Is centripetal acceleration constant in uniform circular motion?',['centripetal constant','acceleration constant circle'],T('Its magnitude v²/r is constant, but its direction keeps turning towards the centre, so the acceleration vector is not constant.','Iska magnitude v²/r constant hai, par direction centre ki taraf ghoomti rehti hai, isliye acceleration vector constant nahi.','इसका परिमाण v²/r नियत है, पर दिशा केंद्र की ओर घूमती रहती है, इसलिए त्वरण सदिश नियत नहीं।')]],
'Laws of Motion':[
  ['What is the difference between mass and weight?',['mass and weight','mass weight','dravyaman','bhaar','weight difference'],T('Mass (kg) is the amount of matter and the measure of inertia - the same everywhere. Weight (N) is the gravitational pull mg - it changes with g (on the Moon it is about 1/6).','Mass (kg) padarth ki matra aur inertia ka naap hai - har jagah same. Weight (N) gravity ka kheenchav mg hai - g ke saath badalta hai (Chaand par lagbhag 1/6).','द्रव्यमान (kg) पदार्थ की मात्रा और जड़त्व का माप है - हर जगह समान। भार (N) गुरुत्व का खिंचाव mg है - g के साथ बदलता है (चाँद पर लगभग 1/6)।')],
  ['Why do we wear seat belts?',['seat belt','seatbelt','car crash'],T('In a sudden stop your body keeps moving forward (inertia). The belt supplies the force to stop you over a longer time and distance, reducing the force on you (impulse).','Achanak rukne par shareer aage chalta rehta hai (inertia). Belt tumhe zyada time aur doori mein rokne ka force deti hai, isliye tum par force kam lagta hai (impulse).','अचानक रुकने पर शरीर आगे चलता रहता है (जड़त्व)। बेल्ट तुम्हें अधिक समय और दूरी में रोकने का बल देती है, इसलिए तुम पर बल कम लगता है (आवेग)।')],
  ['Why is it difficult to walk on ice?',['walk on ice','ice slip','slippery','fisalna'],T('Walking needs friction: you push the ground back and friction pushes you forward. Ice gives very little friction, so your foot slips.','Chalne ke liye friction chahiye: tum zameen ko peeche dhakelte ho aur friction tumhe aage. Barf par friction bahut kam hai, isliye pair fisalta hai.','चलने के लिए घर्षण चाहिए: तुम ज़मीन को पीछे धकेलते हो और घर्षण तुम्हें आगे। बर्फ़ पर घर्षण बहुत कम है, इसलिए पैर फिसलता है।')],
  ['Why does a long jumper run before jumping?',['long jump','run before jump','athlete run'],T('Inertia of motion: the speed gained in the run-up is carried into the jump, so the jumper travels farther.','Inertia of motion: daud se mili speed jump mein saath rehti hai, isliye jumper zyada door jaata hai.','गति का जड़त्व: दौड़ से मिली चाल छलाँग में साथ रहती है, इसलिए खिलाड़ी अधिक दूर जाता है।')],
  ['Is centrifugal force real?',['centrifugal','centrifugal force'],T('In the ground (inertial) frame only the centripetal force acts. Centrifugal force is a pseudo force (mv²/r outward) that appears only when you work in the rotating frame.','Zameen (inertial) frame mein sirf centripetal force lagta hai. Centrifugal ek pseudo force (mv²/r bahar ki taraf) hai jo sirf ghoomte frame mein dikhta hai.','ज़मीन (जड़त्वीय) फ़्रेम में केवल अभिकेंद्र बल लगता है। अपकेंद्र एक छद्म बल (mv²/r बाहर की ओर) है जो केवल घूमते फ़्रेम में दिखता है।')],
  ['Why is tension the same throughout a light string?',['tension same','tension string','light string','massless string'],T('For a massless string, the net force on any piece must be zero (F = ma with m = 0), so the pull is the same along it - as long as it passes over frictionless pulleys.','Massless string ke kisi bhi hisse par net force zero hona chahiye (m = 0 ke saath F = ma), isliye poori string mein kheench same - jab tak pulley chikni ho.','द्रव्यमानरहित डोरी के किसी भी भाग पर कुल बल शून्य होना चाहिए (m = 0 के साथ F = ma), इसलिए पूरी डोरी में खिंचाव समान - जब तक घिरनी चिकनी हो।')]]
};
const CH=window.PhysicaTutorChapters=window.PhysicaTutorChapters||{};
for(const [name,list] of Object.entries(L)){const c=CH[name]||(CH[name]={qa:[],quiz:[]});for(const [q,k,a] of list)c.qa.push({q,k,a:()=>a})}
})();
