/* Physica Exam - board-pattern and NEET-style practice questions for the tutor's "Exam" tab.
   Each question is written in three languages (en = English, hl = Hinglish, hi = Hindi) with a step-by-step answer.
   t: '1' = 1 mark, '3' = 2-3 marks, '5' = 5 marks, 'mcq' = NEET-style MCQ (o = options, c = correct option).
   sim: the experiment where the idea can be tried out. Chapters so far: Units and Measurements. */
(() => {
'use strict';
const T=(en,hl,hi)=>({en,hl,hi});
window.PhysicaExam={
'Units and Measurements':[
  {t:'1',q:T('What is the SI unit of luminous intensity?','Luminous intensity ki SI unit kya hai?','ज्योति तीव्रता (luminous intensity) का SI मात्रक क्या है?'),
    a:T('candela (cd). It is one of the seven SI base units.','candela (cd). Ye saat SI base units mein se ek hai.','कैंडेला (cd)। यह सात SI मूल मात्रकों में से एक है।')},
  {t:'1',q:T('A light-year is a unit of which quantity? Give its value in metres.','Light-year kis quantity ki unit hai? Iski value metre mein batao.','प्रकाश-वर्ष किस राशि का मात्रक है? इसका मान मीटर में बताइए।'),
    a:T('Distance (not time). It is the distance light travels in one year:\n1 ly = 3×10⁸ m/s × 3.156×10⁷ s ≈ 9.46×10¹⁵ m.','Distance ki (time ki nahi). Ek saal mein light jitni doori tay karti hai:\n1 ly = 3×10⁸ m/s × 3.156×10⁷ s ≈ 9.46×10¹⁵ m.','दूरी का (समय का नहीं)। प्रकाश एक वर्ष में जितनी दूरी तय करता है:\n1 ly = 3×10⁸ m/s × 3.156×10⁷ s ≈ 9.46×10¹⁵ m।')},
  {t:'1',q:T('How many significant figures are there in 0.007 m²?','0.007 m² mein kitne significant figures hain?','0.007 m² में कितने सार्थक अंक हैं?'),
    a:T('One. Zeros before the first non-zero digit only fix the decimal point, so only the 7 counts.','Ek. Pehle non-zero digit se pehle ke zeros sirf decimal ki jagah batate hain, isliye sirf 7 count hota hai.','एक। पहले अशून्य अंक से पहले के शून्य केवल दशमलव का स्थान बताते हैं, इसलिए केवल 7 गिना जाता है।')},
  {t:'1',sim:'units',q:T('Define the least count of a vernier caliper.','Vernier caliper ka least count define karo.','वर्नियर कैलिपर्स का अल्पतमांक परिभाषित कीजिए।'),
    a:T('Least count = 1 main scale division − 1 vernier scale division.\nFor 10 VSD = 9 MSD of 1 mm: LC = 1 − 0.9 = 0.1 mm.','Least count = 1 MSD − 1 VSD.\nAgar 10 VSD = 9 MSD (1 mm wale): LC = 1 − 0.9 = 0.1 mm.','अल्पतमांक = 1 मुख्य पैमाना भाग − 1 वर्नियर पैमाना भाग।\nयदि 10 VSD = 9 MSD (1 mm वाले): LC = 1 − 0.9 = 0.1 mm।')},
  {t:'1',q:T('How many dynes make one newton?','Ek newton mein kitne dyne hote hain?','एक न्यूटन में कितने डाइन होते हैं?'),
    a:T('1 N = 1 kg·m/s² = 1000 g × 100 cm/s² = 10⁵ dyne.','1 N = 1 kg·m/s² = 1000 g × 100 cm/s² = 10⁵ dyne.','1 N = 1 kg·m/s² = 1000 g × 100 cm/s² = 10⁵ डाइन।')},
  {t:'1',sim:'parallax',q:T('Define one parsec.','Ek parsec define karo.','एक पारसेक परिभाषित कीजिए।'),
    a:T('The distance at which 1 AU (Earth–Sun distance) subtends an angle of 1 arcsecond.\n1 pc ≈ 3.08×10¹⁶ m ≈ 3.26 light-years.','Wo doori jahan se 1 AU (Earth–Sun doori) 1 arcsecond ka angle banati hai.\n1 pc ≈ 3.08×10¹⁶ m ≈ 3.26 light-year.','वह दूरी जहाँ से 1 AU (पृथ्वी–सूर्य दूरी) 1 आर्कसेकंड का कोण बनाती है।\n1 pc ≈ 3.08×10¹⁶ m ≈ 3.26 प्रकाश-वर्ष।')},
  {t:'3',sim:'dimensional-analysis',q:T('State the principle of homogeneity of dimensions. Use it to check v = u + at.','Dimensions ki homogeneity ka principle batao. Isse v = u + at check karo.','विमाओं की समांगता का सिद्धांत लिखिए। इससे v = u + at की जाँच कीजिए।'),
    a:T('Every term added or equated in a correct equation must have the same dimensions.\n[v] = [LT⁻¹], [u] = [LT⁻¹], [at] = [LT⁻²][T] = [LT⁻¹].\nAll three terms match, so the equation is dimensionally correct.','Sahi equation mein jode ya barabar kiye gaye har term ki dimensions same honi chahiye.\n[v] = [LT⁻¹], [u] = [LT⁻¹], [at] = [LT⁻²][T] = [LT⁻¹].\nTeeno match karte hain, isliye equation dimensionally sahi hai.','सही समीकरण में जोड़े या बराबर किए गए हर पद की विमाएँ समान होनी चाहिए।\n[v] = [LT⁻¹], [u] = [LT⁻¹], [at] = [LT⁻²][T] = [LT⁻¹]।\nतीनों मेल खाते हैं, इसलिए समीकरण विमीय रूप से सही है।')},
  {t:'3',q:T('Find the dimensions of Planck\'s constant h, using E = hν.','E = hν se Planck constant h ki dimensions nikalo.','E = hν से प्लांक नियतांक h की विमाएँ ज्ञात कीजिए।'),
    a:T('h = E/ν.\n[E] = [ML²T⁻²], [ν] = [T⁻¹].\n[h] = [ML²T⁻²]/[T⁻¹] = [ML²T⁻¹] - the same as angular momentum.','h = E/ν.\n[E] = [ML²T⁻²], [ν] = [T⁻¹].\n[h] = [ML²T⁻²]/[T⁻¹] = [ML²T⁻¹] - angular momentum jaisi hi.','h = E/ν।\n[E] = [ML²T⁻²], [ν] = [T⁻¹]।\n[h] = [ML²T⁻²]/[T⁻¹] = [ML²T⁻¹] - कोणीय संवेग के समान।')},
  {t:'3',q:T('Round off 2.745 and 2.735 to three significant figures.','2.745 aur 2.735 ko teen significant figures tak round off karo.','2.745 और 2.735 को तीन सार्थक अंकों तक पूर्णांकित कीजिए।'),
    a:T('When the dropped digit is exactly 5, the previous digit stays the same if it is even and goes up by 1 if it is odd.\n2.745 → 2.74 (4 is even)\n2.735 → 2.74 (3 is odd, becomes 4)','Jab hataya gaya digit theek 5 ho: pichhla digit even hai to waisa hi rehta hai, odd hai to 1 badh jata hai.\n2.745 → 2.74 (4 even hai)\n2.735 → 2.74 (3 odd hai, 4 ban gaya)','जब हटाया गया अंक ठीक 5 हो: पिछला अंक सम हो तो वैसा ही रहता है, विषम हो तो 1 बढ़ जाता है।\n2.745 → 2.74 (4 सम है)\n2.735 → 2.74 (3 विषम है, 4 बन गया)')},
  {t:'3',q:T('In van der Waals\' equation (P + a/V²)(V − b) = RT, find the dimensions of a and b.','Van der Waals equation (P + a/V²)(V − b) = RT mein a aur b ki dimensions nikalo.','वान्डर वाल्स समीकरण (P + a/V²)(V − b) = RT में a और b की विमाएँ ज्ञात कीजिए।'),
    a:T('Only like quantities can be added or subtracted.\na/V² has the dimensions of pressure: a = [ML⁻¹T⁻²][L³]² = [ML⁵T⁻²].\nb has the dimensions of volume: b = [L³].','Sirf ek jaisi quantities hi jod/ghata sakte hain.\na/V² ki dimensions pressure jaisi: a = [ML⁻¹T⁻²][L³]² = [ML⁵T⁻²].\nb ki dimensions volume jaisi: b = [L³].','केवल समान राशियाँ ही जोड़ी/घटाई जा सकती हैं।\na/V² की विमाएँ दाब के समान: a = [ML⁻¹T⁻²][L³]² = [ML⁵T⁻²]।\nb की विमाएँ आयतन के समान: b = [L³]।')},
  {t:'3',sim:'screw-gauge',q:T('A screw gauge has pitch 0.5 mm and 50 circular divisions. The main scale reads 3 mm and the 35th circular division is on the line. Find the reading.','Screw gauge ka pitch 0.5 mm aur 50 circular divisions hain. Main scale 3 mm aur 35th circular division line par hai. Reading nikalo.','स्क्रू गेज का पिच 0.5 mm और वृत्तीय पैमाने पर 50 भाग हैं। मुख्य पैमाना 3 mm तथा 35वाँ वृत्तीय भाग रेखा पर है। पाठ्यांक ज्ञात कीजिए।'),
    a:T('LC = pitch / divisions = 0.5/50 = 0.01 mm.\nReading = MSR + CSR × LC = 3 + 35 × 0.01 = 3.35 mm.','LC = pitch / divisions = 0.5/50 = 0.01 mm.\nReading = MSR + CSR × LC = 3 + 35 × 0.01 = 3.35 mm.','LC = पिच / भाग = 0.5/50 = 0.01 mm।\nपाठ्यांक = MSR + CSR × LC = 3 + 35 × 0.01 = 3.35 mm।')},
  {t:'3',sim:'units',q:T('A vernier caliper has least count 0.1 mm. The main scale reads 12 mm and the 7th vernier division coincides. Find the length.','Vernier caliper ka LC 0.1 mm hai. Main scale 12 mm aur 7th vernier division coincide karta hai. Length nikalo.','वर्नियर कैलिपर्स का अल्पतमांक 0.1 mm है। मुख्य पैमाना 12 mm तथा 7वाँ वर्नियर भाग संपाती है। लंबाई ज्ञात कीजिए।'),
    a:T('Length = MSR + VSR × LC = 12 + 7 × 0.1 = 12.7 mm.','Length = MSR + VSR × LC = 12 + 7 × 0.1 = 12.7 mm.','लंबाई = MSR + VSR × LC = 12 + 7 × 0.1 = 12.7 mm।')},
  {t:'3',sim:'screw-gauge',q:T('A screw gauge has a zero error of −0.03 mm. A wire reads 2.48 mm. What is its true diameter?','Screw gauge ki zero error −0.03 mm hai. Wire ki reading 2.48 mm aati hai. Asli diameter kya hai?','स्क्रू गेज की शून्यांक त्रुटि −0.03 mm है। तार का पाठ्यांक 2.48 mm है। वास्तविक व्यास क्या है?'),
    a:T('True reading = observed − zero error = 2.48 − (−0.03) = 2.51 mm.\n(A negative zero error is added.)','Asli reading = observed − zero error = 2.48 − (−0.03) = 2.51 mm.\n(Negative zero error jodi jaati hai.)','वास्तविक पाठ्यांक = प्रेक्षित − शून्यांक त्रुटि = 2.48 − (−0.03) = 2.51 mm।\n(ऋणात्मक शून्यांक त्रुटि जोड़ी जाती है।)')},
  {t:'3',sim:'uncertainty',q:T('Distinguish between accuracy and precision.','Accuracy aur precision mein antar batao.','यथार्थता (accuracy) और परिशुद्धता (precision) में अंतर बताइए।'),
    a:T('Accuracy: how close a measurement is to the true value.\nPrecision: how close repeated measurements are to each other (set by the least count).\nExample: true length 3.678 cm. Readings 3.5 cm (LC 0.1 cm) and 3.38 cm (LC 0.01 cm): the first is more accurate, the second more precise.','Accuracy: measurement asli value ke kitna paas hai.\nPrecision: baar-baar ki readings aapas mein kitni paas hain (least count se tay hoti hai).\nUdaharan: asli length 3.678 cm. Readings 3.5 cm (LC 0.1 cm) aur 3.38 cm (LC 0.01 cm): pehli zyada accurate, doosri zyada precise.','यथार्थता: माप वास्तविक मान के कितना निकट है।\nपरिशुद्धता: बार-बार के माप आपस में कितने निकट हैं (अल्पतमांक से तय)।\nउदाहरण: वास्तविक लंबाई 3.678 cm। माप 3.5 cm (LC 0.1 cm) और 3.38 cm (LC 0.01 cm): पहला अधिक यथार्थ, दूसरा अधिक परिशुद्ध।')},
  {t:'3',sim:'error-propagation',q:T('P = a²b³/(c√d). The percentage errors in a, b, c, d are 1%, 2%, 3% and 4%. Find the percentage error in P.','P = a²b³/(c√d). a, b, c, d mein percentage error 1%, 2%, 3% aur 4% hai. P mein percentage error nikalo.','P = a²b³/(c√d)। a, b, c, d में प्रतिशत त्रुटि 1%, 2%, 3% तथा 4% है। P में प्रतिशत त्रुटि ज्ञात कीजिए।'),
    a:T('Errors always add, each multiplied by its power:\nΔP/P = 2(1%) + 3(2%) + 1(3%) + ½(4%) = 2 + 6 + 3 + 2 = 13%.','Errors hamesha judte hain, har ek apni power se guna hokar:\nΔP/P = 2(1%) + 3(2%) + 1(3%) + ½(4%) = 2 + 6 + 3 + 2 = 13%.','त्रुटियाँ सदा जुड़ती हैं, प्रत्येक अपनी घात से गुणा होकर:\nΔP/P = 2(1%) + 3(2%) + 1(3%) + ½(4%) = 2 + 6 + 3 + 2 = 13%।')},
  {t:'3',sim:'dimensional-analysis',q:T('Write any three limitations of dimensional analysis.','Dimensional analysis ki koi teen limitations likho.','विमीय विश्लेषण की कोई तीन सीमाएँ लिखिए।'),
    a:T('1. It cannot find dimensionless constants (like 2π in T = 2π√(l/g)).\n2. It cannot derive relations with sin, log or exponential terms.\n3. It cannot handle a quantity that depends on more than three others (only three equations from M, L, T).\n4. A dimensionally correct equation is not necessarily physically correct.','1. Dimensionless constants (jaise T = 2π√(l/g) mein 2π) nahi nikal sakte.\n2. sin, log ya exponential wale relations derive nahi hote.\n3. Teen se zyada quantities par depend karne wala relation nahi nikalta (M, L, T se sirf teen equations).\n4. Dimensionally sahi equation zaroori nahi ki physically bhi sahi ho.','1. विमाहीन नियतांक (जैसे T = 2π√(l/g) में 2π) ज्ञात नहीं कर सकते।\n2. sin, log या घातांकी पदों वाले संबंध व्युत्पन्न नहीं होते।\n3. तीन से अधिक राशियों पर निर्भर संबंध नहीं मिलता (M, L, T से केवल तीन समीकरण)।\n4. विमीय रूप से सही समीकरण भौतिक रूप से भी सही हो, यह आवश्यक नहीं।')},
  {t:'5',sim:'dimensional-analysis',q:T('The time period T of a simple pendulum depends on its length l, the mass m of the bob and g. Derive the formula using dimensions.','Simple pendulum ka time period T length l, bob ke mass m aur g par depend karta hai. Dimensions se formula derive karo.','सरल लोलक का आवर्तकाल T, लंबाई l, गोलक के द्रव्यमान m और g पर निर्भर करता है। विमाओं से सूत्र व्युत्पन्न कीजिए।'),
    a:T('Let T = k lᵃ mᵇ gᶜ (k has no dimensions).\n[T] = [L]ᵃ [M]ᵇ [LT⁻²]ᶜ = [Mᵇ Lᵃ⁺ᶜ T⁻²ᶜ].\nCompare powers: M: b = 0; T: −2c = 1 → c = −½; L: a + c = 0 → a = ½.\nSo T = k√(l/g). It does not depend on mass. Experiment gives k = 2π, so T = 2π√(l/g).','Maan lo T = k lᵃ mᵇ gᶜ (k dimensionless hai).\n[T] = [L]ᵃ [M]ᵇ [LT⁻²]ᶜ = [Mᵇ Lᵃ⁺ᶜ T⁻²ᶜ].\nPowers compare karo: M: b = 0; T: −2c = 1 → c = −½; L: a + c = 0 → a = ½.\nIsliye T = k√(l/g). Mass par depend nahi karta. Experiment se k = 2π, to T = 2π√(l/g).','माना T = k lᵃ mᵇ gᶜ (k विमाहीन है)।\n[T] = [L]ᵃ [M]ᵇ [LT⁻²]ᶜ = [Mᵇ Lᵃ⁺ᶜ T⁻²ᶜ]।\nघातों की तुलना: M: b = 0; T: −2c = 1 → c = −½; L: a + c = 0 → a = ½।\nअतः T = k√(l/g)। यह द्रव्यमान पर निर्भर नहीं करता। प्रयोग से k = 2π, अतः T = 2π√(l/g)।')},
  {t:'5',q:T('The force F on a body moving in a circle depends on its mass m, speed v and radius r. Derive the formula using dimensions.','Circle mein ghoom rahi body par force F, mass m, speed v aur radius r par depend karta hai. Dimensions se formula derive karo.','वृत्त में गतिमान वस्तु पर बल F, उसके द्रव्यमान m, चाल v और त्रिज्या r पर निर्भर है। विमाओं से सूत्र व्युत्पन्न कीजिए।'),
    a:T('Let F = k mᵃ vᵇ rᶜ.\n[MLT⁻²] = [M]ᵃ [LT⁻¹]ᵇ [L]ᶜ = [Mᵃ Lᵇ⁺ᶜ T⁻ᵇ].\nCompare: a = 1; −b = −2 → b = 2; b + c = 1 → c = −1.\nSo F = k mv²/r (with k = 1: F = mv²/r).','Maan lo F = k mᵃ vᵇ rᶜ.\n[MLT⁻²] = [M]ᵃ [LT⁻¹]ᵇ [L]ᶜ = [Mᵃ Lᵇ⁺ᶜ T⁻ᵇ].\nCompare: a = 1; −b = −2 → b = 2; b + c = 1 → c = −1.\nIsliye F = k mv²/r (k = 1 lene par F = mv²/r).','माना F = k mᵃ vᵇ rᶜ।\n[MLT⁻²] = [M]ᵃ [LT⁻¹]ᵇ [L]ᶜ = [Mᵃ Lᵇ⁺ᶜ T⁻ᵇ]।\nतुलना: a = 1; −b = −2 → b = 2; b + c = 1 → c = −1।\nअतः F = k mv²/r (k = 1 लेने पर F = mv²/r)।')},
  {t:'5',sim:'uncertainty',q:T('The period of a pendulum is measured as 2.63 s, 2.56 s, 2.42 s, 2.71 s and 2.80 s. Find the mean value, mean absolute error, relative error and percentage error.','Pendulum ka period 2.63 s, 2.56 s, 2.42 s, 2.71 s aur 2.80 s mila. Mean value, mean absolute error, relative error aur percentage error nikalo.','लोलक का आवर्तकाल 2.63 s, 2.56 s, 2.42 s, 2.71 s तथा 2.80 s मापा गया। माध्य मान, माध्य निरपेक्ष त्रुटि, आपेक्षिक त्रुटि और प्रतिशत त्रुटि ज्ञात कीजिए।'),
    a:T('Mean T = (2.63 + 2.56 + 2.42 + 2.71 + 2.80)/5 = 13.12/5 = 2.624 ≈ 2.62 s.\nAbsolute errors: 0.01, 0.06, 0.20, 0.09, 0.18 s.\nMean absolute error = 0.54/5 = 0.108 ≈ 0.11 s.\nResult: T = 2.62 ± 0.11 s.\nRelative error = 0.11/2.62 ≈ 0.04; percentage error ≈ 4%.','Mean T = (2.63 + 2.56 + 2.42 + 2.71 + 2.80)/5 = 13.12/5 = 2.624 ≈ 2.62 s.\nAbsolute errors: 0.01, 0.06, 0.20, 0.09, 0.18 s.\nMean absolute error = 0.54/5 = 0.108 ≈ 0.11 s.\nResult: T = 2.62 ± 0.11 s.\nRelative error = 0.11/2.62 ≈ 0.04; percentage error ≈ 4%.','माध्य T = (2.63 + 2.56 + 2.42 + 2.71 + 2.80)/5 = 13.12/5 = 2.624 ≈ 2.62 s।\nनिरपेक्ष त्रुटियाँ: 0.01, 0.06, 0.20, 0.09, 0.18 s।\nमाध्य निरपेक्ष त्रुटि = 0.54/5 = 0.108 ≈ 0.11 s।\nपरिणाम: T = 2.62 ± 0.11 s।\nआपेक्षिक त्रुटि = 0.11/2.62 ≈ 0.04; प्रतिशत त्रुटि ≈ 4%।')},
  {t:'mcq',q:T('The dimensional formula of the gravitational constant G is:','Gravitational constant G ka dimensional formula hai:','गुरुत्वीय नियतांक G का विमीय सूत्र है:'),o:['[M⁻¹L³T⁻²]','[ML²T⁻²]','[M⁻¹L²T⁻¹]','[ML³T⁻²]'],c:0,
    a:T('F = Gm²/r² → G = Fr²/m² = [MLT⁻²][L²]/[M²] = [M⁻¹L³T⁻²].','F = Gm²/r² → G = Fr²/m² = [MLT⁻²][L²]/[M²] = [M⁻¹L³T⁻²].','F = Gm²/r² → G = Fr²/m² = [MLT⁻²][L²]/[M²] = [M⁻¹L³T⁻²]।')},
  {t:'mcq',q:T('How many significant figures are there in 6.320?','6.320 mein kitne significant figures hain?','6.320 में कितने सार्थक अंक हैं?'),o:['2','3','4','5'],c:2,
    a:T('Four. A trailing zero after the decimal point is significant.','Chaar. Decimal ke baad aakhri zero significant hota hai.','चार। दशमलव के बाद अंत का शून्य सार्थक होता है।')},
  {t:'mcq',sim:'error-propagation',q:T('The radius of a sphere is measured with a 2% error. The error in its volume is:','Sphere ki radius 2% error ke saath naapi gayi. Volume mein error hoga:','गोले की त्रिज्या 2% त्रुटि से मापी गई। आयतन में त्रुटि होगी:'),o:['2%','4%','6%','8%'],c:2,
    a:T('V = (4/3)πr³, so ΔV/V = 3 × Δr/r = 3 × 2% = 6%.','V = (4/3)πr³, isliye ΔV/V = 3 × Δr/r = 3 × 2% = 6%.','V = (4/3)πr³, अतः ΔV/V = 3 × Δr/r = 3 × 2% = 6%।')},
  {t:'mcq',q:T('Which pair has the same dimensions?','Kis pair ki dimensions same hain?','किस युग्म की विमाएँ समान हैं?'),o:['Work and power','Work and torque','Force and momentum','Impulse and force'],c:1,
    a:T('Work = F × d and torque = r × F, both [ML²T⁻²].','Work = F × d aur torque = r × F, dono [ML²T⁻²].','कार्य = F × d और बल-आघूर्ण = r × F, दोनों [ML²T⁻²]।')},
  {t:'mcq',sim:'screw-gauge',q:T('A screw gauge has pitch 1 mm and 100 circular divisions. Its least count is:','Screw gauge ka pitch 1 mm aur 100 circular divisions hain. Least count hai:','स्क्रू गेज का पिच 1 mm और 100 वृत्तीय भाग हैं। अल्पतमांक है:'),o:['0.1 mm','0.01 mm','0.001 mm','1 mm'],c:1,
    a:T('LC = pitch / number of divisions = 1/100 = 0.01 mm.','LC = pitch / divisions = 1/100 = 0.01 mm.','LC = पिच / भागों की संख्या = 1/100 = 0.01 mm।')},
  {t:'mcq',q:T('4.234 × 1.005, written to the correct significant figures, is:','4.234 × 1.005 ko sahi significant figures mein likho:','4.234 × 1.005 सही सार्थक अंकों में है:'),o:['4.255','4.2552','4.26','4.25517'],c:0,
    a:T('4.234 × 1.005 = 4.25517. Both numbers have 4 significant figures, so the answer keeps 4: 4.255.','4.234 × 1.005 = 4.25517. Dono numbers mein 4 significant figures, to answer mein bhi 4: 4.255.','4.234 × 1.005 = 4.25517। दोनों संख्याओं में 4 सार्थक अंक हैं, अतः उत्तर में भी 4: 4.255।')},
  {t:'mcq',q:T('The SI unit of impulse is:','Impulse ki SI unit hai:','आवेग का SI मात्रक है:'),o:['N/s','N·s','N·m','kg/s'],c:1,
    a:T('Impulse = force × time, so N·s (= kg·m/s, the unit of momentum).','Impulse = force × time, isliye N·s (= kg·m/s, momentum ki unit).','आवेग = बल × समय, अतः N·s (= kg·m/s, संवेग का मात्रक)।')}
]};
})();
