/* Writes _redirects so Netlify answers 404 for every file that is not part of the public site:
   the readable source scripts (only the built *.min.js bundles, ga.js and sw.js are public), tools/, notes, configs.
   Runs at the end of every build, so new source files are covered automatically. */
const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),PUBLIC_JS=new Set(['ga.js','sw.js']);
const out=['# generated by tools/lockdown.js - do not edit'];
for(const f of fs.readdirSync(root).sort()){
  if(f.endsWith('.js')&&!f.endsWith('.min.js')&&!PUBLIC_JS.has(f))out.push(`/${f} /404.html 404!`);
  if(/\.(md|gs|log|map|bak|orig|env|key|pem|json)$/.test(f)&&f!=='manifest.webmanifest')out.push(`/${f} /404.html 404!`);
}
out.push('/tools/* /404.html 404!','/.git/* /404.html 404!','/.git /404.html 404!','/.github/* /404.html 404!','/.env* /404.html 404!',
  '/START-HERE.txt /404.html 404!','/netlify.toml /404.html 404!','/_headers /404.html 404!','/_redirects /404.html 404!','/.gitignore /404.html 404!','/*.map /404.html 404!','/*.tmp.js /404.html 404!','/.*.tmp.js /404.html 404!');
fs.writeFileSync(path.join(root,'_redirects'),out.join('\n')+'\n');
console.log('lockdown: '+(out.length-1)+' rules');
